#pragma once
// Augmatch public umbrella header. Include this file to access the complete API.
#include "augmatch/arithmetic.hpp"
// bayer.hpp also exposes Quad-Bayer, RGBW, and custom-mask CFA sampling.
#include "augmatch/bayer.hpp"
#include "augmatch/blend.hpp"
#include "augmatch/canny.hpp"
// color.hpp includes RGB/YCbCr photometric, gain-noise, temperature-error, chroma-subsampling, and local-tone APIs.
#include "augmatch/color.hpp"
#include "augmatch/colorspace.hpp"
#include "augmatch/composition.hpp"
#include "augmatch/convert.hpp"
#include "augmatch/dithering.hpp"
#include "augmatch/derivative.hpp"
#include "augmatch/dropout.hpp"
#include "augmatch/environmental.hpp"
#include "augmatch/execution.hpp"
// filter.hpp includes convolution, deterministic optical motion, and aperture PSF artifacts.
#include "augmatch/filter.hpp"
// geometric.hpp includes affine-compatible focus-breathing radial scaling.
#include "augmatch/geometric.hpp"
#include "augmatch/hsv.hpp"
#include "augmatch/image.hpp"
#include "augmatch/meta.hpp"
#include "augmatch/mixing.hpp"
#include "augmatch/iso_profile.hpp"
#include "augmatch/imgcorruptlike.hpp"
// isp_artifacts.hpp includes derivative, demosaicing, block-compression, quantization, and clipping-ring surrogates.
#include "augmatch/isp_artifacts.hpp"
#include "augmatch/jpeg.hpp"
// noise.hpp includes sensor, row-phase temporal T-H-W-C batches, telegraph/video compression and motion surrogates, water-droplet lens records, optical gain, illumination, dust-shadow, and optical-scatter artifacts.
#include "augmatch/noise.hpp"
#include "augmatch/noise_view.hpp"
#include "augmatch/native_api.hpp"
#include "augmatch/sensor/api.hpp"
#include "augmatch/optics/api.hpp"
#include "augmatch/isp/api.hpp"
#include "augmatch/compression/api.hpp"
#include "augmatch/video/api.hpp"
#include "augmatch/remaining_catalog.hpp"
#include "augmatch/status.hpp"
#include "augmatch/pixel.hpp"
#include "augmatch/pillike.hpp"
#include "augmatch/pipeline.hpp"
#include "augmatch/pipeline_registry.hpp"
#include "augmatch/signal.hpp"
#include "augmatch/size.hpp"
#include "augmatch/superpixels.hpp"
#include "augmatch/voronoi.hpp"
#include "augmatch/tone.hpp"
#include "augmatch/target_metadata.hpp"
#include "augmatch/transport.hpp"
#include "augmatch/transforms.hpp"
#include "augmatch/weather.hpp"
#include "augmatch/webp.hpp"
#include "augmatch/video_codec.hpp"
