#pragma once
#include <cstdint>
#ifndef AUGMATCH_HAS_CUDA
#define AUGMATCH_HAS_CUDA 0
#endif
#if AUGMATCH_HAS_CUDA
#include <cuda_runtime_api.h>
#else
using cudaStream_t = void*;
#endif

namespace augmatch {

// A site is an integer pixel coordinate. Sites are ordered by their array/index
// order; equal distances select the lowest site index. Coordinates outside the
// image are rejected by the CPU API and are never generated by the built-ins.
struct VoronoiPoint { int x=0, y=0; };

// Generic seeded Voronoi. If points is non-null it borrows point_count records;
// otherwise point_count sites are generated uniformly from seed. The label-map
// operation writes the source mask value sampled at each site's pixel to every
// pixel in that site's cell. Thus targets are discrete labels, not interpolated
// image values. point_count must be positive and is also the number of cells.
struct VoronoiConfig {
  int width=0, height=0, point_count=16;
  std::uint64_t seed=0;
  const VoronoiPoint* points=nullptr;
};

// UniformVoronoi uses one deterministic jittered site per occupied stratum.
// point_count controls the number of sites/cells; seed controls jitter.
struct UniformVoronoiConfig {
  int width=0, height=0, point_count=16;
  std::uint64_t seed=0;
};

// RegularGridVoronoi puts one site at the centre of each grid cell. grid_width
// and grid_height are cell counts (and therefore also the maximum site count).
struct RegularGridVoronoiConfig {
  int width=0, height=0, grid_width=4, grid_height=4;
};

// RelativeRegularGridVoronoi treats relative_grid_width/height as cell widths
// relative to the full image extent. Values in (0,1] are required; ceil(1/r)
// cells are used on each axis, with a final partial cell at the boundary.
struct RelativeRegularGridVoronoiConfig {
  int width=0, height=0;
  float relative_grid_width=0.25f, relative_grid_height=0.25f;
};

// Each *_u8 function transforms a borrowed HxW discrete target mask. No target
// is created, blended, or resized: the nearest site's original target label is
// copied to the output. CPU pointers are host memory; CUDA pointers are device
// memory valid until stream completion.
void voronoi_u8(const std::uint8_t*, std::uint8_t*, const VoronoiConfig&, cudaStream_t stream=nullptr);
void uniform_voronoi_u8(const std::uint8_t*, std::uint8_t*, const UniformVoronoiConfig&, cudaStream_t stream=nullptr);
void regular_grid_voronoi_u8(const std::uint8_t*, std::uint8_t*, const RegularGridVoronoiConfig&, cudaStream_t stream=nullptr);
void relative_regular_grid_voronoi_u8(const std::uint8_t*, std::uint8_t*, const RelativeRegularGridVoronoiConfig&, cudaStream_t stream=nullptr);

// Label-map variants expose the selected site index rather than sampling a
// target mask. They are useful when the Voronoi partition itself is the target.
void voronoi_labels_u32(std::uint32_t*, const VoronoiConfig&, cudaStream_t stream=nullptr);
void uniform_voronoi_labels_u32(std::uint32_t*, const UniformVoronoiConfig&, cudaStream_t stream=nullptr);
void regular_grid_voronoi_labels_u32(std::uint32_t*, const RegularGridVoronoiConfig&, cudaStream_t stream=nullptr);
void relative_regular_grid_voronoi_labels_u32(std::uint32_t*, const RelativeRegularGridVoronoiConfig&, cudaStream_t stream=nullptr);

} // namespace augmatch
