#include "augmatch/blend.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__host__ __device__ unsigned long long mix(unsigned long long x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__host__ __device__ float unit(unsigned long long x){return (float)((mix(x)>>11)*(1.0/9007199254740992.0));}
__device__ unsigned char cv(float x){x=fminf(255.f,fmaxf(0.f,x));return (unsigned char)floorf(x+.5f);}
__device__ void put(const unsigned char*a,const unsigned char*b,unsigned char*o,int i,float z){z=fminf(1.f,fmaxf(0.f,z));o[i]=cv((1-z)*a[i]+z*b[i]);}
__global__ void scalar_k(const unsigned char*a,const unsigned char*b,unsigned char*o,BlendAlphaConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i<n)put(a,b,o,i,c.alpha);}
__global__ void mask_k(const unsigned char*a,const unsigned char*b,const unsigned char*m,unsigned char*o,BlendAlphaMaskConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i<n)put(a,b,o,i,m[i/c.channels]*c.mask_scale);}
__global__ void element_k(const unsigned char*a,const unsigned char*b,const unsigned char*m,unsigned char*o,BlendAlphaElementwiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i<n){int p=i/c.channels;float z=m?m[p]*c.mask_scale:c.min_alpha+(c.max_alpha-c.min_alpha)*unit(c.seed+(unsigned long long)p);put(a,b,o,i,z);}}
__global__ void simplex_k(const unsigned char*a,const unsigned char*b,unsigned char*o,BlendAlphaSimplexNoiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int p=i/c.channels,x=p%c.width,y=p/c.width;float f=fmaxf(.0001f,c.frequency),v=0,amp=1,total=0;for(int k=0;k<(c.octaves>0?c.octaves:1);++k){int gx=(int)floorf(x*f/c.width),gy=(int)floorf(y*f/c.height);v+=amp*unit(c.seed+(unsigned long long)gx*0x632be59bd9b4e019ULL+(unsigned long long)gy*0x8cb92baa5f3a2d17ULL+(unsigned long long)k*0x9e3779b9ULL);total+=amp;amp*=.5f;f*=2;}put(a,b,o,i,c.min_alpha+(c.max_alpha-c.min_alpha)*(total?v/total:.5f));}
__global__ void frequency_k(const unsigned char*a,const unsigned char*b,unsigned char*o,BlendAlphaFrequencyNoiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int p=i/c.channels,x=p%c.width,y=p/c.width;float w=.5f+.5f*sinf((x+c.seed%997)*c.frequency*6.2831853f/c.width)*cosf((y+c.seed%991)*c.frequency*6.2831853f/c.height);float z=c.min_alpha+(c.max_alpha-c.min_alpha) * fminf(1.f,fmaxf(0.f,.5f+c.amplitude*(w-.5f)));put(a,b,o,i,z);}
__global__ void colors_k(const unsigned char*a,const unsigned char*b,unsigned char*o,BlendAlphaSomeColorsConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int p=i/c.channels,base=p*c.channels;bool hit=false;for(int k=0;k<c.color_count&&!hit;++k){hit=true;for(int ch=0;ch<c.channels;++ch)if(fabsf((float)a[base+ch]-c.colors[k*c.channels+ch])>c.tolerance){hit=false;break;}}put(a,b,o,i,hit?c.alpha:0);}
__global__ void gradient_k(const unsigned char*a,const unsigned char*b,unsigned char*o,BlendAlphaGradientConfig c,bool vertical){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int p=i/c.channels,x=p%c.width,y=p/c.width;float t=vertical?(c.height==1?0.f:(float)y/(c.height-1)):(c.width==1?0.f:(float)x/(c.width-1));put(a,b,o,i,c.alpha_start+t*(c.alpha_end-c.alpha_start));}
__global__ void grid_k(const unsigned char*a,const unsigned char*b,unsigned char*o,BlendAlphaRegularGridConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int p=i/c.channels,x=p%c.width,y=p/c.width;put(a,b,o,i,(x%c.cell_width==0||y%c.cell_height==0)?c.alpha:0);}
__global__ void checker_k(const unsigned char*a,const unsigned char*b,unsigned char*o,BlendAlphaCheckerboardConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int p=i/c.channels,x=p%c.width,y=p/c.width;bool z=((x/c.cell_width+y/c.cell_height)&1)!=0;if(c.invert)z=!z;put(a,b,o,i,z?c.alpha:0);}
__global__ void seg_k(const unsigned char*a,const unsigned char*b,unsigned char*o,BlendAlphaSegMapClassIdsConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int p=i/c.channels;bool hit=false;for(int k=0;k<c.class_count;++k)if(c.seg_map[p]==c.class_ids[k])hit=true;put(a,b,o,i,hit?c.alpha:0);}
__global__ void boxes_k(const unsigned char*a,const unsigned char*b,unsigned char*o,BlendAlphaBoundingBoxesConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int p=i/c.channels,x=p%c.width,y=p/c.width;bool hit=false;for(int k=0;k<c.box_count;++k){BoxXYXY r=c.boxes[k];if(x>=r.x1&&x<r.x2&&y>=r.y1&&y<r.y2)hit=true;}put(a,b,o,i,hit?c.alpha:0);}
void check(cudaError_t e,const char*n){if(e!=cudaSuccess)throw std::runtime_error(std::string(n)+": "+cudaGetErrorString(e));}
void valid(const void*a,const void*b,const void*o,int w,int h,int c){if(!a||!b||!o||w<=0||h<=0||c<=0)throw std::invalid_argument("invalid blend configuration");}
template<class K,class C>void launch(K k,const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const C&c,cudaStream_t s,const char*n){valid(a,b,o,c.width,c.height,c.channels);int z=c.width*c.height*c.channels;k<<<(z+255)/256,256,0,s>>>(a,b,o,c);check(cudaGetLastError(),n);}
}
void blend_alpha_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaConfig&c,cudaStream_t s){launch(scalar_k,a,b,o,c,s,"blend_alpha");}
void blend_alpha_mask_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaMaskConfig&c,cudaStream_t s){blend_alpha_mask_u8(a,b,c.mask,o,c,s);}
void blend_alpha_mask_u8(const std::uint8_t*a,const std::uint8_t*b,const std::uint8_t*m,std::uint8_t*o,const BlendAlphaMaskConfig&c,cudaStream_t s){if(!m)throw std::invalid_argument("blend mask is null");valid(a,b,o,c.width,c.height,c.channels);int z=c.width*c.height*c.channels;mask_k<<<(z+255)/256,256,0,s>>>(a,b,m,o,c);check(cudaGetLastError(),"blend_alpha_mask");}
void blend_alpha_elementwise_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaElementwiseConfig&c,cudaStream_t s){blend_alpha_elementwise_u8(a,b,c.mask,o,c,s);}
void blend_alpha_elementwise_u8(const std::uint8_t*a,const std::uint8_t*b,const std::uint8_t*m,std::uint8_t*o,const BlendAlphaElementwiseConfig&c,cudaStream_t s){valid(a,b,o,c.width,c.height,c.channels);if(m==nullptr&&c.min_alpha>c.max_alpha)throw std::invalid_argument("invalid elementwise blend range");int z=c.width*c.height*c.channels;element_k<<<(z+255)/256,256,0,s>>>(a,b,m,o,c);check(cudaGetLastError(),"blend_alpha_elementwise");}
void blend_alpha_simplex_noise_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaSimplexNoiseConfig&c,cudaStream_t s){launch(simplex_k,a,b,o,c,s,"blend_alpha_simplex_noise");}
void blend_alpha_frequency_noise_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaFrequencyNoiseConfig&c,cudaStream_t s){launch(frequency_k,a,b,o,c,s,"blend_alpha_frequency_noise");}
void blend_alpha_some_colors_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaSomeColorsConfig&c,cudaStream_t s){if(c.color_count>0&&!c.colors)throw std::invalid_argument("SomeColors records are null");launch(colors_k,a,b,o,c,s,"blend_alpha_some_colors");}
void blend_alpha_horizontal_linear_gradient_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaGradientConfig&c,cudaStream_t s){valid(a,b,o,c.width,c.height,c.channels);int z=c.width*c.height*c.channels;gradient_k<<<(z+255)/256,256,0,s>>>(a,b,o,c,false);check(cudaGetLastError(),"blend_alpha_horizontal_gradient");}
void blend_alpha_vertical_linear_gradient_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaGradientConfig&c,cudaStream_t s){valid(a,b,o,c.width,c.height,c.channels);int z=c.width*c.height*c.channels;gradient_k<<<(z+255)/256,256,0,s>>>(a,b,o,c,true);check(cudaGetLastError(),"blend_alpha_vertical_gradient");}
void blend_alpha_regular_grid_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaRegularGridConfig&c,cudaStream_t s){launch(grid_k,a,b,o,c,s,"blend_alpha_regular_grid");}
void blend_alpha_checkerboard_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaCheckerboardConfig&c,cudaStream_t s){launch(checker_k,a,b,o,c,s,"blend_alpha_checkerboard");}
void blend_alpha_seg_map_class_ids_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaSegMapClassIdsConfig&c,cudaStream_t s){if(!c.seg_map||c.class_count>0&&!c.class_ids)throw std::invalid_argument("invalid segmentation metadata");launch(seg_k,a,b,o,c,s,"blend_alpha_seg_map");}
void blend_alpha_bounding_boxes_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaBoundingBoxesConfig&c,cudaStream_t s){if(c.box_count>0&&!c.boxes)throw std::invalid_argument("invalid box metadata");launch(boxes_k,a,b,o,c,s,"blend_alpha_bounding_boxes");}
}
