#include "augmatch/filter/blend.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace augmatch { namespace {
using U=std::uint64_t;
U mix(U x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
float unit(U x){return static_cast<float>((mix(x)>>11)*(1.0/9007199254740992.0));}
void valid(int w,int h,int c){if(w<=0||h<=0||c<=0)throw std::invalid_argument("invalid blend dimensions");}
void ptrs(const void*a,const void*b,const void*o){if(!a||!b||!o)throw std::invalid_argument("null blend buffer");}
float clip(float a){return std::max(0.0f,std::min(1.0f,a));}
std::uint8_t px(float v){return static_cast<std::uint8_t>(std::max(0.0f,std::min(255.0f,std::floor(v+0.5f))));}
void blend(const std::uint8_t* a,const std::uint8_t* b,std::uint8_t* o,int n,float alpha){alpha=clip(alpha);for(int i=0;i<n;++i)o[i]=px((1-alpha)*a[i]+alpha*b[i]);}
void validate(const std::uint8_t* a,const std::uint8_t* b,std::uint8_t* o,int w,int h,int c){valid(w,h,c);ptrs(a,b,o);}
float field(int x,int y,const BlendAlphaSimplexNoiseConfig& c){float f=std::max(0.0001f,c.frequency), value=0, amp=1,total=0;for(int k=0;k<std::max(1,c.octaves);++k){const int gx=static_cast<int>(std::floor(x*f/c.width)),gy=static_cast<int>(std::floor(y*f/c.height));value+=amp*unit(c.seed+static_cast<U>(gx)*0x632be59bd9b4e019ULL+static_cast<U>(gy)*0x8cb92baa5f3a2d17ULL+static_cast<U>(k)*0x9e3779b9ULL);total+=amp;amp*=.5f;f*=2;}return total?value/total:.5f;}
}
void blend_alpha_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);blend(a,b,o,c.width*c.height*c.channels,c.alpha);}
void blend_alpha_mask_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaMaskConfig&c,cudaStream_t s){blend_alpha_mask_u8(a,b,c.mask,o,c,s);}
void blend_alpha_mask_u8(const std::uint8_t*a,const std::uint8_t*b,const std::uint8_t*m,std::uint8_t*o,const BlendAlphaMaskConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);if(!m||!std::isfinite(c.mask_scale)||c.mask_scale<0)throw std::invalid_argument("invalid blend mask");for(int p=0;p<c.width*c.height;++p)blend(a+p*c.channels,b+p*c.channels,o+p*c.channels,c.channels,m[p]*c.mask_scale);}
void blend_alpha_elementwise_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaElementwiseConfig&c,cudaStream_t s){blend_alpha_elementwise_u8(a,b,c.mask,o,c,s);}
void blend_alpha_elementwise_u8(const std::uint8_t*a,const std::uint8_t*b,const std::uint8_t*m,std::uint8_t*o,const BlendAlphaElementwiseConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);if(c.min_alpha>c.max_alpha||!std::isfinite(c.min_alpha)||!std::isfinite(c.max_alpha))throw std::invalid_argument("invalid elementwise blend range");const int n=c.width*c.height;for(int p=0;p<n;++p){float alpha=m?m[p]*c.mask_scale:c.min_alpha+(c.max_alpha-c.min_alpha)*unit(c.seed+static_cast<U>(p));blend(a+p*c.channels,b+p*c.channels,o+p*c.channels,c.channels,alpha);}}
void blend_alpha_simplex_noise_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaSimplexNoiseConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);if(c.min_alpha>c.max_alpha||c.frequency<=0)throw std::invalid_argument("invalid simplex blend configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){const float z=c.min_alpha+(c.max_alpha-c.min_alpha)*field(x,y,c);blend(a+(y*c.width+x)*c.channels,b+(y*c.width+x)*c.channels,o+(y*c.width+x)*c.channels,c.channels,z);}}
void blend_alpha_frequency_noise_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaFrequencyNoiseConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);if(c.min_alpha>c.max_alpha||c.frequency<=0||!std::isfinite(c.amplitude))throw std::invalid_argument("invalid frequency blend configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){const float wave=.5f+.5f*std::sin((x+c.seed%997)*c.frequency*6.2831853f/c.width)*std::cos((y+c.seed%991)*c.frequency*6.2831853f/c.height);const float z=c.min_alpha+(c.max_alpha-c.min_alpha)*clip(.5f+c.amplitude*(wave-.5f));blend(a+(y*c.width+x)*c.channels,b+(y*c.width+x)*c.channels,o+(y*c.width+x)*c.channels,c.channels,z);}}
void blend_alpha_some_colors_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaSomeColorsConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);if(c.color_count<0||c.tolerance<0||(c.color_count&&!c.colors))throw std::invalid_argument("invalid SomeColors records");for(int p=0;p<c.width*c.height;++p){bool hit=false;for(int k=0;k<c.color_count&&!hit;++k){hit=true;for(int ch=0;ch<c.channels;++ch)if(std::abs(int(a[p*c.channels+ch])-int(c.colors[k*c.channels+ch]))>c.tolerance){hit=false;break;}}blend(a+p*c.channels,b+p*c.channels,o+p*c.channels,c.channels,hit?c.alpha:0);}}
void blend_alpha_horizontal_linear_gradient_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaGradientConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){float t=c.width==1?0.f:float(x)/(c.width-1);blend(a+(y*c.width+x)*c.channels,b+(y*c.width+x)*c.channels,o+(y*c.width+x)*c.channels,c.channels,c.alpha_start+t*(c.alpha_end-c.alpha_start));}}
void blend_alpha_vertical_linear_gradient_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaGradientConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){float t=c.height==1?0.f:float(y)/(c.height-1);blend(a+(y*c.width+x)*c.channels,b+(y*c.width+x)*c.channels,o+(y*c.width+x)*c.channels,c.channels,c.alpha_start+t*(c.alpha_end-c.alpha_start));}}
void blend_alpha_regular_grid_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaRegularGridConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);if(c.cell_width<=0||c.cell_height<=0)throw std::invalid_argument("invalid regular grid");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){const bool line=x%c.cell_width==0||y%c.cell_height==0;blend(a+(y*c.width+x)*c.channels,b+(y*c.width+x)*c.channels,o+(y*c.width+x)*c.channels,c.channels,line?c.alpha:0);}}
void blend_alpha_checkerboard_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaCheckerboardConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);if(c.cell_width<=0||c.cell_height<=0)throw std::invalid_argument("invalid checkerboard");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){bool hit=((x/c.cell_width+y/c.cell_height)&1)!=0;if(c.invert)hit=!hit;blend(a+(y*c.width+x)*c.channels,b+(y*c.width+x)*c.channels,o+(y*c.width+x)*c.channels,c.channels,hit?c.alpha:0);}}
void blend_alpha_seg_map_class_ids_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaSegMapClassIdsConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);if(!c.seg_map||c.class_count<0||(c.class_count&&!c.class_ids))throw std::invalid_argument("invalid segmentation metadata");for(int p=0;p<c.width*c.height;++p){bool hit=false;for(int k=0;k<c.class_count;++k)if(c.seg_map[p]==c.class_ids[k]){hit=true;break;}blend(a+p*c.channels,b+p*c.channels,o+p*c.channels,c.channels,hit?c.alpha:0);}}
void blend_alpha_bounding_boxes_u8(const std::uint8_t*a,const std::uint8_t*b,std::uint8_t*o,const BlendAlphaBoundingBoxesConfig&c,cudaStream_t){validate(a,b,o,c.width,c.height,c.channels);if(c.box_count<0||(c.box_count&&!c.boxes))throw std::invalid_argument("invalid bounding-box metadata");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){bool hit=false;for(int k=0;k<c.box_count;++k){const BoxXYXY&r=c.boxes[k];if(!box_is_valid(r)||r.x1<0||r.y1<0||r.x2>c.width||r.y2>c.height)throw std::invalid_argument("bounding box outside image");if(x>=r.x1&&x<r.x2&&y>=r.y1&&y<r.y2)hit=true;}blend(a+(y*c.width+x)*c.channels,b+(y*c.width+x)*c.channels,o+(y*c.width+x)*c.channels,c.channels,hit?c.alpha:0);}}
}
