#include "augmatch/filter/canny.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ int canny_coord(int p,int n,BorderPolicy border){if(p>=0&&p<n)return p;return border==BorderPolicy::Clamp?max(0,min(n-1,p)):-1;}
__device__ float canny_luma(const unsigned char* in,const CannyConfig& c,int x,int y){const int px=canny_coord(x,c.width,c.border),py=canny_coord(y,c.height,c.border);if(px<0||py<0)return (float)c.border_value;const int at=(py*c.width+px)*c.channels;if(c.channels==1)return (float)in[at];return .299f*in[at]+.587f*in[at+1]+.114f*in[at+2];}
__device__ void canny_coeff(int aperture,int i,float& derivative,float& smoothing){if(aperture==3){const float d[3]={-1,0,1},s[3]={1,2,1};derivative=d[i];smoothing=s[i];}else if(aperture==5){const float d[5]={-1,-2,0,2,1},s[5]={1,4,6,4,1};derivative=d[i];smoothing=s[i];}else{const float d[7]={-1,-4,-5,0,5,4,1},s[7]={1,6,15,20,15,6,1};derivative=d[i];smoothing=s[i];}}
__device__ void canny_gradient(const unsigned char* in,const CannyConfig& c,int x,int y,float& gx,float& gy){const int r=c.aperture_size/2;gx=0;gy=0;for(int ky=-r;ky<=r;++ky)for(int kx=-r;kx<=r;++kx){float dx,sx,dy,sy;canny_coeff(c.aperture_size,kx+r,dx,sx);canny_coeff(c.aperture_size,ky+r,dy,sy);const float v=canny_luma(in,c,x+kx,y+ky);gx+=dx*sy*v;gy+=sx*dy*v;}}
__global__ void canny_nms_kernel(const unsigned char* in,unsigned char* state,CannyConfig c){const int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height;if(i>=n)return;const int x=i%c.width,y=i/c.width;float gx,gy;canny_gradient(in,c,x,y,gx,gy);const float ax=fabsf(gx),ay=fabsf(gy),m=ax+ay; if(m<c.low_threshold)return;int dx1=0,dy1=0,dx2=0,dy2=0;const float tangent=.41421356237309505f;if(ay<=ax*tangent){dx1=1;dx2=-1;}else if(ax<=ay*tangent){dy1=1;dy2=-1;}else{dx1=gx*gy>=0?1:-1;dy1=1;dx2=-dx1;dy2=-1;}const int x1=x+dx1,y1=y+dy1,x2=x+dx2,y2=y+dy2;float g1x=0,g1y=0,g2x=0,g2y=0;if(x1>=0&&x1<c.width&&y1>=0&&y1<c.height)canny_gradient(in,c,x1,y1,g1x,g1y);if(x2>=0&&x2<c.width&&y2>=0&&y2<c.height)canny_gradient(in,c,x2,y2,g2x,g2y);const float m1=(x1<0||x1>=c.width||y1<0||y1>=c.height)?0.f:fabsf(g1x)+fabsf(g1y);const float m2=(x2<0||x2>=c.width||y2<0||y2>=c.height)?0.f:fabsf(g2x)+fabsf(g2y);if(m<m1||m<m2)return;state[i]=m>=c.high_threshold?2:1;}
__global__ void canny_hysteresis_kernel(unsigned char* state,unsigned char* out,CannyConfig c){if(blockIdx.x||threadIdx.x)return;const int n=c.width*c.height;bool changed=true;while(changed){changed=false;for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){const int i=y*c.width+x;if(state[i]!=1)continue;bool connected=false;for(int dy=-1;dy<=1;++dy)for(int dx=-1;dx<=1;++dx){const int nx=x+dx,ny=y+dy;if(nx>=0&&nx<c.width&&ny>=0&&ny<c.height&&state[ny*c.width+nx]==2)connected=true;}if(connected){state[i]=2;changed=true;}}}for(int i=0;i<n;++i){const unsigned char value=state[i]==2?255:0;for(int ch=0;ch<c.channels;++ch)out[i*c.channels+ch]=value;}}
void check(cudaError_t e,const char* where){if(e!=cudaSuccess)throw std::runtime_error(std::string(where)+": "+cudaGetErrorString(e));}
void validate_canny_cuda(const std::uint8_t* in,const std::uint8_t* out,const CannyConfig& c){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||!isfinite(c.low_threshold)||!isfinite(c.high_threshold)||c.low_threshold<0||c.high_threshold<c.low_threshold||c.aperture_size<3||c.aperture_size>7||!(c.aperture_size&1)||static_cast<int>(c.border)<0||static_cast<int>(c.border)>1)throw std::invalid_argument("invalid Canny configuration");}
}
void canny_u8(const std::uint8_t* in,std::uint8_t* out,const CannyConfig& c,cudaStream_t stream){validate_canny_cuda(in,out,c);const int pixels=c.width*c.height;unsigned char* state=nullptr;check(cudaMalloc(&state,(std::size_t)pixels),"canny cudaMalloc state");check(cudaMemsetAsync(state,0,(std::size_t)pixels,stream),"canny cudaMemset state");canny_nms_kernel<<<(pixels+255)/256,256,0,stream>>>(in,state,c);check(cudaGetLastError(),"canny_nms_kernel");canny_hysteresis_kernel<<<1,1,0,stream>>>(state,out,c);check(cudaGetLastError(),"canny_hysteresis_kernel");check(cudaFree(state),"canny cudaFree state");}
}
