#include "augmatch/colorspace.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ int bin(float x){return max(0,min(255,(int)floorf(x+0.5f)));}
__device__ int hue_bin(float x){int h=(int)floorf(x+0.5f)%180;return h<0?h+180:h;}
struct HSV { int h,s,v; };
__device__ HSV to_hsv(const unsigned char* p){float r=p[0]/255.f,g=p[1]/255.f,b=p[2]/255.f,mx=fmaxf(r,fmaxf(g,b)),mn=fminf(r,fminf(g,b)),d=mx-mn,h=0.f;if(d>1.e-6f){if(mx==r)h=60.f*fmodf((g-b)/d+6.f,6.f);else if(mx==g)h=60.f*((b-r)/d+2.f);else h=60.f*((r-g)/d+4.f);}return {hue_bin(h/2.f),bin(mx<=1.e-6f?0.f:d/mx*255.f),bin(mx*255.f)};}
__device__ void from_hsv(unsigned char* q,int h,int s,int v){float value=v/255.f,saturation=s/255.f,sector=h*2.f/60.f,part=sector-floorf(sector),pv=value*(1-saturation),qv=value*(1-saturation*part),tv=value*(1-saturation*(1-part)),r,g,b;switch(h/30){case 0:r=value;g=tv;b=pv;break;case 1:r=qv;g=value;b=pv;break;case 2:r=pv;g=value;b=tv;break;case 3:r=pv;g=qv;b=value;break;case 4:r=tv;g=pv;b=value;break;default:r=value;g=pv;b=qv;break;}q[0]=bin(r*255.f);q[1]=bin(g*255.f);q[2]=bin(b*255.f);}
struct Lab { float l,a,b; };
__device__ float pivot_rgb(float x){return x<=.04045f?x/12.92f:powf((x+.055f)/1.055f,2.4f);}
__device__ float pivot_xyz(float x){return x>.0088564517f?cbrtf(x):7.787037f*x+16.f/116.f;}
__device__ float inv_xyz(float x){float x3=x*x*x;return x3>.0088564517f?x3:(x-16.f/116.f)/7.787037f;}
__device__ float inv_rgb(float x){return x<=.0031308f?12.92f*x:1.055f*powf(fmaxf(0.f,x),1.f/2.4f)-.055f;}
__device__ Lab to_lab(const unsigned char* p){float r=pivot_rgb(p[0]/255.f),g=pivot_rgb(p[1]/255.f),b=pivot_rgb(p[2]/255.f);float x=pivot_xyz((.4124564f*r+.3575761f*g+.1804375f*b)/.95047f),y=pivot_xyz((.2126729f*r+.7151522f*g+.072175f*b)),z=pivot_xyz((.0193339f*r+.119192f*g+.9503041f*b)/1.08883f);return {116.f*y-16.f,500.f*(x-y),200.f*(y-z)};}
__device__ void from_lab(unsigned char* q,float l,float a,float b){float y=(l+16.f)/116.f,x=a/500.f+y,z=y-b/200.f,X=.95047f*inv_xyz(x),Y=inv_xyz(y),Z=1.08883f*inv_xyz(z),r=inv_rgb(3.2404542f*X-1.5371385f*Y-.4985314f*Z),g=inv_rgb(-.969266f*X+1.8760108f*Y+.041556f*Z),bb=inv_rgb(.0556434f*X-.2040259f*Y+1.0572252f*Z);q[0]=bin(fminf(1.f,fmaxf(0.f,r))*255.f);q[1]=bin(fminf(1.f,fmaxf(0.f,g))*255.f);q[2]=bin(fminf(1.f,fmaxf(0.f,bb))*255.f);}
__global__ void colorspace_kernel(const unsigned char* in,unsigned char* out,WithColorspaceConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height;if(i>=n)return;const unsigned char* p=in+i*c.channels;unsigned char* q=out+i*c.channels;for(int ch=3;ch<c.channels;++ch)q[ch]=p[ch];if(c.colorspace==ColorSpace::RGB){q[0]=bin(p[0]*c.multiplier0+c.addend0);q[1]=bin(p[1]*c.multiplier1+c.addend1);q[2]=bin(p[2]*c.multiplier2+c.addend2);}else if(c.colorspace==ColorSpace::HSV){HSV x=to_hsv(p);x.h=hue_bin(x.h*c.multiplier0+c.addend0);x.s=bin(x.s*c.multiplier1+c.addend1);x.v=bin(x.v*c.multiplier2+c.addend2);from_hsv(q,x.h,x.s,x.v);}else{Lab x=to_lab(p);const float l=fminf(255.f,fmaxf(0.f,(x.l*2.55f)*c.multiplier0+c.addend0)),a=fminf(255.f,fmaxf(0.f,(x.a+128.f)*c.multiplier1+c.addend1)),b=fminf(255.f,fmaxf(0.f,(x.b+128.f)*c.multiplier2+c.addend2));from_lab(q,l/2.55f,a-128.f,b-128.f);}}
__global__ void brightness_kernel(const unsigned char* in,unsigned char* out,WithBrightnessChannelsConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height;if(i>=n)return;const unsigned char* p=in+i*c.channels;unsigned char* q=out+i*c.channels;for(int ch=0;ch<c.channels;++ch)q[ch]=p[ch];if(c.colorspace==ColorSpace::RGB){if(c.channel0>=0)q[c.channel0]=bin(p[c.channel0]*c.multiplier+c.addend);if(c.channel1>=0)q[c.channel1]=bin(p[c.channel1]*c.multiplier+c.addend);if(c.channel2>=0)q[c.channel2]=bin(p[c.channel2]*c.multiplier+c.addend);}else{if(c.channel0==2||c.channel1==2||c.channel2==2){HSV x=to_hsv(p);x.v=bin(x.v*c.multiplier+c.addend);from_hsv(q,x.h,x.s,x.v);for(int ch=3;ch<c.channels;++ch)q[ch]=p[ch];}}}
void valid(int w,int h,int c){if(w<=0||h<=0||c<3)throw std::invalid_argument("colorspace requires positive RGB dimensions");}
void check_space(ColorSpace s){if(s!=ColorSpace::RGB&&s!=ColorSpace::HSV&&s!=ColorSpace::LAB)throw std::invalid_argument("unsupported colorspace");}
void finite(float x,const char* n){if(!std::isfinite(x))throw std::invalid_argument(std::string(n)+" must be finite");}
void validate(const WithColorspaceConfig& c){valid(c.width,c.height,c.channels);check_space(c.colorspace);const float v[]={c.multiplier0,c.multiplier1,c.multiplier2,c.addend0,c.addend1,c.addend2};for(float x:v)finite(x,"colorspace parameter");if(c.multiplier0<0||c.multiplier1<0||c.multiplier2<0)throw std::invalid_argument("colorspace multipliers must be nonnegative");}
void validate(const WithBrightnessChannelsConfig& c){valid(c.width,c.height,c.channels);if(c.colorspace!=ColorSpace::RGB&&c.colorspace!=ColorSpace::HSV)throw std::invalid_argument("brightness channels supports RGB or HSV");finite(c.multiplier,"brightness multiplier");finite(c.addend,"brightness addend");if(c.multiplier<0)throw std::invalid_argument("brightness multiplier must be nonnegative");const int ids[]={c.channel0,c.channel1,c.channel2};for(int id:ids)if(id!=-1&&(id<0||id>2||(c.colorspace==ColorSpace::HSV&&id!=2)))throw std::invalid_argument("invalid brightness channel");}
void launch(const unsigned char* in,unsigned char* out,int n,int op,WithColorspaceConfig cs,WithBrightnessChannelsConfig bc,cudaStream_t s){if(!in||!out)throw std::invalid_argument("null colorspace buffer");if(op==0)colorspace_kernel<<<(n+255)/256,256,0,s>>>(in,out,cs);else brightness_kernel<<<(n+255)/256,256,0,s>>>(in,out,bc);const auto e=cudaGetLastError();if(e!=cudaSuccess)throw std::runtime_error(std::string("colorspace kernel: ")+cudaGetErrorString(e));}
}
void with_colorspace_u8(const std::uint8_t* in,std::uint8_t* out,const WithColorspaceConfig& c,cudaStream_t s){validate(c);launch(in,out,c.width*c.height,0,c,{},s);}
void with_brightness_channels_u8(const std::uint8_t* in,std::uint8_t* out,const WithBrightnessChannelsConfig& c,cudaStream_t s){validate(c);launch(in,out,c.width*c.height,1,{},c,s);}
}
