#include "augmatch/filter/derivative.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ unsigned char at(const unsigned char* p,int w,int h,int c,int x,int y,int ch,BorderPolicy border,unsigned char fill){if(x<0||x>=w||y<0||y>=h){if(border==BorderPolicy::Constant)return fill;x=max(0,min(w-1,x));y=max(0,min(h-1,y));}return p[(y*w+x)*c+ch];}
__device__ unsigned char dat(const unsigned char* p,LocalStatsConfig c,int x,int y,int ch){return at(p,c.width,c.height,c.channels,x,y,ch,c.border,c.border_value);}
__global__ void kernel(const unsigned char* in,unsigned char* out,DerivativeConfig c,int kind){int q=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(q>=n)return;int ch=q%c.channels,x=(q/c.channels)%c.width,y=q/(c.width*c.channels);const int sx[9]={-1,0,1,-2,0,2,-1,0,1},sy[9]={-1,-2,-1,0,0,0,1,2,1},schx[9]={-3,0,3,-10,0,10,-3,0,3},schy[9]={-3,-10,-3,0,0,0,3,10,3},lap[9]={0,1,0,1,-4,1,0,1,0};const int* a=kind==0?sx:kind==1?sy:kind==2?schx:kind==3?schy:lap;float gx=0,gy=0;for(int j=-1;j<=1;++j)for(int i=-1;i<=1;++i){float v=at(in,c.width,c.height,c.channels,x+i,y+j,ch,c.border,c.border_value);gx+=v*a[(j+1)*3+i+1];if(kind==5)gy+=v*sy[(j+1)*3+i+1];}float v=kind==5?sqrtf(gx*gx+gy*gy):fabsf(gx);out[q]=(unsigned char)fminf(255.f,fmaxf(0.f,rintf(v*c.scale)));}
__global__ void local_kernel(const unsigned char* in,unsigned char* out,LocalStatsConfig c,int entropy){int q=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(q>=n)return;int ch=q%c.channels,x=(q/c.channels)%c.width,y=q/(c.width*c.channels),bins[256]={},count=0;float sum=0,sq=0;for(int j=-c.radius;j<=c.radius;++j)for(int i=-c.radius;i<=c.radius;++i){unsigned char v=dat(in,c,x+i,y+j,ch);sum+=v;sq+=(float)v*v;++bins[v];++count;}float value;if(entropy){value=0;for(int b:bins)if(b){float p=(float)b/count;value-=p*log2f(p);}}else value=fmaxf(0.f,sq/count-(sum/count)*(sum/count));out[q]=(unsigned char)fminf(255.f,fmaxf(0.f,rintf(value*c.scale)));}
void check(cudaError_t e,const char* p){if(e!=cudaSuccess)throw std::runtime_error(std::string(p)+": "+cudaGetErrorString(e));}
}
void run(const std::uint8_t* i,std::uint8_t* o,const DerivativeConfig& c,int k,cudaStream_t s){if(!i||!o||c.width<=0||c.height<=0||c.channels<=0||c.scale<0)throw std::invalid_argument("invalid derivative configuration");int n=c.width*c.height*c.channels;kernel<<<(n+255)/256,256,0,s>>>(i,o,c,k);check(cudaGetLastError(),"derivative_kernel");}
void local_run(const std::uint8_t* i,std::uint8_t* o,const LocalStatsConfig& c,int e,cudaStream_t s){if(!i||!o||c.width<=0||c.height<=0||c.channels<=0||c.radius<1||c.scale<0)throw std::invalid_argument("invalid local statistics configuration");int n=c.width*c.height*c.channels;local_kernel<<<(n+255)/256,256,0,s>>>(i,o,c,e);check(cudaGetLastError(),"local_statistics_kernel");}
void local_variance_u8(const std::uint8_t*i,std::uint8_t*o,const LocalStatsConfig&c,cudaStream_t s){local_run(i,o,c,0,s);} void local_entropy_u8(const std::uint8_t*i,std::uint8_t*o,const LocalStatsConfig&c,cudaStream_t s){local_run(i,o,c,1,s);}
void sobel_x_u8(const std::uint8_t*i,std::uint8_t*o,const DerivativeConfig&c,cudaStream_t s){run(i,o,c,0,s);} void sobel_y_u8(const std::uint8_t*i,std::uint8_t*o,const DerivativeConfig&c,cudaStream_t s){run(i,o,c,1,s);} void scharr_x_u8(const std::uint8_t*i,std::uint8_t*o,const DerivativeConfig&c,cudaStream_t s){run(i,o,c,2,s);} void scharr_y_u8(const std::uint8_t*i,std::uint8_t*o,const DerivativeConfig&c,cudaStream_t s){run(i,o,c,3,s);} void laplacian_u8(const std::uint8_t*i,std::uint8_t*o,const DerivativeConfig&c,cudaStream_t s){run(i,o,c,4,s);} void gradient_magnitude_u8(const std::uint8_t*i,std::uint8_t*o,const DerivativeConfig&c,cudaStream_t s){run(i,o,c,5,s);}
}
