#include "augmatch/filter.hpp"
#include <cuda_runtime.h>
#include <algorithm>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ int reflect101(int i,int n){if(n==1)return 0;while(i<0||i>=n)i=i<0?-i:2*n-i-2;return i;}
__global__ void convolution3x3_kernel(const unsigned char* in,unsigned char* out,int width,int height,int channels,float alpha,float strength,float direction,int mode){const int i=blockIdx.x*blockDim.x+threadIdx.x,n=width*height*channels;if(i>=n)return;float kernel[9]={0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,0.0f,0.0f,0.0f};if(mode==0){kernel[0]=-1.0f-strength;kernel[1]=-strength;kernel[3]=-strength;kernel[5]=strength;kernel[7]=strength;kernel[8]=1.0f+strength;}else if(mode==1){kernel[1]=1.0f;kernel[3]=1.0f;kernel[4]=-4.0f;kernel[5]=1.0f;kernel[7]=1.0f;}else{const int degrees=(int)(direction*360.0f)%360;const double radians=(double)degrees*3.14159265358979323846/180.0;const double dx_direction=cos(radians-0.5*3.14159265358979323846),dy_direction=sin(radians-0.5*3.14159265358979323846);float norm=0.0f;for(int y=-1;y<=1;++y)for(int x=-1;x<=1;++x)if(x||y){const double dot=((double)x*dx_direction+(double)y*dy_direction)/sqrt((double)(x*x+y*y));const double angle=acos(fmin(1.0,fmax(-1.0,dot)));const float similarity=(float)pow(1.0-angle/3.14159265358979323846,4.0);kernel[(y+1)*3+x+1]=-similarity;norm+=similarity;}for(int k=0;k<9;++k)if(k!=4)kernel[k]/=norm;}for(int k=0;k<9;++k)kernel[k]*=alpha;kernel[4]+=1.0f-alpha;const int ch=i%channels,x=(i/ch)%width,y=i/(width*channels);float value=0.0f;for(int dy=-1;dy<=1;++dy)for(int dx=-1;dx<=1;++dx){const int px=reflect101(x+dx,width),py=reflect101(y+dy,height);value+=kernel[(dy+1)*3+dx+1]*(float)in[(py*width+px)*channels+ch];}out[i]=(unsigned char)fminf(255.0f,fmaxf(0.0f,floorf(value+0.5f)));}
__global__ void blur_kernel(const unsigned char* in,unsigned char* out,BlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.kernel_size/2;if(c.mode==BlurMode::Median){unsigned char values[225];int count=0;for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){int px=max(0,min(c.width-1,x+dx)),py=max(0,min(c.height-1,y+dy));values[count++]=in[(py*c.width+px)*c.channels+ch];}for(int a=0;a<count;++a){int best=a;for(int b=a+1;b<count;++b)if(values[b]<values[best])best=b;unsigned char t=values[a];values[a]=values[best];values[best]=t;}out[i]=values[count/2];return;}float sum=0,wtotal=0,inv=1.f/(2.f*c.sigma*c.sigma);for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){int px=reflect101(x+dx,c.width),py=reflect101(y+dy,c.height);float w=c.mode==BlurMode::Average?1.f:expf(-(dx*dx+dy*dy)*inv);sum+=w*in[(py*c.width+px)*c.channels+ch];wtotal+=w;}out[i]=(unsigned char)fminf(255.f,fmaxf(0.f,rintf(sum/wtotal)));}
__global__ void bilateral_blur_kernel(const unsigned char* in,unsigned char* out,BilateralBlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;const int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),radius=c.radius;const float spatial_inv=1.f/(2.f*c.sigma_space*c.sigma_space),color_inv=1.f/(2.f*c.sigma_color*c.sigma_color);float sum=0.f,weight_sum=0.f;for(int dy=-radius;dy<=radius;++dy)for(int dx=-radius;dx<=radius;++dx){const int px=reflect101(x+dx,c.width),py=reflect101(y+dy,c.height),sample=(py*c.width+px)*c.channels;float color_distance=0.f;for(int other=0;other<c.channels;++other){const float difference=(float)in[sample+other]-(float)in[(y*c.width+x)*c.channels+other];color_distance+=difference*difference;}const float weight=expf(-((float)(dx*dx+dy*dy)*spatial_inv+color_distance*color_inv));weight_sum+=weight;sum+=weight*in[sample+ch];}const float value=fminf(255.f,fmaxf(0.f,sum/weight_sum));out[i]=static_cast<unsigned char>(floorf(value+.5f));}
__global__ void mean_shift_blur_init(const unsigned char* source,float* state,int n){const int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)state[i]=static_cast<float>(source[i]);}
__global__ void mean_shift_blur_kernel(const unsigned char* source,const float* current,float* out,MeanShiftBlurConfig c){
  const int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;
  const int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),radius=c.spatial_radius;
  const int center=(y*c.width+x)*c.channels; const float color_limit=c.color_radius*c.color_radius;
  float sum=0.f;int count=0;
  for(int dy=-radius;dy<=radius;++dy)for(int dx=-radius;dx<=radius;++dx){
    const int px=reflect101(x+dx,c.width),py=reflect101(y+dy,c.height),sample=(py*c.width+px)*c.channels;float distance=0.f;
    for(int other=0;other<c.channels;++other){const float difference=static_cast<float>(source[sample+other])-static_cast<float>(current[center+other]);distance+=difference*difference;}
    if(distance<=color_limit){++count;sum+=static_cast<float>(source[sample+ch]);}
  }
  const float value=count?sum/static_cast<float>(count):static_cast<float>(current[center+ch]);
  out[i]=value;
}
__global__ void mean_shift_blur_finalize(const float* state,unsigned char* out,int n){const int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)out[i]=static_cast<unsigned char>(floorf(fminf(255.f,fmaxf(0.f,state[i]))+.5f));}
__global__ void advanced_blur_kernel(const unsigned char* in,unsigned char* out,AdvancedBlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.kernel_size/2;float angle=c.angle_degrees*3.14159265358979323846f/180.f,co=cosf(angle),si=sinf(angle),norm=0.f;float kernel[225];for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){float xp=co*dx+si*dy,yp=-si*dx+co*dy,qx=xp/c.sigma_x,qy=yp/c.sigma_y,w=expf(-.5f*(qx*qx+qy*qy));kernel[(dy+r)*c.kernel_size+dx+r]=w;norm+=w;}float sum=0.f;for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){int px=reflect101(x+dx,c.width),py=reflect101(y+dy,c.height);sum+=(kernel[(dy+r)*c.kernel_size+dx+r]/norm)*in[(py*c.width+px)*c.channels+ch];}out[i]=(unsigned char)fminf(255.f,fmaxf(0.f,rintf(sum)));}
__global__ void unsharp_kernel(const unsigned char* in,unsigned char* out,UnsharpConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.kernel_size/2;float sum=0,wtotal=0,inv=1.f/(2.f*c.sigma*c.sigma);for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){int px=reflect101(x+dx,c.width),py=reflect101(y+dy,c.height);float w=expf(-(dx*dx+dy*dy)*inv);sum+=w*in[(py*c.width+px)*c.channels+ch];wtotal+=w;}float orig=in[i],detail=orig-sum/wtotal,v=fabsf(detail)>=c.threshold?orig+c.amount*detail:orig;out[i]=(unsigned char)fminf(255.f,fmaxf(0.f,rintf(v)));}
__global__ void defocus_kernel(const unsigned char* in,unsigned char* out,DefocusConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.radius,R=max(8,r),g=R<=8?1:2;float sigma=c.alias_blur>0?c.alias_blur:0,sum=0,norm=0;for(int dy=-R;dy<=R;++dy)for(int dx=-R;dx<=R;++dx){float w=0;for(int gy=-g;gy<=g;++gy)for(int gx=-g;gx<=g;++gx)if((dx-gx)*(dx-gx)+(dy-gy)*(dy-gy)<=r*r){float wx=sigma==0?(gx==0?.5f:.25f):expf(-gx*gx/(2*sigma*sigma)),wy=sigma==0?(gy==0?.5f:.25f):expf(-gy*gy/(2*sigma*sigma));w+=wx*wy;}sum+=w*in[(reflect101(y+dy,c.height)*c.width+reflect101(x+dx,c.width))*c.channels+ch];norm+=w;}out[i]=(unsigned char)rintf(sum/norm);}
__global__ void sharpen_kernel(const unsigned char* in,unsigned char* out,SharpenConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.kernel_size/2;float sum=0,wtotal=0,inv=1.f/(2.f*c.sigma*c.sigma);for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){int px=reflect101(x+dx,c.width),py=reflect101(y+dy,c.height);float w=expf(-(dx*dx+dy*dy)*inv);sum+=w*in[(py*c.width+px)*c.channels+ch];wtotal+=w;}int orig=in[i],blur=(int)rintf(sum/wtotal);float wrapped=(unsigned char)(orig-blur),v=orig+c.alpha*c.lightness*wrapped;out[i]=(unsigned char)fminf(255.f,fmaxf(0.f,rintf(v)));}
__global__ void ringing_overshoot_kernel(const unsigned char* in,unsigned char* out,RingingOvershootConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.kernel_size/2;float inv=1.f/(2.f*c.sigma*c.sigma),blurred=0.f,norm=0.f;for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx)norm+=expf(-(dx*dx+dy*dy)*inv);for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){float weight=expf(-(dx*dx+dy*dy)*inv);blurred+=(weight/norm)*in[(reflect101(y+dy,c.height)*c.width+reflect101(x+dx,c.width))*c.channels+ch];}float original=in[i],value=original+c.amount*(original-blurred),clipped=fminf(255.f,fmaxf(0.f,value));out[i]=(unsigned char)floorf(clipped+0.5f);}
__global__ void motion_kernel(const unsigned char* in,unsigned char* out,MotionBlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.kernel_size/2;float a=c.angle_degrees*3.14159265358979323846f/180.f,co=cosf(a),si=sinf(a),sum=0,weight=0;for(int t=-r;t<=r;++t){int px=(int)rintf(x+t*co),py=(int)rintf(y+t*si);float w=1.f+c.direction*(r?(float)t/r:0.f);sum+=w*in[(reflect101(py,c.height)*c.width+reflect101(px,c.width))*c.channels+ch];weight+=w;}out[i]=(unsigned char)fminf(255.f,fmaxf(0.f,rintf(sum/weight)));}
__device__ unsigned char optical_u8(float value){return (unsigned char)fminf(255.f,fmaxf(0.f,rintf(value)));}
__global__ void depth_defocus_kernel(const unsigned char* in,unsigned char* out,DepthDependentDefocusConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);int r=(int)rintf(fabsf(c.depth[y*c.width+x]-c.focus_depth)*c.blur_scale);r=max(0,min(c.max_radius,r));float sum=0;int count=0;for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx)if(dx*dx+dy*dy<=r*r){sum+=in[(reflect101(y+dy,c.height)*c.width+reflect101(x+dx,c.width))*c.channels+ch];++count;}out[i]=optical_u8(count?sum/count:(float)in[i]);}
__global__ void camera_shake_kernel(const unsigned char* in,unsigned char* out,CameraShakeBlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float sum=0;for(int s=0;s<c.sample_count;++s){int px=(int)rintf(x+c.offsets_x[s]),py=(int)rintf(y+c.offsets_y[s]);sum+=in[(reflect101(py,c.height)*c.width+reflect101(px,c.width))*c.channels+ch];}out[i]=optical_u8(sum/c.sample_count);}
__global__ void linear_directional_kernel(const unsigned char* in,unsigned char* out,LinearDirectionalBlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float a=c.angle_degrees*3.14159265358979323846f/180.f,co=cosf(a),si=sinf(a),sum=0;for(int s=0;s<c.sample_count;++s){float t=c.sample_count==1?0.f:(float)s/(c.sample_count-1)-.5f;int px=(int)rintf(x+t*c.length*co),py=(int)rintf(y+t*c.length*si);sum+=in[(reflect101(py,c.height)*c.width+reflect101(px,c.width))*c.channels+ch];}out[i]=optical_u8(sum/c.sample_count);}
__global__ void rotational_motion_kernel(const unsigned char* in,unsigned char* out,RotationalMotionBlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float a=c.angle_degrees*3.14159265358979323846f/180.f,rx=x-c.center_x,ry=y-c.center_y,sum=0;for(int s=0;s<c.sample_count;++s){float q=c.sample_count==1?0.f:(float)s/(c.sample_count-1)-.5f,co=cosf(q*a),si=sinf(q*a);int px=(int)rintf(c.center_x+co*rx-si*ry),py=(int)rintf(c.center_y+si*rx+co*ry);sum+=in[(reflect101(py,c.height)*c.width+reflect101(px,c.width))*c.channels+ch];}out[i]=optical_u8(sum/c.sample_count);}
__global__ void rolling_shutter_motion_kernel(const unsigned char* in,unsigned char* out,RollingShutterMotionBlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float sum=0;for(int s=0;s<c.sample_count;++s){float q=c.sample_count==1?0.f:(float)s/(c.sample_count-1)-.5f;int px=(int)rintf(x+q*c.row_offsets_x[y]),py=(int)rintf(y+q*c.row_offsets_y[y]);sum+=in[(reflect101(py,c.height)*c.width+reflect101(px,c.width))*c.channels+ch];}out[i]=optical_u8(sum/c.sample_count);}
__device__ float diffraction_weight(float distance,int radius,float scale){if(distance>(float)radius)return 0.f;if(distance==0.f)return 1.f;float q=distance/((float)radius*scale),s=sinf(3.14159265358979323846f*q)/(3.14159265358979323846f*q);return s*s;}
__device__ float disk_weight(float distance,int radius,float softness){if(distance>(float)radius)return 0.f;if(softness<=0.f)return 1.f;float q=distance/(float)radius,start=1.f-softness;return q<=start?1.f:fmaxf(0.f,(1.f-q)/softness);}
__device__ float aperture_weight(float dx,float dy,ApertureShapeBlurConfig c){float distance=sqrtf(dx*dx+dy*dy);if(distance>(float)c.radius)return 0.f;if(distance==0.f)return 1.f;const float pi=3.14159265358979323846f,sector=2.f*pi/(float)c.blades;float angle=atan2f(dy,dx)-c.rotation_degrees*pi/180.f;angle=fmodf(angle+pi,sector);if(angle<0.f)angle+=sector;angle-=sector*.5f;float polygon=(float)c.radius*cosf(pi/(float)c.blades)/cosf(angle),boundary=(1.f-c.roundness)*polygon+c.roundness*(float)c.radius;return distance<=boundary?1.f:0.f;}
__global__ void diffraction_blur_kernel(const unsigned char* in,unsigned char* out,DiffractionBlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.radius;if(!r){out[i]=in[i];return;}float sum=0.f,norm=0.f;for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){float scale=fminf(4.f,fmaxf(.25f,(c.wavelength_nm/550.f)*(c.focal_length_mm/50.f)*(2.f/c.aperture_diameter_mm)));float w=diffraction_weight(sqrtf((float)(dx*dx+dy*dy)),r,scale);if(w<=0.f)continue;sum+=w*in[(reflect101(y+dy,c.height)*c.width+reflect101(x+dx,c.width))*c.channels+ch];norm+=w;}out[i]=optical_u8(norm>0.f?sum/norm:(float)in[i]);}
__global__ void bokeh_blur_kernel(const unsigned char* in,unsigned char* out,BokehBlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.radius;if(!r){out[i]=in[i];return;}float sum=0.f,norm=0.f;for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){float w=disk_weight(sqrtf((float)(dx*dx+dy*dy)),r,c.edge_softness);if(w<=0.f)continue;sum+=w*in[(reflect101(y+dy,c.height)*c.width+reflect101(x+dx,c.width))*c.channels+ch];norm+=w;}out[i]=optical_u8(norm>0.f?sum/norm:(float)in[i]);}
__global__ void cat_eye_bokeh_kernel(const unsigned char* in,unsigned char* out,CatEyeBokehConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.radius;if(!r){out[i]=in[i];return;}float nx=c.width>1?(x/(float)(c.width-1)-c.center_x):0.f,ny=c.height>1?(y/(float)(c.height-1)-c.center_y):0.f,edge=fminf(1.f,sqrtf(nx*nx+ny*ny)*2.f),scale=fmaxf(.25f,1.f-c.cat_eye_strength*edge),sum=0.f,norm=0.f;for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){float q=dx*dx/((float)(r*r)*scale*scale)+dy*dy/(float)(r*r);if(q>1.f)continue;sum+=in[(reflect101(y+dy,c.height)*c.width+reflect101(x+dx,c.width))*c.channels+ch];norm+=1.f;}out[i]=optical_u8(norm>0.f?sum/norm:(float)in[i]);}
__global__ void aperture_shape_blur_kernel(const unsigned char* in,unsigned char* out,ApertureShapeBlurConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),r=c.radius;if(!r){out[i]=in[i];return;}float sum=0.f,norm=0.f;for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){float w=aperture_weight((float)dx,(float)dy,c);if(w<=0.f)continue;sum+=w*in[(reflect101(y+dy,c.height)*c.width+reflect101(x+dx,c.width))*c.channels+ch];norm+=w;}out[i]=optical_u8(norm>0.f?sum/norm:(float)in[i]);}
__device__ float zoom_blur_sample(const unsigned char* image,int width,int height,int channels,float x,float y,int channel){const int x0=(int)floorf(x),y0=(int)floorf(y);const float fx=x-x0,fy=y-y0;const int xa=reflect101(x0,width),xb=reflect101(x0+1,width),ya=reflect101(y0,height),yb=reflect101(y0+1,height);const float a=image[(ya*width+xa)*channels+channel],b=image[(ya*width+xb)*channels+channel],cc=image[(yb*width+xa)*channels+channel],d=image[(yb*width+xb)*channels+channel];const float top=a+(b-a)*fx;return top+(cc+(d-cc)*fx-top)*fy;}
__global__ void zoom_blur_kernel(const unsigned char* in,unsigned char* out,ZoomBlurConfig c){const int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;const int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),count=c.steps+1;const float cx=.5f*(c.width-1),cy=.5f*(c.height-1);float sum=0.f;for(int step=0;step<count;++step){const float t=c.steps?(float)step/c.steps:0.f,factor=c.min_factor+(c.max_factor-c.min_factor)*t,sx=cx+(x-cx)/factor,sy=cy+(y-cy)/factor;sum+=zoom_blur_sample(in,c.width,c.height,c.channels,sx,sy,ch);}out[i]=(unsigned char)fminf(255.f,fmaxf(0.f,floorf(sum/count+.5f)));}
void check(cudaError_t e,const char* p){if(e!=cudaSuccess)throw std::runtime_error(std::string(p)+": "+cudaGetErrorString(e));}
}
namespace {
__device__ unsigned long long glass_blur_splitmix64(unsigned long long value){value+=0x9e3779b97f4a7c15ULL;value=(value^(value>>30))*0xbf58476d1ce4e5b9ULL;value=(value^(value>>27))*0x94d049bb133111ebULL;return value^(value>>31);}
__global__ void glass_blur_gaussian_kernel(const unsigned char* in,unsigned char* out,GlassBlurConfig c,int radius){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float inv=1.f/(2.f*c.sigma*c.sigma),sum=0.f,norm=0.f;for(int dy=-radius;dy<=radius;++dy)for(int dx=-radius;dx<=radius;++dx){float weight=expf(-(dx*dx+dy*dy)*inv);sum+=weight*in[(reflect101(y+dy,c.height)*c.width+reflect101(x+dx,c.width))*c.channels+ch];norm+=weight;}out[i]=(unsigned char)fminf(255.f,fmaxf(0.f,rintf(sum/norm)));}
__global__ void glass_blur_swap_kernel(unsigned char* image,GlassBlurConfig c,const GlassBlurSwap* swaps){if(blockIdx.x!=0||threadIdx.x!=0)return;const int width=c.width-2*c.max_delta,height=c.height-2*c.max_delta;const unsigned long long count=(unsigned long long)c.iterations*width*height;for(unsigned long long k=0;k<count;++k){const int position=(int)(k%(unsigned long long)(width*height)),x=c.max_delta+position%width,y=c.max_delta+position/width;GlassBlurSwap swap;if(swaps)swap=swaps[k];else{const unsigned long long span=(unsigned long long)(2*c.max_delta+1);swap.dx=(signed char)((int)(glass_blur_splitmix64(c.seed+2*k)%span)-c.max_delta);swap.dy=(signed char)((int)(glass_blur_splitmix64(c.seed+2*k+1)%span)-c.max_delta);}const int sx=x+swap.dx,sy=y+swap.dy;for(int ch=0;ch<c.channels;++ch){unsigned char* a=image+((y*c.width+x)*c.channels+ch);unsigned char* b=image+((sy*c.width+sx)*c.channels+ch);unsigned char value=*a;*a=*b;*b=value;}}}
int glass_blur_radius_cuda(float sigma){int radius=(int)ceilf(3.f*sigma);if(radius<1||radius>15)throw std::invalid_argument("glass blur sigma produces an unsupported kernel");return radius;}
void validate_glass_blur_cuda(const std::uint8_t* in,const std::uint8_t* out,const GlassBlurConfig& c){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||!isfinite(c.sigma)||c.sigma<=0.f||c.max_delta<0||c.max_delta>127||c.iterations<0||c.max_delta>c.width/2||c.max_delta>c.height/2)throw std::invalid_argument("invalid glass blur configuration");glass_blur_radius_cuda(c.sigma);}
}
void blur_u8(const std::uint8_t* in,std::uint8_t* out,const BlurConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.kernel_size<=0||!(c.kernel_size&1)||c.kernel_size>17||(c.mode==BlurMode::Median&&c.kernel_size>15)||c.sigma<=0||static_cast<int>(c.mode)<0||static_cast<int>(c.mode)>2)throw std::invalid_argument("invalid blur configuration");int n=c.width*c.height*c.channels;blur_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"blur_kernel");}
void emboss_u8(const std::uint8_t* in,std::uint8_t* out,const EmbossConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||!isfinite(c.alpha)||c.alpha<0.f||c.alpha>1.f||!isfinite(c.strength)||c.strength<0.f)throw std::invalid_argument("invalid emboss configuration");const int n=c.width*c.height*c.channels;convolution3x3_kernel<<<(n+255)/256,256,0,s>>>(in,out,c.width,c.height,c.channels,c.alpha,c.strength,0.f,0);check(cudaGetLastError(),"emboss_kernel");}
void edge_detect_u8(const std::uint8_t* in,std::uint8_t* out,const EdgeDetectConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||!isfinite(c.alpha)||c.alpha<0.f||c.alpha>1.f)throw std::invalid_argument("invalid edge-detect configuration");const int n=c.width*c.height*c.channels;convolution3x3_kernel<<<(n+255)/256,256,0,s>>>(in,out,c.width,c.height,c.channels,c.alpha,0.f,0.f,1);check(cudaGetLastError(),"edge_detect_kernel");}
void directed_edge_detect_u8(const std::uint8_t* in,std::uint8_t* out,const DirectedEdgeDetectConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||!isfinite(c.alpha)||c.alpha<0.f||c.alpha>1.f||!isfinite(c.direction))throw std::invalid_argument("invalid directed edge-detect configuration");const int n=c.width*c.height*c.channels;convolution3x3_kernel<<<(n+255)/256,256,0,s>>>(in,out,c.width,c.height,c.channels,c.alpha,0.f,c.direction,2);check(cudaGetLastError(),"directed_edge_detect_kernel");}
void bilateral_blur_u8(const std::uint8_t* in,std::uint8_t* out,const BilateralBlurConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.radius<1||c.radius>15||!isfinite(c.sigma_space)||c.sigma_space<=0.f||!isfinite(c.sigma_color)||c.sigma_color<=0.f)throw std::invalid_argument("invalid bilateral blur configuration");const int n=c.width*c.height*c.channels;bilateral_blur_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"bilateral_blur_kernel");}
void mean_shift_blur_u8(const std::uint8_t* in,std::uint8_t* out,const MeanShiftBlurConfig& c,cudaStream_t s){
  if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.spatial_radius<1||c.spatial_radius>15||c.iterations<1||c.iterations>16||!isfinite(c.color_radius)||c.color_radius<=0.f)throw std::invalid_argument("invalid mean-shift blur configuration");
  const int n=c.width*c.height*c.channels;const std::size_t bytes=static_cast<std::size_t>(n),state_bytes=bytes*sizeof(float);std::uint8_t *source=nullptr;float *current=nullptr,*next=nullptr;
  check(cudaMalloc(&source,bytes),"mean_shift_blur cudaMalloc source");check(cudaMalloc(&current,state_bytes),"mean_shift_blur cudaMalloc current");check(cudaMalloc(&next,state_bytes),"mean_shift_blur cudaMalloc next");
  check(cudaMemcpyAsync(source,in,bytes,cudaMemcpyDeviceToDevice,s),"mean_shift_blur source copy");mean_shift_blur_init<<<(n+255)/256,256,0,s>>>(source,current,n);check(cudaGetLastError(),"mean_shift_blur_init");
  for(int iteration=0;iteration<c.iterations;++iteration){mean_shift_blur_kernel<<<(n+255)/256,256,0,s>>>(source,current,next,c);check(cudaGetLastError(),"mean_shift_blur_kernel");std::swap(current,next);}
  mean_shift_blur_finalize<<<(n+255)/256,256,0,s>>>(current,out,n);check(cudaGetLastError(),"mean_shift_blur_finalize");check(cudaFree(source),"mean_shift_blur cudaFree source");check(cudaFree(current),"mean_shift_blur cudaFree current");check(cudaFree(next),"mean_shift_blur cudaFree next");
}
void advanced_blur_u8(const std::uint8_t* in,std::uint8_t* out,const AdvancedBlurConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.kernel_size<=0||!(c.kernel_size&1)||c.kernel_size>15||!isfinite(c.sigma_x)||!isfinite(c.sigma_y)||c.sigma_x<=0||c.sigma_y<=0||!isfinite(c.angle_degrees))throw std::invalid_argument("invalid advanced blur configuration");int n=c.width*c.height*c.channels;advanced_blur_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"advanced_blur_kernel");}
void unsharp_mask_u8(const std::uint8_t* in,std::uint8_t* out,const UnsharpConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.kernel_size<=0||!(c.kernel_size&1)||c.sigma<=0||c.amount<0||c.threshold<0)throw std::invalid_argument("invalid unsharp configuration");int n=c.width*c.height*c.channels;unsharp_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"unsharp_kernel");}
void sharpen_u8(const std::uint8_t* in,std::uint8_t* out,const SharpenConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.kernel_size<=0||!(c.kernel_size&1)||c.sigma<=0||c.alpha<0||c.lightness<0)throw std::invalid_argument("invalid sharpen configuration");int n=c.width*c.height*c.channels;sharpen_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"sharpen_kernel");}
void ringing_overshoot_u8(const std::uint8_t* in,std::uint8_t* out,const RingingOvershootConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.kernel_size<=0||!(c.kernel_size&1)||c.kernel_size>15||!isfinite(c.sigma)||c.sigma<=0.f||!isfinite(c.amount)||c.amount<0.f||c.amount>4.f)throw std::invalid_argument("invalid ringing overshoot configuration");int n=c.width*c.height*c.channels;ringing_overshoot_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"ringing_overshoot_kernel");}
void motion_blur_u8(const std::uint8_t* in,std::uint8_t* out,const MotionBlurConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.kernel_size<=0||!(c.kernel_size&1)||c.direction<-1||c.direction>1)throw std::invalid_argument("invalid motion blur configuration");int n=c.width*c.height*c.channels;motion_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"motion_kernel");}
void optical_motion_blur_u8(const std::uint8_t* in,std::uint8_t* out,const OpticalMotionBlurConfig& c,cudaStream_t s){if(!isfinite(c.angle_degrees)||!isfinite(c.direction))throw std::invalid_argument("invalid optical motion blur configuration");motion_blur_u8(in,out,{c.width,c.height,c.channels,c.kernel_size,c.angle_degrees,c.direction,true},s);}
void depth_dependent_defocus_u8(const std::uint8_t* in,std::uint8_t* out,const DepthDependentDefocusConfig& c,cudaStream_t s){if(!in||!out||!c.depth||c.width<=0||c.height<=0||c.channels<=0||!isfinite(c.focus_depth)||!isfinite(c.blur_scale)||c.blur_scale<0||c.max_radius<0||c.max_radius>64)throw std::invalid_argument("invalid depth-dependent defocus configuration");int n=c.width*c.height*c.channels;depth_defocus_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"depth_defocus_kernel");}
void camera_shake_blur_u8(const std::uint8_t* in,std::uint8_t* out,const CameraShakeBlurConfig& c,cudaStream_t s){if(!in||!out||!c.offsets_x||!c.offsets_y||c.width<=0||c.height<=0||c.channels<=0||c.sample_count<1)throw std::invalid_argument("invalid camera-shake blur configuration");int n=c.width*c.height*c.channels;camera_shake_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"camera_shake_kernel");}
void linear_directional_blur_u8(const std::uint8_t* in,std::uint8_t* out,const LinearDirectionalBlurConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.sample_count<1||!isfinite(c.length)||c.length<0||!isfinite(c.angle_degrees))throw std::invalid_argument("invalid linear directional blur configuration");int n=c.width*c.height*c.channels;linear_directional_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"linear_directional_kernel");}
void rotational_motion_blur_u8(const std::uint8_t* in,std::uint8_t* out,const RotationalMotionBlurConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.sample_count<1||!isfinite(c.center_x)||!isfinite(c.center_y)||!isfinite(c.angle_degrees))throw std::invalid_argument("invalid rotational motion blur configuration");int n=c.width*c.height*c.channels;rotational_motion_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"rotational_motion_kernel");}
void rolling_shutter_motion_blur_u8(const std::uint8_t* in,std::uint8_t* out,const RollingShutterMotionBlurConfig& c,cudaStream_t s){if(!in||!out||!c.row_offsets_x||!c.row_offsets_y||c.width<=0||c.height<=0||c.channels<=0||c.sample_count<1)throw std::invalid_argument("invalid rolling-shutter motion blur configuration");int n=c.width*c.height*c.channels;rolling_shutter_motion_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"rolling_shutter_motion_kernel");}
void diffraction_blur_u8(const std::uint8_t* in,std::uint8_t* out,const DiffractionBlurConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.radius<0||c.radius>32||!isfinite(c.wavelength_nm)||c.wavelength_nm<=0.f||!isfinite(c.aperture_diameter_mm)||c.aperture_diameter_mm<=0.f||!isfinite(c.focal_length_mm)||c.focal_length_mm<=0.f)throw std::invalid_argument("invalid diffraction blur configuration");int n=c.width*c.height*c.channels;diffraction_blur_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"diffraction_blur_kernel");}
void bokeh_blur_u8(const std::uint8_t* in,std::uint8_t* out,const BokehBlurConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.radius<0||c.radius>32||!isfinite(c.edge_softness)||c.edge_softness<0.f||c.edge_softness>1.f)throw std::invalid_argument("invalid bokeh blur configuration");int n=c.width*c.height*c.channels;bokeh_blur_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"bokeh_blur_kernel");}
void cat_eye_bokeh_u8(const std::uint8_t* in,std::uint8_t* out,const CatEyeBokehConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.radius<0||c.radius>32||!isfinite(c.cat_eye_strength)||c.cat_eye_strength<0.f||c.cat_eye_strength>1.f||!isfinite(c.center_x)||!isfinite(c.center_y))throw std::invalid_argument("invalid cat-eye bokeh configuration");int n=c.width*c.height*c.channels;cat_eye_bokeh_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"cat_eye_bokeh_kernel");}
void aperture_shape_blur_u8(const std::uint8_t* in,std::uint8_t* out,const ApertureShapeBlurConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.radius<0||c.radius>32||c.blades<3||c.blades>32||!isfinite(c.rotation_degrees)||!isfinite(c.roundness)||c.roundness<0.f||c.roundness>1.f)throw std::invalid_argument("invalid aperture shape blur configuration");int n=c.width*c.height*c.channels;aperture_shape_blur_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"aperture_shape_blur_kernel");}
void defocus_u8(const std::uint8_t* in,std::uint8_t* out,const DefocusConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.radius<1||c.radius>32)throw std::invalid_argument("invalid defocus configuration");int n=c.width*c.height*c.channels;defocus_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"defocus_kernel");}
void optical_defocus_u8(const std::uint8_t* in,std::uint8_t* out,const OpticalDefocusConfig& c,cudaStream_t s){if(!isfinite(c.alias_blur)||c.alias_blur<0.0f)throw std::invalid_argument("invalid optical defocus configuration");if(c.radius==0){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0)throw std::invalid_argument("invalid optical defocus configuration");check(cudaMemcpyAsync(out,in,static_cast<std::size_t>(c.width)*c.height*c.channels,cudaMemcpyDeviceToDevice,s),"optical_defocus copy");return;}defocus_u8(in,out,{c.width,c.height,c.channels,c.radius,c.alias_blur},s);}
int zoom_blur_factor_count(const ZoomBlurConfig& c){if(c.steps<0||c.steps>256)throw std::invalid_argument("invalid zoom blur step count");return c.steps+1;}
void zoom_blur_u8(const std::uint8_t* in,std::uint8_t* out,const ZoomBlurConfig& c,cudaStream_t s){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||!isfinite(c.min_factor)||!isfinite(c.max_factor)||c.min_factor<1.f||c.max_factor<c.min_factor||c.steps<0||c.steps>256)throw std::invalid_argument("invalid zoom blur configuration");const int n=c.width*c.height*c.channels;zoom_blur_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"zoom_blur_kernel");}
void optical_zoom_blur_u8(const std::uint8_t* in,std::uint8_t* out,const OpticalZoomBlurConfig& c,cudaStream_t s){zoom_blur_u8(in,out,{c.width,c.height,c.channels,c.min_factor,c.max_factor,c.steps},s);}
std::size_t glass_blur_swap_count(int width,int height,int max_delta,int iterations){if(width<=0||height<=0||max_delta<0||max_delta>127||iterations<0||max_delta>width/2||max_delta>height/2)throw std::invalid_argument("invalid glass blur swap dimensions");return static_cast<std::size_t>(iterations)*static_cast<std::size_t>(height-2*max_delta)*static_cast<std::size_t>(width-2*max_delta);}
void make_glass_blur_swap_sequence(GlassBlurSwap* sequence,int width,int height,int max_delta,int iterations,std::uint64_t seed){const std::size_t count=glass_blur_swap_count(width,height,max_delta,iterations);if(!sequence&&count)throw std::invalid_argument("null glass blur swap sequence");const std::uint64_t span=static_cast<std::uint64_t>(2*max_delta+1);for(std::size_t i=0;i<count;++i){std::uint64_t x=seed+static_cast<std::uint64_t>(2*i);x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;x^=x>>31;std::uint64_t y=seed+static_cast<std::uint64_t>(2*i+1);y+=0x9e3779b97f4a7c15ULL;y=(y^(y>>30))*0xbf58476d1ce4e5b9ULL;y=(y^(y>>27))*0x94d049bb133111ebULL;y^=y>>31;sequence[i].dx=static_cast<std::int8_t>(static_cast<int>(x%span)-max_delta);sequence[i].dy=static_cast<std::int8_t>(static_cast<int>(y%span)-max_delta);}}
void glass_blur_u8(const std::uint8_t* in,std::uint8_t* out,const GlassBlurConfig& c,cudaStream_t s){validate_glass_blur_cuda(in,out,c);const int n=c.width*c.height*c.channels,radius=glass_blur_radius_cuda(c.sigma);std::uint8_t* work=nullptr;check(cudaMalloc(&work,static_cast<std::size_t>(n)),"glass_blur cudaMalloc");glass_blur_gaussian_kernel<<<(n+255)/256,256,0,s>>>(in,work,c,radius);check(cudaGetLastError(),"glass_blur initial gaussian");glass_blur_swap_kernel<<<1,1,0,s>>>(work,c,c.swap_sequence);check(cudaGetLastError(),"glass_blur swaps");glass_blur_gaussian_kernel<<<(n+255)/256,256,0,s>>>(work,out,c,radius);check(cudaGetLastError(),"glass_blur final gaussian");check(cudaFree(work),"glass_blur cudaFree");}
}
