#include "augmatch/color/hsv.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ unsigned char sat(float v){return (unsigned char)fminf(255.f,fmaxf(0.f,rintf(v)));}
__global__ void hsv_kernel(const unsigned char* in,unsigned char* out,HSVShiftConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height;if(i>=n)return;const unsigned char* p=in+i*c.channels;unsigned char* q=out+i*c.channels;float r=p[0]/255.f,g=p[1]/255.f,b=p[2]/255.f,mx=fmaxf(r,fmaxf(g,b)),mn=fminf(r,fminf(g,b)),d=mx-mn,h=0;if(d>1e-6f){if(mx==r)h=60.f*fmodf((g-b)/d+6.f,6.f);else if(mx==g)h=60.f*((b-r)/d+2.f);else h=60.f*((r-g)/d+4.f);}float s=mx<=1e-6f?0.f:d/mx,v=mx;int hb=((int)floorf(h/2.f+0.5f)+c.hue_shift)%180;if(hb<0)hb+=180;float sb=fminf(255.f,fmaxf(0.f,floorf(s*255.f+c.saturation_shift+0.5f)))/255.f,vb=fminf(255.f,fmaxf(0.f,floorf(v*255.f+c.value_shift+0.5f)))/255.f;float hf=hb*2.f,sector=hf/60.f,ff=sector-floorf(sector),pp=vb*(1-sb),qq=vb*(1-sb*ff),tt=vb*(1-sb*(1-ff)),rr,gg,bb;int si=((int)floorf(sector))%6;if(si==0){rr=vb;gg=tt;bb=pp;}else if(si==1){rr=qq;gg=vb;bb=pp;}else if(si==2){rr=pp;gg=vb;bb=tt;}else if(si==3){rr=pp;gg=qq;bb=vb;}else if(si==4){rr=tt;gg=pp;bb=vb;}else{rr=vb;gg=pp;bb=qq;}q[0]=sat(rr*255);q[1]=sat(gg*255);q[2]=sat(bb*255);for(int ch=3;ch<c.channels;++ch)q[ch]=p[ch];}
enum HsvBatchOp { MBrightness, ABrightness, MABrightness, SetHS, MHS, MHue, MSat, RSat, AHS, AHue, ASat };
__device__ int clip_bin(float v){return max(0,min(255,(int)floorf(v+0.5f)));}
__device__ int wrap_hue(float v){int x=((int)floorf(v+0.5f))%180;return x<0?x+180:x;}
__device__ void rgb_to_opencv_hsv(const unsigned char* p,int& hue,int& saturation,int& value){int r=p[0],g=p[1],b=p[2];value=max(r,max(g,b));int minimum=min(r,min(g,b)),delta=value-minimum;int saturation_div=value?(int)lrintf((255<<12)/(float)value):0;saturation=(delta*saturation_div+(1<<11))>>12;int numerator;if(value==r)numerator=g-b;else if(value==g)numerator=b-r+2*delta;else numerator=r-g+4*delta;int hue_div=delta?(int)lrintf((180<<12)/(6.0f*delta)):0;hue=(numerator*hue_div+(1<<11))>>12;if(hue<0)hue+=180;}
__global__ void hsv_batch_kernel(const unsigned char* in,unsigned char* out,int width,int height,int channels,int op,float a,float b){int i=blockIdx.x*blockDim.x+threadIdx.x,n=width*height;if(i>=n)return;const unsigned char* p=in+i*channels;unsigned char* q=out+i*channels;int h,s,v;rgb_to_opencv_hsv(p,h,s,v);switch(op){case MBrightness:v=clip_bin(v*a);break;case ABrightness:v=clip_bin(v+a);break;case MABrightness:v=clip_bin(v*a+b);break;case SetHS:h=wrap_hue(a);s=clip_bin(b);break;case MHS:h=wrap_hue(h*a);s=clip_bin(s*b);break;case MHue:h=wrap_hue(h*a);break;case MSat:s=clip_bin(s*a);break;case RSat:s=0;break;case AHS:h=wrap_hue(h+a);s=clip_bin(s+b);break;case AHue:h=wrap_hue(h+a);break;case ASat:s=clip_bin(s+a);break;}float value=v/255.f,saturation=s/255.f,sector=(h*2.f)/60.f,part=sector-floorf(sector),pv=value*(1.f-saturation),qv=value*(1.f-saturation*part),tv=value*(1.f-saturation*(1.f-part)),rr=0.f,gg=0.f,bb=0.f;switch(h/30){case 0:rr=value;gg=tv;bb=pv;break;case 1:rr=qv;gg=value;bb=pv;break;case 2:rr=pv;gg=value;bb=tv;break;case 3:rr=pv;gg=qv;bb=value;break;case 4:rr=tv;gg=pv;bb=value;break;default:rr=value;gg=pv;bb=qv;break;}q[0]=sat(rr*255.f);q[1]=sat(gg*255.f);q[2]=sat(bb*255.f);for(int ch=3;ch<channels;++ch)q[ch]=p[ch];}
void check(cudaError_t e,const char* p){if(e!=cudaSuccess)throw std::runtime_error(std::string(p)+": "+cudaGetErrorString(e));}
void valid(int w,int h,int c){if(w<=0||h<=0||c<3)throw std::invalid_argument("HSV requires RGB dimensions");}
void finite(float v,const char* name,bool nonnegative=false){if(!std::isfinite(v)||(nonnegative&&v<0.f))throw std::invalid_argument(std::string(name)+" is invalid");}
void launch(const std::uint8_t* in,std::uint8_t* out,int w,int h,int c,int op,float a,float b,cudaStream_t stream){valid(w,h,c);if(!in||!out)throw std::invalid_argument("null HSV buffer");int n=w*h;hsv_batch_kernel<<<(n+255)/256,256,0,stream>>>(in,out,w,h,c,op,a,b);check(cudaGetLastError(),"hsv_batch_kernel");}
}
void hsv_shift_u8(const std::uint8_t* in,std::uint8_t* out,const HSVShiftConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out)throw std::invalid_argument("null HSV buffer");int n=c.width*c.height;hsv_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"hsv_kernel");}
void multiply_brightness_u8(const std::uint8_t* i,std::uint8_t* o,const MultiplyBrightnessConfig& c,cudaStream_t s){finite(c.multiplier,"brightness multiplier",true);launch(i,o,c.width,c.height,c.channels,MBrightness,c.multiplier,0,s);}
void add_to_brightness_u8(const std::uint8_t* i,std::uint8_t* o,const AddToBrightnessConfig& c,cudaStream_t s){finite(c.amount,"brightness amount");launch(i,o,c.width,c.height,c.channels,ABrightness,c.amount,0,s);}
void multiply_and_add_to_brightness_u8(const std::uint8_t* i,std::uint8_t* o,const MultiplyAndAddToBrightnessConfig& c,cudaStream_t s){finite(c.multiplier,"brightness multiplier",true);finite(c.addend,"brightness addend");launch(i,o,c.width,c.height,c.channels,MABrightness,c.multiplier,c.addend,s);}
void with_hue_and_saturation_u8(const std::uint8_t* i,std::uint8_t* o,const WithHueAndSaturationConfig& c,cudaStream_t s){finite(c.hue,"hue");finite(c.saturation,"saturation");launch(i,o,c.width,c.height,c.channels,SetHS,c.hue,c.saturation,s);}
void multiply_hue_and_saturation_u8(const std::uint8_t* i,std::uint8_t* o,const MultiplyHueAndSaturationConfig& c,cudaStream_t s){finite(c.hue_multiplier,"hue multiplier",true);finite(c.saturation_multiplier,"saturation multiplier",true);launch(i,o,c.width,c.height,c.channels,MHS,c.hue_multiplier,c.saturation_multiplier,s);}
void multiply_hue_u8(const std::uint8_t* i,std::uint8_t* o,const MultiplyHueConfig& c,cudaStream_t s){finite(c.multiplier,"hue multiplier",true);launch(i,o,c.width,c.height,c.channels,MHue,c.multiplier,0,s);}
void multiply_saturation_u8(const std::uint8_t* i,std::uint8_t* o,const MultiplySaturationConfig& c,cudaStream_t s){finite(c.multiplier,"saturation multiplier",true);launch(i,o,c.width,c.height,c.channels,MSat,c.multiplier,0,s);}
void remove_saturation_u8(const std::uint8_t* i,std::uint8_t* o,const RemoveSaturationConfig& c,cudaStream_t s){launch(i,o,c.width,c.height,c.channels,RSat,0,0,s);}
void add_to_hue_and_saturation_u8(const std::uint8_t* i,std::uint8_t* o,const AddToHueAndSaturationConfig& c,cudaStream_t s){finite(c.hue_amount,"hue amount");finite(c.saturation_amount,"saturation amount");launch(i,o,c.width,c.height,c.channels,AHS,c.hue_amount,c.saturation_amount,s);}
void add_to_hue_u8(const std::uint8_t* i,std::uint8_t* o,const AddToHueConfig& c,cudaStream_t s){finite(c.amount,"hue amount");launch(i,o,c.width,c.height,c.channels,AHue,c.amount,0,s);}
void add_to_saturation_u8(const std::uint8_t* i,std::uint8_t* o,const AddToSaturationConfig& c,cudaStream_t s){finite(c.amount,"saturation amount");launch(i,o,c.width,c.height,c.channels,ASat,c.amount,0,s);}
}
