#include "augmatch/catalog/imgcorruptlike.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>

namespace augmatch {
namespace {
__device__ std::uint64_t mix(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__device__ float uni(std::uint64_t seed,std::uint64_t i){return static_cast<float>(mix(seed+i)>>40)/16777216.0f;}
__device__ float norm(std::uint64_t seed,std::uint64_t i){const float u=fmaxf(uni(seed,i*2),1.0e-7f),v=uni(seed,i*2+1);return sqrtf(-2.0f*logf(u))*cosf(6.2831853071795864769f*v);}
__device__ unsigned char sat(float x){return static_cast<unsigned char>(fminf(255.0f,fmaxf(0.0f,floorf(x+0.5f))));}
__device__ float field(const float* f,std::uint64_t seed,int p){return f?f[p]:uni(seed,static_cast<std::uint64_t>(p));}
__global__ void speckle_kernel(const unsigned char* in,unsigned char* out,SpeckleNoiseConfig c){const int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i<n)out[i]=sat(static_cast<float>(in[i])*(1.0f+c.mean+c.stddev*norm(c.seed,static_cast<std::uint64_t>(i))));}
__global__ void fog_kernel(const unsigned char* in,unsigned char* out,FogConfig c){const int p=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height;if(p>=n)return;const float a=fminf(1.0f,c.density*c.opacity*field(c.field,c.seed,p));for(int ch=0;ch<c.channels;++ch)out[p*c.channels+ch]=sat((1.0f-a)*in[p*c.channels+ch]+a*255.0f);}
__global__ void frost_kernel(const unsigned char* in,unsigned char* out,FrostConfig c){const int p=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height;if(p>=n)return;const float a=fminf(1.0f,c.intensity*c.opacity*field(c.field,c.seed,p));for(int ch=0;ch<c.channels;++ch){const float frost=ch==0?230.0f:(ch==1?240.0f:255.0f);out[p*c.channels+ch]=sat((1.0f-a)*in[p*c.channels+ch]+a*frost);}}
__global__ void snow_kernel(const unsigned char* in,unsigned char* out,SnowConfig c){const int p=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height;if(p>=n)return;const float f=field(c.field,c.seed,p),a=f>=1.0f-c.density?c.opacity:0.0f;for(int ch=0;ch<c.channels;++ch)out[p*c.channels+ch]=sat((1.0f-a)*in[p*c.channels+ch]+a*255.0f);}
__global__ void contrast_kernel(const unsigned char* in,unsigned char* out,ContrastConfig c){const int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i<n)out[i]=sat((static_cast<float>(in[i])-127.5f)*c.factor+127.5f);}
__global__ void brightness_kernel(const unsigned char* in,unsigned char* out,BrightnessConfig c){const int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i<n)out[i]=sat(static_cast<float>(in[i])*c.factor);}
__device__ void rgb_to_hsv(float r,float g,float b,float& h,float& s,float& v){const float mx=fmaxf(r,fmaxf(g,b)),mn=fminf(r,fminf(g,b)),d=mx-mn;v=mx;s=mx==0?0:d/mx;h=0;if(d!=0){if(mx==r)h=fmodf((g-b)/d,6.0f);else if(mx==g)h=(b-r)/d+2.0f;else h=(r-g)/d+4.0f;h/=6.0f;if(h<0)h+=1.0f;}}
__device__ void hsv_to_rgb(float h,float s,float v,float& r,float& g,float& b){if(s==0){r=g=b=v;return;}const float q=h*6.0f;const int i=static_cast<int>(floorf(q));const float f=q-i,p=v*(1-s),t=v*(1-s*f),u=v*(1-s*(1-f));switch(i%6){case 0:r=v;g=u;b=p;break;case 1:r=t;g=v;b=p;break;case 2:r=p;g=v;b=u;break;case 3:r=p;g=t;b=v;break;case 4:r=u;g=p;b=v;break;default:r=v;g=p;b=t;break;}}
__global__ void saturate_kernel(const unsigned char* in,unsigned char* out,SaturateConfig c){const int p=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height;if(p>=n)return;const unsigned char* s=in+p*c.channels;unsigned char* d=out+p*c.channels;if(c.channels<3){for(int ch=0;ch<c.channels;++ch)d[ch]=s[ch];return;}float h,ss,v,r,g,b;rgb_to_hsv(s[0]/255.0f,s[1]/255.0f,s[2]/255.0f,h,ss,v);hsv_to_rgb(h,fminf(1.0f,ss*c.factor),v,r,g,b);d[0]=sat(r*255);d[1]=sat(g*255);d[2]=sat(b*255);for(int ch=3;ch<c.channels;++ch)d[ch]=s[ch];}
__global__ void pixelate_kernel(const unsigned char* in,unsigned char* out,PixelateConfig c){const int p=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height;if(p>=n)return;const int x=p%c.width,y=p/c.width,sx=min(c.width-1,(x/c.block_size)*c.block_size+c.block_size/2),sy=min(c.height-1,(y/c.block_size)*c.block_size+c.block_size/2);for(int ch=0;ch<c.channels;++ch)out[p*c.channels+ch]=in[(sy*c.width+sx)*c.channels+ch];}
void check(cudaError_t e,const char* n){if(e!=cudaSuccess)throw std::runtime_error(std::string(n)+": "+cudaGetErrorString(e));}
void dims(int w,int h,int c){if(w<=0||h<=0||c<=0)throw std::invalid_argument("imgcorruptlike dimensions and channels must be positive");}
void io(const void* i,const void* o){if(!i||!o)throw std::invalid_argument("imgcorruptlike input and output are required");}
void unit(float x,const char* n){if(!std::isfinite(x)||x<0||x>1)throw std::invalid_argument(std::string(n)+" must be finite and in [0,1]");}
}
void speckle_noise_u8(const std::uint8_t* i,std::uint8_t* o,const SpeckleNoiseConfig& c,cudaStream_t s){dims(c.width,c.height,c.channels);io(i,o);if(!std::isfinite(c.mean)||!std::isfinite(c.stddev)||c.stddev<0)throw std::invalid_argument("invalid SpeckleNoise parameters");int n=c.width*c.height*c.channels;speckle_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"speckle_noise_kernel");}
void fog_u8(const std::uint8_t* i,std::uint8_t* o,const FogConfig& c,cudaStream_t s){dims(c.width,c.height,c.channels);io(i,o);unit(c.density,"Fog density");unit(c.opacity,"Fog opacity");int n=c.width*c.height;fog_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"fog_kernel");}
void frost_u8(const std::uint8_t* i,std::uint8_t* o,const FrostConfig& c,cudaStream_t s){dims(c.width,c.height,c.channels);io(i,o);unit(c.intensity,"Frost intensity");unit(c.opacity,"Frost opacity");int n=c.width*c.height;frost_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"frost_kernel");}
void snow_u8(const std::uint8_t* i,std::uint8_t* o,const SnowConfig& c,cudaStream_t s){dims(c.width,c.height,c.channels);io(i,o);unit(c.density,"Snow density");unit(c.opacity,"Snow opacity");int n=c.width*c.height;snow_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"snow_kernel");}
void contrast_u8(const std::uint8_t* i,std::uint8_t* o,const ContrastConfig& c,cudaStream_t s){dims(c.width,c.height,c.channels);io(i,o);if(!std::isfinite(c.factor)||c.factor<0)throw std::invalid_argument("invalid Contrast factor");int n=c.width*c.height*c.channels;contrast_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"contrast_kernel");}
void brightness_u8(const std::uint8_t* i,std::uint8_t* o,const BrightnessConfig& c,cudaStream_t s){dims(c.width,c.height,c.channels);io(i,o);if(!std::isfinite(c.factor)||c.factor<0)throw std::invalid_argument("invalid Brightness factor");int n=c.width*c.height*c.channels;brightness_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"brightness_kernel");}
void saturate_u8(const std::uint8_t* i,std::uint8_t* o,const SaturateConfig& c,cudaStream_t s){dims(c.width,c.height,c.channels);io(i,o);if(!std::isfinite(c.factor)||c.factor<0)throw std::invalid_argument("invalid Saturate factor");int n=c.width*c.height;saturate_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"saturate_kernel");}
void pixelate_u8(const std::uint8_t* i,std::uint8_t* o,const PixelateConfig& c,cudaStream_t s){dims(c.width,c.height,c.channels);io(i,o);if(c.block_size<=0)throw std::invalid_argument("Pixelate block size must be positive");int n=c.width*c.height;pixelate_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"pixelate_kernel");}
} // namespace augmatch
