#include "augmatch/iso_profile.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ unsigned long long mix(unsigned long long x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__device__ float uni(unsigned long long x){return (float)((mix(x)>>11)*(1.0/9007199254740992.0));}
__device__ float normal(unsigned long long x){float a=fmaxf(uni(x),1.0e-7f);return sqrtf(-2.0f*logf(a))*cosf(6.28318530718f*uni(x^0xd1b54a32d192ed03ULL));}
__device__ unsigned long long key(unsigned long long s,int x,int y,int ch,unsigned long long tag){return s^(unsigned long long)x*0x632be59bd9b4e019ULL^(unsigned long long)y*0x8cb92baa2f2f6f7dULL^(unsigned long long)ch*0x9e3779b97f4a7c15ULL^tag;}
__device__ float poisson(float lambda,unsigned long long seed){if(lambda<=0)return 0;if(lambda<64){float u=uni(seed^0x53484f545f554e49ULL),p=expf(-lambda),cdf=p;int n=0;while(u>cdf&&n<512){++n;p*=lambda/(float)n;cdf+=p;}return (float)n;}return floorf(fmaxf(0.0f,lambda+sqrtf(lambda)*normal(seed^0x53484f545f4e4f52ULL))+0.5f);}
__device__ unsigned char byte_clip(float v){return (unsigned char)floorf(fminf(1.0f,fmaxf(0.0f,v))*255.0f+0.5f);}
__global__ void shot_kernel(const unsigned char* in,unsigned char* out,IsoNoiseApplicationConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float gain=iso_to_gain(c.iso,c.profile),scale=c.shot_scale*iso_shot_noise_scale(c.iso,c.profile);float lambda=((float)in[i]/255.0f)*gain*scale;out[i]=byte_clip(poisson(lambda,key(c.seed,x,y,ch,0x49534f5f53484f54ULL))/scale);}
__global__ void read_kernel(const float* in,float* out,IsoNoiseApplicationConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float sigma=c.read_noise_stddev*iso_read_noise_scale(c.iso,c.profile);out[i]=fmaxf(c.clip_min,fminf(c.clip_max,in[i]+sigma*normal(key(c.seed,x,y,ch,0x49534f5f52454144ULL))));}
__global__ void fpn_kernel(const float* in,float* out,IsoNoiseApplicationConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float sigma=c.fpn_stddev*iso_fpn_scale(c.iso,c.profile);out[i]=fmaxf(c.clip_min,fminf(c.clip_max,in[i]+sigma*normal(key(c.seed,x,y,ch,0x49534f5f46504e4eULL))));}
__global__ void exposure_dark_kernel(const float* in,float* out,ExposureTimeDarkCurrentConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float lambda=c.dark_current_electrons_per_second*c.exposure_seconds*iso_to_gain(c.iso,c.profile);float dark=poisson(lambda,key(c.seed,x,y,ch,0x4441524b5f54494dULL));out[i]=fmaxf(c.clip_min,fminf(c.clip_max,in[i]+dark/c.electrons_per_unit));}
__global__ void temperature_noise_kernel(const float* in,float* out,TemperatureNoiseScalingConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float thermal=expf(c.temperature_noise_coefficient_per_celsius*(c.temperature_celsius-c.reference_temperature_celsius));float sigma=c.noise_stddev_electrons*thermal*iso_to_gain(c.iso,c.profile)*iso_read_noise_scale(c.iso,c.profile)/c.electrons_per_unit;out[i]=fmaxf(c.clip_min,fminf(c.clip_max,in[i]+sigma*normal(key(c.seed,x,y,ch,0x54454d505f4e4f49ULL))));}
__device__ float transition_weight(float gain,float low,float high,float width){if(high<=low)return gain>=high?1.0f:0.0f;float t=(gain-low)/(high-low);if(width<=0.0f)return fminf(1.0f,fmaxf(0.0f,t));if(width*2.0f>=high-low){float q=fminf(1.0f,fmaxf(0.0f,t));return q*q*(3.0f-2.0f*q);}float w=width/(high-low);float q=fminf(1.0f,fmaxf(0.0f,(t-w)/(1.0f-2.0f*w)));return q*q*(3.0f-2.0f*q);}
__global__ void dual_conversion_kernel(const float* in,float* out,DualConversionGainConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float w=transition_weight(iso_to_gain(c.iso,c.profile),c.low_gain_threshold,c.high_gain_threshold,0.0f);float conversion=c.low_conversion_gain+(c.high_conversion_gain-c.low_conversion_gain)*w;float sigma=(c.low_read_noise_electrons+(c.high_read_noise_electrons-c.low_read_noise_electrons)*w)/c.electrons_per_unit;float v=in[i]*conversion+sigma*normal(key(c.seed,x,y,ch,0x4443475f4e4f4953ULL));out[i]=fmaxf(c.clip_min,fminf(c.clip_max,v));}
__global__ void gain_transition_kernel(const float* in,float* out,GainSwitchTransitionConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;float gain=iso_to_gain(c.iso,c.profile),lo=c.low_gain_threshold-c.hysteresis,hi=c.high_gain_threshold+c.hysteresis,w=transition_weight(gain,lo,hi,c.transition_width);if(c.initial_high_gain&&gain>lo&&gain<c.low_gain_threshold)w=1.0f;if(!c.initial_high_gain&&gain>c.high_gain_threshold&&gain<hi)w=0.0f;float v=in[i]*(c.low_signal_gain+(c.high_signal_gain-c.low_signal_gain)*w)+c.transition_strength*w*(1.0f-w);out[i]=fmaxf(c.clip_min,fminf(c.clip_max,v));}
__global__ void levels_kernel(const unsigned char* in,unsigned char* out,IsoNoiseApplicationConfig c,int mode){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int lo=(int)rintf(255.0f*iso_black_level(c.iso,c.profile)),hi=(int)rintf(255.0f*iso_saturation_level(c.iso,c.profile)),v=(int)in[i];if(mode==0)v=max(v,lo);else if(mode==1)v=min(v,hi);else v=max(lo,min(hi,v));out[i]=(unsigned char)v;}
void check(cudaError_t e,const char* where){if(e!=cudaSuccess)throw std::runtime_error(std::string(where)+": "+cudaGetErrorString(e));}
void valid(const IsoNoiseApplicationConfig& c,const void* in,const void* out){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||!isfinite(c.iso)||c.iso<=0||!isfinite(c.shot_scale)||c.shot_scale<=0||!isfinite(c.read_noise_stddev)||c.read_noise_stddev<0||!isfinite(c.fpn_stddev)||c.fpn_stddev<0||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||!c.profile.points||c.profile.point_count==0)throw std::invalid_argument("invalid ISO noise profile configuration");}
}
void iso_shot_noise_u8(const std::uint8_t* i,std::uint8_t* o,const IsoNoiseApplicationConfig& c,cudaStream_t s){valid(c,i,o);int n=c.width*c.height*c.channels;shot_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"iso_shot_noise_kernel");}
void iso_read_noise_f32(const float* i,float* o,const IsoNoiseApplicationConfig& c,cudaStream_t s){valid(c,i,o);int n=c.width*c.height*c.channels;read_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"iso_read_noise_kernel");}
void iso_fpn_f32(const float* i,float* o,const IsoNoiseApplicationConfig& c,cudaStream_t s){valid(c,i,o);int n=c.width*c.height*c.channels;fpn_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"iso_fpn_kernel");}
void exposure_time_dark_current_f32(const float* i,float* o,const ExposureTimeDarkCurrentConfig& c,cudaStream_t s){
  IsoNoiseApplicationConfig base{};base.width=c.width;base.height=c.height;base.channels=c.channels;base.iso=c.iso;base.profile=c.profile;base.shot_scale=1.0f;base.clip_min=c.clip_min;base.clip_max=c.clip_max;
  valid(base,i,o);if(!isfinite(c.dark_current_electrons_per_second)||c.dark_current_electrons_per_second<0.0f||!isfinite(c.exposure_seconds)||c.exposure_seconds<0.0f||!isfinite(c.electrons_per_unit)||c.electrons_per_unit<=0.0f)throw std::invalid_argument("invalid exposure-time dark-current configuration");
  if(!isfinite(c.dark_current_electrons_per_second*c.exposure_seconds)||c.dark_current_electrons_per_second*c.exposure_seconds<0.0f)throw std::invalid_argument("invalid exposure-time dark-current rate");
  int n=c.width*c.height*c.channels;exposure_dark_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"exposure_dark_current_kernel");
}
void temperature_noise_scaling_f32(const float* i,float* o,const TemperatureNoiseScalingConfig& c,cudaStream_t s){
  IsoNoiseApplicationConfig base{};base.width=c.width;base.height=c.height;base.channels=c.channels;base.iso=c.iso;base.profile=c.profile;base.shot_scale=1.0f;base.clip_min=c.clip_min;base.clip_max=c.clip_max;
  valid(base,i,o);if(!isfinite(c.noise_stddev_electrons)||c.noise_stddev_electrons<0.0f||!isfinite(c.temperature_celsius)||!isfinite(c.reference_temperature_celsius)||!isfinite(c.temperature_noise_coefficient_per_celsius)||!isfinite(c.electrons_per_unit)||c.electrons_per_unit<=0.0f)throw std::invalid_argument("invalid temperature noise-scaling configuration");
  const float thermal=expf(c.temperature_noise_coefficient_per_celsius*(c.temperature_celsius-c.reference_temperature_celsius));if(!isfinite(thermal))throw std::invalid_argument("invalid temperature noise-scaling result");
  int n=c.width*c.height*c.channels;temperature_noise_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"temperature_noise_scaling_kernel");
}
void dual_conversion_gain_f32(const float* i,float* o,const DualConversionGainConfig& c,cudaStream_t s){IsoNoiseApplicationConfig base{};base.width=c.width;base.height=c.height;base.channels=c.channels;base.iso=c.iso;base.profile=c.profile;base.shot_scale=1.0f;base.clip_min=c.clip_min;base.clip_max=c.clip_max;valid(base,i,o);if(!isfinite(c.low_gain_threshold)||!isfinite(c.high_gain_threshold)||c.low_gain_threshold<0||c.high_gain_threshold<c.low_gain_threshold||!isfinite(c.low_conversion_gain)||!isfinite(c.high_conversion_gain)||c.low_conversion_gain<0||c.high_conversion_gain<0||!isfinite(c.low_read_noise_electrons)||!isfinite(c.high_read_noise_electrons)||c.low_read_noise_electrons<0||c.high_read_noise_electrons<0||!isfinite(c.electrons_per_unit)||c.electrons_per_unit<=0)throw std::invalid_argument("invalid dual-conversion-gain configuration");int n=c.width*c.height*c.channels;dual_conversion_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"dual_conversion_gain_kernel");}
void gain_switch_transition_f32(const float* i,float* o,const GainSwitchTransitionConfig& c,cudaStream_t s){IsoNoiseApplicationConfig base{};base.width=c.width;base.height=c.height;base.channels=c.channels;base.iso=c.iso;base.profile=c.profile;base.shot_scale=1.0f;base.clip_min=c.clip_min;base.clip_max=c.clip_max;valid(base,i,o);if(!isfinite(c.low_gain_threshold)||!isfinite(c.high_gain_threshold)||c.low_gain_threshold<0||c.high_gain_threshold<c.low_gain_threshold||!isfinite(c.hysteresis)||c.hysteresis<0||!isfinite(c.transition_width)||c.transition_width<0||!isfinite(c.low_signal_gain)||!isfinite(c.high_signal_gain)||c.low_signal_gain<0||c.high_signal_gain<0||!isfinite(c.transition_strength)||c.transition_strength<0)throw std::invalid_argument("invalid gain-switch transition configuration");int n=c.width*c.height*c.channels;gain_transition_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"gain_switch_transition_kernel");}
void levels(const std::uint8_t* i,std::uint8_t* o,const IsoNoiseApplicationConfig& c,int mode,cudaStream_t s){valid(c,i,o);int n=c.width*c.height*c.channels;levels_kernel<<<(n+255)/256,256,0,s>>>(i,o,c,mode);check(cudaGetLastError(),"iso_levels_kernel");}
void iso_black_level_u8(const std::uint8_t* i,std::uint8_t* o,const IsoNoiseApplicationConfig& c,cudaStream_t s){levels(i,o,c,0,s);}
void iso_saturation_level_u8(const std::uint8_t* i,std::uint8_t* o,const IsoNoiseApplicationConfig& c,cudaStream_t s){levels(i,o,c,1,s);}
void iso_signal_levels_u8(const std::uint8_t* i,std::uint8_t* o,const IsoNoiseApplicationConfig& c,cudaStream_t s){levels(i,o,c,2,s);}
}

namespace augmatch { namespace {
__device__ unsigned long long camera_mix(unsigned long long x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__device__ float camera_uniform(unsigned long long x){return (float)((camera_mix(x)>>11)*(1.0/9007199254740992.0));}
__device__ float camera_normal(unsigned long long x){float a=fmaxf(camera_uniform(x),1.0e-7f);return sqrtf(-2.0f*logf(a))*cosf(6.28318530718f*camera_uniform(x^0xd1b54a32d192ed03ULL));}
__device__ unsigned long long camera_key(unsigned long long s,int x,int y,int ch,unsigned long long tag){return s^(unsigned long long)x*0x632be59bd9b4e019ULL^(unsigned long long)y*0x8cb92baa2f2f6f7dULL^(unsigned long long)ch*0x9e3779b97f4a7c15ULL^tag;}
__device__ float camera_poisson(float lambda,unsigned long long seed){if(lambda<=0)return 0;if(lambda<64){float u=camera_uniform(seed^0x53484f545f554e49ULL),p=expf(-lambda),cdf=p;int n=0;while(u>cdf&&n<512){++n;p*=lambda/(float)n;cdf+=p;}return(float)n;}return floorf(fmaxf(0.0f,lambda+sqrtf(lambda)*camera_normal(seed^0x53484f545f4e4f52ULL))+0.5f);}
__global__ void camera_profile_kernel(const float* in,float* out,CameraProfileLookupConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float gain=camera_profile_gain(c.iso,c.profile);float shot=camera_profile_lookup_value(c.iso,c.profile,CameraProfileLookupParameter::ShotScale)*camera_profile_lookup_value(c.iso,c.profile,CameraProfileLookupParameter::ShotNoiseScale);float read=camera_profile_lookup_value(c.iso,c.profile,CameraProfileLookupParameter::ReadNoiseStddev)*camera_profile_lookup_value(c.iso,c.profile,CameraProfileLookupParameter::ReadNoiseScale);float fpn=camera_profile_lookup_value(c.iso,c.profile,CameraProfileLookupParameter::FPNStddev)*camera_profile_lookup_value(c.iso,c.profile,CameraProfileLookupParameter::FPNScale);unsigned long long k=camera_key(c.seed,x,y,ch,0x43414d4552415f53ULL);float v=in[i]*gain;if(shot>0)v=camera_poisson(fmaxf(0.0f,v*shot),k)/shot;v+=read*camera_normal(k^0x524541445f4e4f49ULL)+fpn*camera_normal(k^0x46504e5f4e4f49ULL);out[i]=fmaxf(c.clip_min,fminf(c.clip_max,v));}
__global__ void calibration_kernel(const float* in,float* out,CalibrationFrameNoiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float gain=c.calibration.gain_map?c.calibration.gain_map[i]:1.0f;float sigma=c.calibration.read_noise_map?c.calibration.read_noise_map[i]:c.calibration.read_noise_stddev;unsigned long long k=camera_key(c.seed,x,y,ch,0x43414c5f53484f54ULL);float fpn=c.calibration.fpn_map?c.calibration.fpn_map[i]:c.calibration.fpn_stddev*camera_normal(camera_key(c.seed,x,y,ch,0x43414c5f46504e4eULL));float v=in[i]*gain;if(c.calibration.shot_noise_scale>0)v=camera_poisson(fmaxf(0.0f,v*c.calibration.shot_noise_scale),k)/c.calibration.shot_noise_scale;v+=sigma*camera_normal(k^0x524541445f4e4f49ULL)+fpn;out[i]=fmaxf(c.clip_min,fminf(c.clip_max,v));}
void valid_camera_cuda(const CameraProfileLookupConfig& c,const void* in,const void* out){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||!isfinite(c.iso)||c.iso<=0||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||!c.profile.points||c.profile.point_count==0)throw std::invalid_argument("invalid camera profile lookup configuration");}
void valid_calibration_cuda(const CalibrationFrameNoiseConfig& c,const void* in,const void* out){std::size_t n=(std::size_t)c.width*c.height*c.channels;if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||!isfinite(c.calibration.shot_noise_scale)||c.calibration.shot_noise_scale<0||!isfinite(c.calibration.read_noise_stddev)||c.calibration.read_noise_stddev<0||!isfinite(c.calibration.fpn_stddev)||c.calibration.fpn_stddev<0||((c.calibration.read_noise_map||c.calibration.fpn_map||c.calibration.gain_map)&&c.calibration.map_count!=n))throw std::invalid_argument("invalid calibration-frame noise configuration");}
}
void camera_profile_lookup_f32(const float* i,float* o,const CameraProfileLookupConfig& c,cudaStream_t s){valid_camera_cuda(c,i,o);int n=c.width*c.height*c.channels;camera_profile_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"camera_profile_lookup_kernel");}
void calibration_frame_noise_f32(const float* i,float* o,const CalibrationFrameNoiseConfig& c,cudaStream_t s){valid_calibration_cuda(c,i,o);int n=c.width*c.height*c.channels;calibration_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"calibration_frame_noise_kernel");}
}
