#include "augmatch/isp/isp_artifacts.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace augmatch { namespace {
void valid(const std::uint8_t* in,const std::uint8_t* out,int w,int h,int c){if(!in||!out||w<=0||h<=0||c<=0)throw std::invalid_argument("invalid ISP artifact dimensions");}
int clampi(int i,int n){return std::max(0,std::min(n-1,i));}
float clip(float v){return std::floor(std::max(0.0f,std::min(255.0f,v))+0.5f);}
std::size_t at(int x,int y,int ch,int w,int c){return (static_cast<std::size_t>(y)*w+x)*c+ch;}
void basic(const std::uint8_t* in,std::uint8_t* out,int w,int h,int c,float amount,int kind){
  for(int y=0;y<h;++y)for(int x=0;x<w;++x)for(int ch=0;ch<c;++ch){const float p=in[at(x,y,ch,w,c)];float residual=0.0f;
    if(kind==0){for(int dy=-1;dy<=1;++dy)for(int dx=-1;dx<=1;++dx)if(dx||dy)residual-=in[at(clampi(x+dx,w),clampi(y+dy,h),ch,w,c)];residual+=8.0f*p;}
    else residual=4.0f*p-in[at(clampi(x-1,w),y,ch,w,c)]-in[at(clampi(x+1,w),y,ch,w,c)]-in[at(x,clampi(y-1,h),ch,w,c)]-in[at(x,clampi(y+1,h),ch,w,c)];
    out[at(x,y,ch,w,c)]=static_cast<std::uint8_t>(clip(p+amount*residual));
  }
}
void validate_map(const float* map,int map_channels,int channels,int width,int height){if(map_channels!=1&&map_channels!=channels)throw std::invalid_argument("residual map_channels must be 1 or channels");if(map){const std::size_t n=static_cast<std::size_t>(width)*height*(map_channels==1?1:channels);for(std::size_t i=0;i<n;++i)if(!std::isfinite(map[i]))throw std::invalid_argument("residual map values must be finite");}}
float residual_map(const float* map,int map_channels,int x,int y,int ch,int w,int c){return map[(static_cast<std::size_t>(y)*w+x)*(map_channels==1?1:c)+(map_channels==1?0:ch)];}
float lap_residual(const std::uint8_t* in,int x,int y,int ch,int w,int h,int c){const float p=in[at(x,y,ch,w,c)];return 4.0f*p-in[at(clampi(x-1,w),y,ch,w,c)]-in[at(clampi(x+1,w),y,ch,w,c)]-in[at(x,clampi(y-1,h),ch,w,c)]-in[at(x,clampi(y+1,h),ch,w,c)];}
float sobel_residual(const std::uint8_t* in,int x,int y,int ch,int w,int h,int c,int direction){const int k[3]={-1,0,1};float r=0;for(int dy=-1;dy<=1;++dy)for(int dx=-1;dx<=1;++dx){const int weight=direction==0?((dy==0?2:1)*k[dx+1]):((dx==0?2:1)*k[dy+1]);r+=weight*in[at(clampi(x+dx,w),clampi(y+dy,h),ch,w,c)];}return r;}
float highpass_residual(const std::uint8_t* in,int x,int y,int ch,int w,int h,int c){const float p=in[at(x,y,ch,w,c)];float r=8.0f*p;for(int dy=-1;dy<=1;++dy)for(int dx=-1;dx<=1;++dx)if(dx||dy)r-=in[at(clampi(x+dx,w),clampi(y+dy,h),ch,w,c)];return r;}
template<class Config,class Derived> void inject(const std::uint8_t* in,std::uint8_t* out,const Config& c,Derived derived){valid(in,out,c.width,c.height,c.channels);if(!std::isfinite(c.amount)||c.amount<0)throw std::invalid_argument("invalid residual injection amount");validate_map(c.residual_map,c.map_channels,c.channels,c.width,c.height);for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const std::size_t i=at(x,y,ch,c.width,c.channels);const float r=c.residual_map?residual_map(c.residual_map,c.map_channels,x,y,ch,c.width,c.channels):derived(in,x,y,ch,c.width,c.height,c.channels);out[i]=static_cast<std::uint8_t>(clip(in[i]+c.amount*r));}}
void validate_radius(int radius,float sigma){if(radius<1||radius>15||!std::isfinite(sigma)||sigma<=0)throw std::invalid_argument("invalid ISP filter radius or sigma");}
float blur(const std::uint8_t* in,int w,int h,int c,int x,int y,int ch,int radius,float sigma,bool gaussian){
  float sum=0,weights=0; const float inv=1.0f/(2.0f*sigma*sigma);
  for(int dy=-radius;dy<=radius;++dy)for(int dx=-radius;dx<=radius;++dx){const float weight=gaussian?std::exp(-(dx*dx+dy*dy)*inv):1.0f;sum+=weight*in[at(clampi(x+dx,w),clampi(y+dy,h),ch,w,c)];weights+=weight;}
  return sum/weights;
}
void highboost(const std::uint8_t* in,std::uint8_t* out,int w,int h,int c,int radius,float sigma,float amount,float gain){
  validate_radius(radius,sigma);if(!std::isfinite(amount)||amount<0||!std::isfinite(gain)||gain<0)throw std::invalid_argument("invalid ISP highboost configuration");
  for(int y=0;y<h;++y)for(int x=0;x<w;++x)for(int ch=0;ch<c;++ch){const float p=in[at(x,y,ch,w,c)],d=p-blur(in,w,h,c,x,y,ch,radius,sigma,true);out[at(x,y,ch,w,c)]=static_cast<std::uint8_t>(clip(p+amount*gain*d));}
}
}}
namespace augmatch {
void edge_oversharpening_u8(const std::uint8_t* in,std::uint8_t* out,const EdgeOversharpeningConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);if(!std::isfinite(c.amount)||c.amount<0)throw std::invalid_argument("invalid edge oversharpening configuration");basic(in,out,c.width,c.height,c.channels,c.amount,0);}
void unsharp_mask_halos_u8(const std::uint8_t* in,std::uint8_t* out,const UnsharpMaskHalosConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);highboost(in,out,c.width,c.height,c.channels,c.radius,c.sigma,c.amount,1.0f);}
void laplacian_halos_u8(const std::uint8_t* in,std::uint8_t* out,const LaplacianHalosConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);if(!std::isfinite(c.amount)||c.amount<0)throw std::invalid_argument("invalid Laplacian halo configuration");basic(in,out,c.width,c.height,c.channels,c.amount,1);}
void laplacian_residual_injection_u8(const std::uint8_t* in,std::uint8_t* out,const LaplacianResidualInjectionConfig& c,cudaStream_t){inject(in,out,c,[](const std::uint8_t* p,int x,int y,int ch,int w,int h,int n){return lap_residual(p,x,y,ch,w,h,n);});}
void sobel_residual_injection_u8(const std::uint8_t* in,std::uint8_t* out,const SobelResidualInjectionConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);if(c.direction<0||c.direction>1)throw std::invalid_argument("Sobel residual direction must be 0 or 1");inject(in,out,c,[&c](const std::uint8_t* p,int x,int y,int ch,int w,int h,int n){return sobel_residual(p,x,y,ch,w,h,n,c.direction);});}
void high_pass_residual_injection_u8(const std::uint8_t* in,std::uint8_t* out,const HighPassResidualInjectionConfig& c,cudaStream_t){inject(in,out,c,[](const std::uint8_t* p,int x,int y,int ch,int w,int h,int n){return highpass_residual(p,x,y,ch,w,h,n);});}
void ringing_near_strong_edges_u8(const std::uint8_t* in,std::uint8_t* out,const RingingNearStrongEdgesConfig& c,cudaStream_t){
  valid(in,out,c.width,c.height,c.channels);if(!std::isfinite(c.amount)||c.amount<0||!std::isfinite(c.gradient_threshold)||c.gradient_threshold<0||!std::isfinite(c.residual_bound)||c.residual_bound<0)throw std::invalid_argument("invalid ringing edge configuration");
  for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const float p=in[at(x,y,ch,c.width,c.channels)],left=in[at(clampi(x-1,c.width),y,ch,c.width,c.channels)],right=in[at(clampi(x+1,c.width),y,ch,c.width,c.channels)],up=in[at(x,clampi(y-1,c.height),ch,c.width,c.channels)],down=in[at(x,clampi(y+1,c.height),ch,c.width,c.channels)];const float gradient=std::fabs(right-left)+std::fabs(down-up);float lap=4*p-left-right-up-down;if(gradient<c.gradient_threshold)lap=0;lap=std::max(-c.residual_bound,std::min(c.residual_bound,lap));if((x+y)&1)lap=-lap;out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip(p+c.amount*lap));}
}
void local_contrast_enhancement_artifacts_u8(const std::uint8_t* in,std::uint8_t* out,const LocalContrastEnhancementArtifactsConfig& c,cudaStream_t){
  valid(in,out,c.width,c.height,c.channels);if(c.radius<1||c.radius>15||!std::isfinite(c.amount)||c.amount<0||!std::isfinite(c.epsilon)||c.epsilon<=0)throw std::invalid_argument("invalid local contrast configuration");
  for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){float sum=0,sq=0;int count=0;for(int dy=-c.radius;dy<=c.radius;++dy)for(int dx=-c.radius;dx<=c.radius;++dx){const float q=in[at(clampi(x+dx,c.width),clampi(y+dy,c.height),ch,c.width,c.channels)];sum+=q;sq+=q*q;++count;}const float mean=sum/count,var=std::max(0.0f,sq/count-mean*mean),sigma=std::sqrt(var),p=in[at(x,y,ch,c.width,c.channels)],residual=(p-mean)*sigma/(sigma+c.epsilon);out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip(p+c.amount*residual));}
}
void haloing_from_tone_mapping_u8(const std::uint8_t* in,std::uint8_t* out,const HaloingFromToneMappingConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);if(!std::isfinite(c.tone_strength)||c.tone_strength<0)throw std::invalid_argument("invalid tone halo configuration");highboost(in,out,c.width,c.height,c.channels,c.radius,c.sigma,c.amount,c.tone_strength);}
void local_sharpening_noise_amplification_u8(const std::uint8_t* in,std::uint8_t* out,const LocalSharpeningNoiseAmplificationConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);highboost(in,out,c.width,c.height,c.channels,c.radius,1.0f,c.amount,c.noise_gain);}
void high_frequency_attenuation_u8(const std::uint8_t* in,std::uint8_t* out,const HighFrequencyAttenuationConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);validate_radius(c.radius,1.0f);if(!std::isfinite(c.amount)||c.amount<0||c.amount>1)throw std::invalid_argument("invalid high-frequency attenuation configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const float p=in[at(x,y,ch,c.width,c.channels)],q=blur(in,c.width,c.height,c.channels,x,y,ch,c.radius,1.0f,false);out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip((1-c.amount)*p+c.amount*q));}}
void detail_smearing_u8(const std::uint8_t* in,std::uint8_t* out,const DetailSmearingConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);validate_radius(c.radius,c.sigma);if(!std::isfinite(c.amount)||c.amount<0||c.amount>1)throw std::invalid_argument("invalid detail smearing configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const float p=in[at(x,y,ch,c.width,c.channels)],q=blur(in,c.width,c.height,c.channels,x,y,ch,c.radius,c.sigma,c.gaussian);out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip((1-c.amount)*p+c.amount*q));}}
void overshoot_and_undershoot_u8(const std::uint8_t* in,std::uint8_t* out,const OvershootAndUndershootConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);validate_radius(c.radius,c.sigma);if(!std::isfinite(c.amount)||c.amount<0||!std::isfinite(c.max_overshoot)||c.max_overshoot<0||!std::isfinite(c.max_undershoot)||c.max_undershoot<0)throw std::invalid_argument("invalid overshoot/undershoot configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const float p=in[at(x,y,ch,c.width,c.channels)],residual=std::max(-c.max_undershoot,std::min(c.max_overshoot,c.amount*(p-blur(in,c.width,c.height,c.channels,x,y,ch,c.radius,c.sigma,true))));out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip(p+residual));}}
std::uint64_t isp_mix(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
float isp_normal(std::uint64_t x){const float u=std::max(1.0e-7f,float((isp_mix(x)>>40)&0xffffffULL)/16777216.0f),v=float((isp_mix(x^0xd1b54a32d192ed03ULL)>>40)&0xffffffULL)/16777216.0f;return std::sqrt(-2.0f*std::log(u))*std::cos(6.28318530718f*v);}
void check_coeff(float a,float b,float d){if(!std::isfinite(a)||a<0||!std::isfinite(b)||b<0||!std::isfinite(d)||d<0)throw std::invalid_argument("invalid ISP coefficient");}
void gradient_plus_laplacian_noise_u8(const std::uint8_t* in,std::uint8_t* out,const GradientPlusLaplacianNoiseConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);check_coeff(c.sigma,c.gradient_scale,c.laplacian_scale);for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const float p=in[at(x,y,ch,c.width,c.channels)],gx=float(in[at(clampi(x+1,c.width),y,ch,c.width,c.channels)])-in[at(clampi(x-1,c.width),y,ch,c.width,c.channels)],gy=float(in[at(x,clampi(y+1,c.height),ch,c.width,c.channels)])-in[at(x,clampi(y-1,c.height),ch,c.width,c.channels)],g=std::sqrt(gx*gx+gy*gy)/510.0f,lap=std::fabs(lap_residual(in,x,y,ch,c.width,c.height,c.channels))/1020.0f,s=c.sigma*(1+c.gradient_scale*g+c.laplacian_scale*lap);out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip(p+s*isp_normal(c.seed+at(x,y,ch,c.width,c.channels))));}}
void deblocking_halos_u8(const std::uint8_t* in,std::uint8_t* out,const DeblockingHalosConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);if(c.block_size<2||c.block_size>64||c.radius<1||c.radius>8||!std::isfinite(c.amount)||c.amount<0)throw std::invalid_argument("invalid deblocking configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const int bx=x%c.block_size,by=y%c.block_size;float r=0;int n=0;if(bx<c.radius&&x>0){r+=in[at(x,y,ch,c.width,c.channels)]-in[at(std::max(0,x-c.radius),y,ch,c.width,c.channels)];++n;}if(bx>=c.block_size-c.radius&&x+1<c.width){r+=in[at(x,y,ch,c.width,c.channels)]-in[at(std::min(c.width-1,x+c.radius),y,ch,c.width,c.channels)];++n;}if(by<c.radius&&y>0){r+=in[at(x,y,ch,c.width,c.channels)]-in[at(x,std::max(0,y-c.radius),ch,c.width,c.channels)];++n;}if(by>=c.block_size-c.radius&&y+1<c.height){r+=in[at(x,y,ch,c.width,c.channels)]-in[at(x,std::min(c.height-1,y+c.radius),ch,c.width,c.channels)];++n;}const float p=in[at(x,y,ch,c.width,c.channels)];out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip(p-c.amount*(n?r/n:0)));}}
void demosaicing_edge_artifacts_u8(const std::uint8_t* in,std::uint8_t* out,const DemosaicingEdgeArtifactsConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);if(!std::isfinite(c.strength)||c.strength<0||!std::isfinite(c.gradient_threshold)||c.gradient_threshold<0)throw std::invalid_argument("invalid demosaicing edge configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){for(int ch=0;ch<c.channels;++ch)out[at(x,y,ch,c.width,c.channels)]=in[at(x,y,ch,c.width,c.channels)];if(c.channels<3)continue;const float gx=std::fabs(float(in[at(clampi(x+1,c.width),y,1,c.width,c.channels)])-in[at(clampi(x-1,c.width),y,1,c.width,c.channels)]),gy=std::fabs(float(in[at(x,clampi(y+1,c.height),1,c.width,c.channels)])-in[at(x,clampi(y-1,c.height),1,c.width,c.channels)]);if(gx+gy<c.gradient_threshold)continue;const float z=c.strength*(gx+gy)/2.0f;out[at(x,y,0,c.width,c.channels)]=static_cast<std::uint8_t>(clip(in[at(x,y,0,c.width,c.channels)]+((x+y)&1?z:-z)));out[at(x,y,2,c.width,c.channels)]=static_cast<std::uint8_t>(clip(in[at(x,y,2,c.width,c.channels)]+((x+y)&1?-z:z)));}}
void edge_dependent_quantization_u8(const std::uint8_t* in,std::uint8_t* out,const EdgeDependentQuantizationConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);if(c.step<1||c.step>255||!std::isfinite(c.edge_scale)||c.edge_scale<0)throw std::invalid_argument("invalid edge quantization configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const float gx=std::fabs(float(in[at(clampi(x+1,c.width),y,ch,c.width,c.channels)])-in[at(clampi(x-1,c.width),y,ch,c.width,c.channels)]),gy=std::fabs(float(in[at(x,clampi(y+1,c.height),ch,c.width,c.channels)])-in[at(x,clampi(y-1,c.height),ch,c.width,c.channels)]),step=c.step*(1+c.edge_scale*std::min(1.0f,(gx+gy)/510.0f)),p=in[at(x,y,ch,c.width,c.channels)];out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip(std::floor(p/step+0.5f)*step));}}
void edge_dependent_compression_error_u8(const std::uint8_t* in,std::uint8_t* out,const EdgeDependentCompressionErrorConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);if(c.block_size<2||c.block_size>64||!std::isfinite(c.strength)||c.strength<0||!std::isfinite(c.edge_scale)||c.edge_scale<0)throw std::invalid_argument("invalid compression error configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const float p=in[at(x,y,ch,c.width,c.channels)],q=in[at(std::min(c.width-1,(x/c.block_size)*c.block_size),std::min(c.height-1,(y/c.block_size)*c.block_size),ch,c.width,c.channels)],edge=(std::fabs(float(in[at(clampi(x+1,c.width),y,ch,c.width,c.channels)])-in[at(clampi(x-1,c.width),y,ch,c.width,c.channels)])+std::fabs(float(in[at(x,clampi(y+1,c.height),ch,c.width,c.channels)])-in[at(x,clampi(y-1,c.height),ch,c.width,c.channels)]))/510.0f;out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip(p+c.strength*(q-p)*(1+c.edge_scale*edge)+0.5f*edge*c.strength*isp_normal(c.seed+at(x,y,ch,c.width,c.channels))));}}
void gradient_reversal_u8(const std::uint8_t* in,std::uint8_t* out,const GradientReversalConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);if(!std::isfinite(c.amount)||c.amount<0||!std::isfinite(c.gradient_threshold)||c.gradient_threshold<0)throw std::invalid_argument("invalid gradient reversal configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const float gx=float(in[at(clampi(x+1,c.width),y,ch,c.width,c.channels)])-in[at(clampi(x-1,c.width),y,ch,c.width,c.channels)],gy=float(in[at(x,clampi(y+1,c.height),ch,c.width,c.channels)])-in[at(x,clampi(y-1,c.height),ch,c.width,c.channels)],g=std::fabs(gx)+std::fabs(gy),p=in[at(x,y,ch,c.width,c.channels)];out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip(p-(g>=c.gradient_threshold?c.amount*(gx+gy)/2:0)));}}
void clipped_edge_ringing_u8(const std::uint8_t* in,std::uint8_t* out,const ClippedEdgeRingingConfig& c,cudaStream_t){valid(in,out,c.width,c.height,c.channels);if(!std::isfinite(c.amount)||c.amount<0||!std::isfinite(c.gradient_threshold)||c.gradient_threshold<0||!std::isfinite(c.residual_bound)||c.residual_bound<0)throw std::invalid_argument("invalid clipped ringing configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const float p=in[at(x,y,ch,c.width,c.channels)],l=in[at(clampi(x-1,c.width),y,ch,c.width,c.channels)],r=in[at(clampi(x+1,c.width),y,ch,c.width,c.channels)],u=in[at(x,clampi(y-1,c.height),ch,c.width,c.channels)],d=in[at(x,clampi(y+1,c.height),ch,c.width,c.channels)],g=std::fabs(r-l)+std::fabs(d-u);float z=0;if(g>=c.gradient_threshold&&(p<=1||p>=254)){z=std::max(-c.residual_bound,std::min(c.residual_bound,c.amount*(4*p-l-r-u-d)));if((x+y)&1)z=-z;}out[at(x,y,ch,c.width,c.channels)]=static_cast<std::uint8_t>(clip(p+z));}}
} // namespace augmatch
