#include "augmatch/isp_artifacts.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
#include <type_traits>
namespace augmatch { namespace {
__device__ int ci(int i,int n){return max(0,min(n-1,i));}
__device__ float cuclip(float v){return floorf(fminf(255.0f,fmaxf(0.0f,v))+0.5f);}
__device__ int pos(int x,int y,int ch,int w,int c){return (y*w+x)*c+ch;}
__device__ float gblur(const unsigned char* in,int w,int h,int c,int x,int y,int ch,int r,float sigma,bool gaussian){float sum=0,weight=0,inv=1.0f/(2.0f*sigma*sigma);for(int dy=-r;dy<=r;++dy)for(int dx=-r;dx<=r;++dx){float q=gaussian?expf(-(dx*dx+dy*dy)*inv):1.0f;sum+=q*in[pos(ci(x+dx,w),ci(y+dy,h),ch,w,c)];weight+=q;}return sum/weight;}
__global__ void edge_kernel(const unsigned char* in,unsigned char* out,EdgeOversharpeningConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float p=in[i],r=8*p;for(int dy=-1;dy<=1;++dy)for(int dx=-1;dx<=1;++dx)if(dx||dy)r-=in[pos(ci(x+dx,c.width),ci(y+dy,c.height),ch,c.width,c.channels)];out[i]=(unsigned char)cuclip(p+c.amount*r);}
__global__ void lap_kernel(const unsigned char* in,unsigned char* out,LaplacianHalosConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float p=in[i],r=4*p-in[pos(ci(x-1,c.width),y,ch,c.width,c.channels)]-in[pos(ci(x+1,c.width),y,ch,c.width,c.channels)]-in[pos(x,ci(y-1,c.height),ch,c.width,c.channels)]-in[pos(x,ci(y+1,c.height),ch,c.width,c.channels)];out[i]=(unsigned char)cuclip(p+c.amount*r);}
__device__ float rmap(const float* map,int mc,int x,int y,int ch,int w,int c){return map[(y*w+x)*(mc==1?1:c)+(mc==1?0:ch)];}
__device__ float lap_res(const unsigned char* in,int x,int y,int ch,int w,int h,int c){float p=in[pos(x,y,ch,w,c)];return 4*p-in[pos(ci(x-1,w),y,ch,w,c)]-in[pos(ci(x+1,w),y,ch,w,c)]-in[pos(x,ci(y-1,h),ch,w,c)]-in[pos(x,ci(y+1,h),ch,w,c)];}
__device__ float sobel_res(const unsigned char* in,int x,int y,int ch,int w,int h,int c,int direction){float r=0;for(int dy=-1;dy<=1;++dy)for(int dx=-1;dx<=1;++dx){int k=direction==0?((dy==0?2:1)*(dx)):((dx==0?2:1)*(dy));r+=k*in[pos(ci(x+dx,w),ci(y+dy,h),ch,w,c)];}return r;}
__device__ float highpass_res(const unsigned char* in,int x,int y,int ch,int w,int h,int c){float p=in[pos(x,y,ch,w,c)],r=8*p;for(int dy=-1;dy<=1;++dy)for(int dx=-1;dx<=1;++dx)if(dx||dy)r-=in[pos(ci(x+dx,w),ci(y+dy,h),ch,w,c)];return r;}
__global__ void lap_residual_kernel(const unsigned char* in,unsigned char* out,LaplacianResidualInjectionConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float r=c.residual_map?rmap(c.residual_map,c.map_channels,x,y,ch,c.width,c.channels):lap_res(in,x,y,ch,c.width,c.height,c.channels);out[i]=(unsigned char)cuclip(in[i]+c.amount*r);}
__global__ void sobel_residual_kernel(const unsigned char* in,unsigned char* out,SobelResidualInjectionConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float r=c.residual_map?rmap(c.residual_map,c.map_channels,x,y,ch,c.width,c.channels):sobel_res(in,x,y,ch,c.width,c.height,c.channels,c.direction);out[i]=(unsigned char)cuclip(in[i]+c.amount*r);}
__global__ void highpass_residual_kernel(const unsigned char* in,unsigned char* out,HighPassResidualInjectionConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float r=c.residual_map?rmap(c.residual_map,c.map_channels,x,y,ch,c.width,c.channels):highpass_res(in,x,y,ch,c.width,c.height,c.channels);out[i]=(unsigned char)cuclip(in[i]+c.amount*r);}
__global__ void highboost_kernel(const unsigned char* in,unsigned char* out,int w,int h,int c,int r,float sigma,float amount,float gain){int i=blockIdx.x*blockDim.x+threadIdx.x,n=w*h*c;if(i>=n)return;int ch=i%c,x=(i/c)%w,y=i/(w*c);float p=in[i],d=p-gblur(in,w,h,c,x,y,ch,r,sigma,true);out[i]=(unsigned char)cuclip(p+amount*gain*d);}
__global__ void ring_kernel(const unsigned char* in,unsigned char* out,RingingNearStrongEdgesConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float p=in[i],l=in[pos(ci(x-1,c.width),y,ch,c.width,c.channels)],r=in[pos(ci(x+1,c.width),y,ch,c.width,c.channels)],u=in[pos(x,ci(y-1,c.height),ch,c.width,c.channels)],d=in[pos(x,ci(y+1,c.height),ch,c.width,c.channels)],lap=4*p-l-r-u-d;if(fabsf(r-l)+fabsf(d-u)<c.gradient_threshold)lap=0;lap=fminf(c.residual_bound,fmaxf(-c.residual_bound,lap));if((x+y)&1)lap=-lap;out[i]=(unsigned char)cuclip(p+c.amount*lap);}
__global__ void contrast_kernel(const unsigned char* in,unsigned char* out,LocalContrastEnhancementArtifactsConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float sum=0,sq=0;int count=0;for(int dy=-c.radius;dy<=c.radius;++dy)for(int dx=-c.radius;dx<=c.radius;++dx){float q=in[pos(ci(x+dx,c.width),ci(y+dy,c.height),ch,c.width,c.channels)];sum+=q;sq+=q*q;++count;}float mean=sum/count,sigma=sqrtf(fmaxf(0.0f,sq/count-mean*mean)),p=in[i],r=(p-mean)*sigma/(sigma+c.epsilon);out[i]=(unsigned char)cuclip(p+c.amount*r);}
__global__ void lowpass_kernel(const unsigned char* in,unsigned char* out,HighFrequencyAttenuationConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float p=in[i],q=gblur(in,c.width,c.height,c.channels,x,y,ch,c.radius,1.0f,false);out[i]=(unsigned char)cuclip((1-c.amount)*p+c.amount*q);}
__global__ void smear_kernel(const unsigned char* in,unsigned char* out,DetailSmearingConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float p=in[i],q=gblur(in,c.width,c.height,c.channels,x,y,ch,c.radius,c.sigma,c.gaussian);out[i]=(unsigned char)cuclip((1-c.amount)*p+c.amount*q);}
__global__ void bounds_kernel(const unsigned char* in,unsigned char* out,OvershootAndUndershootConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float p=in[i],r=c.amount*(p-gblur(in,c.width,c.height,c.channels,x,y,ch,c.radius,c.sigma,true));r=fminf(c.max_overshoot,fmaxf(-c.max_undershoot,r));out[i]=(unsigned char)cuclip(p+r);}
__device__ unsigned long long imix(unsigned long long x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__device__ float inormal(unsigned long long x){float u=fmaxf(1.0e-7f,((imix(x)>>40)&0xffffffULL)/16777216.0f),v=((imix(x^0xd1b54a32d192ed03ULL)>>40)&0xffffffULL)/16777216.0f;return sqrtf(-2.0f*logf(u))*cosf(6.28318530718f*v);}
__device__ float ilap(const unsigned char* a,int x,int y,int ch,int w,int h,int c){return 4.0f*a[pos(x,y,ch,w,c)]-a[pos(ci(x-1,w),y,ch,w,c)]-a[pos(ci(x+1,w),y,ch,w,c)]-a[pos(x,ci(y-1,h),ch,w,c)]-a[pos(x,ci(y+1,h),ch,w,c)];}
__global__ void extra_kernel(const unsigned char* in,unsigned char* out,int op,GradientPlusLaplacianNoiseConfig g,DeblockingHalosConfig d,DemosaicingEdgeArtifactsConfig m,EdgeDependentQuantizationConfig q,EdgeDependentCompressionErrorConfig e,GradientReversalConfig r,ClippedEdgeRingingConfig z){int i=blockIdx.x*blockDim.x+threadIdx.x,n=g.width*g.height*g.channels;if(i>=n)return;int w=g.width,h=g.height,c=g.channels,ch=i%c,x=(i/c)%w,y=i/(c*w);float p=in[i],gx=(float)in[pos(ci(x+1,w),y,ch,w,c)]-in[pos(ci(x-1,w),y,ch,w,c)],gy=(float)in[pos(x,ci(y+1,h),ch,w,c)]-in[pos(x,ci(y-1,h),ch,w,c)],grad=fabsf(gx)+fabsf(gy);if(op==0){float s=g.sigma*(1+g.gradient_scale*sqrtf(gx*gx+gy*gy)/510.0f+g.laplacian_scale*fabsf(ilap(in,x,y,ch,w,h,c))/1020.0f);out[i]=(unsigned char)cuclip(p+s*inormal(g.seed+(unsigned long long)i));return;}if(op==1){int bx=x%d.block_size,by=y%d.block_size;float rr=0;int nn=0;if(bx<d.radius&&x>0){rr+=p-in[pos(max(0,x-d.radius),y,ch,w,c)];++nn;}if(bx>=d.block_size-d.radius&&x+1<w){rr+=p-in[pos(min(w-1,x+d.radius),y,ch,w,c)];++nn;}if(by<d.radius&&y>0){rr+=p-in[pos(x,max(0,y-d.radius),ch,w,c)];++nn;}if(by>=d.block_size-d.radius&&y+1<h){rr+=p-in[pos(x,min(h-1,y+d.radius),ch,w,c)];++nn;}out[i]=(unsigned char)cuclip(p-d.amount*(nn?rr/nn:0));return;}if(op==2){out[i]=in[i];if(c>=3&&ch==0&&grad>=m.gradient_threshold){float zz=m.strength*grad/2.0f;out[i]=(unsigned char)cuclip(p+(((x+y)&1)?zz:-zz));}if(c>=3&&ch==2&&grad>=m.gradient_threshold){float zz=m.strength*grad/2.0f;out[i]=(unsigned char)cuclip(p+(((x+y)&1)?-zz:zz));}return;}if(op==3){float step=q.step*(1+q.edge_scale*fminf(1.0f,grad/510.0f));out[i]=(unsigned char)cuclip(floorf(p/step+0.5f)*step);return;}if(op==4){int xx=(x/e.block_size)*e.block_size,yy=(y/e.block_size)*e.block_size;float base=in[pos(min(w-1,xx),min(h-1,yy),ch,w,c)],ed=grad/510.0f;out[i]=(unsigned char)cuclip(p+e.strength*(base-p)*(1+e.edge_scale*ed)+0.5f*ed*e.strength*inormal(e.seed+(unsigned long long)i));return;}if(op==5){out[i]=(unsigned char)cuclip(p-(grad>=r.gradient_threshold?r.amount*(gx+gy)/2.0f:0));return;}float rr=0;if(op==6&&grad>=z.gradient_threshold&&(p<=1||p>=254)){rr=fminf(z.residual_bound,fmaxf(-z.residual_bound,z.amount*ilap(in,x,y,ch,w,h,c)));if((x+y)&1)rr=-rr;}out[i]=(unsigned char)cuclip(p+rr);}
void valid(const unsigned char* in,const unsigned char* out,int w,int h,int c){if(!in||!out||w<=0||h<=0||c<=0)throw std::invalid_argument("invalid ISP artifact dimensions");}
void check(cudaError_t e,const char* name){if(e!=cudaSuccess)throw std::runtime_error(std::string(name)+": "+cudaGetErrorString(e));}
void radius(int r,float sigma){if(r<1||r>15||!isfinite(sigma)||sigma<=0)throw std::invalid_argument("invalid ISP filter radius or sigma");}
}}
namespace augmatch {
void edge_oversharpening_u8(const std::uint8_t* i,std::uint8_t* o,const EdgeOversharpeningConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);if(!isfinite(c.amount)||c.amount<0)throw std::invalid_argument("invalid edge oversharpening configuration");edge_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"edge_oversharpening_kernel");}
void unsharp_mask_halos_u8(const std::uint8_t* i,std::uint8_t* o,const UnsharpMaskHalosConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);radius(c.radius,c.sigma);if(!isfinite(c.amount)||c.amount<0)throw std::invalid_argument("invalid unsharp halo configuration");highboost_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c.width,c.height,c.channels,c.radius,c.sigma,c.amount,1);check(cudaGetLastError(),"unsharp_mask_halos_kernel");}
void laplacian_halos_u8(const std::uint8_t* i,std::uint8_t* o,const LaplacianHalosConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);if(!isfinite(c.amount)||c.amount<0)throw std::invalid_argument("invalid Laplacian halo configuration");lap_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"laplacian_halos_kernel");}
void laplacian_residual_injection_u8(const std::uint8_t* i,std::uint8_t* o,const LaplacianResidualInjectionConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);if(!isfinite(c.amount)||c.amount<0||(c.map_channels!=1&&c.map_channels!=c.channels))throw std::invalid_argument("invalid Laplacian residual configuration");lap_residual_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"laplacian_residual_injection_kernel");}
void sobel_residual_injection_u8(const std::uint8_t* i,std::uint8_t* o,const SobelResidualInjectionConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);if(!isfinite(c.amount)||c.amount<0||c.direction<0||c.direction>1||(c.map_channels!=1&&c.map_channels!=c.channels))throw std::invalid_argument("invalid Sobel residual configuration");sobel_residual_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"sobel_residual_injection_kernel");}
void high_pass_residual_injection_u8(const std::uint8_t* i,std::uint8_t* o,const HighPassResidualInjectionConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);if(!isfinite(c.amount)||c.amount<0||(c.map_channels!=1&&c.map_channels!=c.channels))throw std::invalid_argument("invalid high-pass residual configuration");highpass_residual_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"high_pass_residual_injection_kernel");}
void ringing_near_strong_edges_u8(const std::uint8_t* i,std::uint8_t* o,const RingingNearStrongEdgesConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);if(!isfinite(c.amount)||c.amount<0||!isfinite(c.gradient_threshold)||c.gradient_threshold<0||!isfinite(c.residual_bound)||c.residual_bound<0)throw std::invalid_argument("invalid ringing edge configuration");ring_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"ringing_near_strong_edges_kernel");}
void local_contrast_enhancement_artifacts_u8(const std::uint8_t* i,std::uint8_t* o,const LocalContrastEnhancementArtifactsConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);if(c.radius<1||c.radius>15||!isfinite(c.amount)||c.amount<0||!isfinite(c.epsilon)||c.epsilon<=0)throw std::invalid_argument("invalid local contrast configuration");contrast_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"local_contrast_kernel");}
void haloing_from_tone_mapping_u8(const std::uint8_t* i,std::uint8_t* o,const HaloingFromToneMappingConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);radius(c.radius,c.sigma);if(!isfinite(c.amount)||c.amount<0||!isfinite(c.tone_strength)||c.tone_strength<0)throw std::invalid_argument("invalid tone halo configuration");highboost_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c.width,c.height,c.channels,c.radius,c.sigma,c.amount,c.tone_strength);check(cudaGetLastError(),"tone_halo_kernel");}
void local_sharpening_noise_amplification_u8(const std::uint8_t* i,std::uint8_t* o,const LocalSharpeningNoiseAmplificationConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);radius(c.radius,1);if(!isfinite(c.amount)||c.amount<0||!isfinite(c.noise_gain)||c.noise_gain<0)throw std::invalid_argument("invalid local sharpening configuration");highboost_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c.width,c.height,c.channels,c.radius,1,c.amount,c.noise_gain);check(cudaGetLastError(),"local_sharpening_kernel");}
void high_frequency_attenuation_u8(const std::uint8_t* i,std::uint8_t* o,const HighFrequencyAttenuationConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);radius(c.radius,1);if(!isfinite(c.amount)||c.amount<0||c.amount>1)throw std::invalid_argument("invalid high-frequency attenuation configuration");lowpass_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"high_frequency_attenuation_kernel");}
void detail_smearing_u8(const std::uint8_t* i,std::uint8_t* o,const DetailSmearingConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);radius(c.radius,c.sigma);if(!isfinite(c.amount)||c.amount<0||c.amount>1)throw std::invalid_argument("invalid detail smearing configuration");smear_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"detail_smearing_kernel");}
void overshoot_and_undershoot_u8(const std::uint8_t* i,std::uint8_t* o,const OvershootAndUndershootConfig& c,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);radius(c.radius,c.sigma);if(!isfinite(c.amount)||c.amount<0||!isfinite(c.max_overshoot)||c.max_overshoot<0||!isfinite(c.max_undershoot)||c.max_undershoot<0)throw std::invalid_argument("invalid overshoot/undershoot configuration");bounds_kernel<<<(c.width*c.height*c.channels+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"overshoot_undershoot_kernel");}
template<class C> void extra_launch(const std::uint8_t* i,std::uint8_t* o,const C& c,int op,cudaStream_t s){valid(i,o,c.width,c.height,c.channels);if constexpr(std::is_same<C,GradientPlusLaplacianNoiseConfig>::value){if(!isfinite(c.sigma)||c.sigma<0||!isfinite(c.gradient_scale)||c.gradient_scale<0||!isfinite(c.laplacian_scale)||c.laplacian_scale<0)throw std::invalid_argument("invalid gradient-plus-Laplacian noise coefficients");}int n=c.width*c.height*c.channels;GradientPlusLaplacianNoiseConfig g{};DeblockingHalosConfig d{};DemosaicingEdgeArtifactsConfig m{};EdgeDependentQuantizationConfig q{};EdgeDependentCompressionErrorConfig e{};GradientReversalConfig r{};ClippedEdgeRingingConfig z{};if constexpr(std::is_same<C,GradientPlusLaplacianNoiseConfig>::value)g=c;else if constexpr(std::is_same<C,DeblockingHalosConfig>::value)d=c;else if constexpr(std::is_same<C,DemosaicingEdgeArtifactsConfig>::value)m=c;else if constexpr(std::is_same<C,EdgeDependentQuantizationConfig>::value)q=c;else if constexpr(std::is_same<C,EdgeDependentCompressionErrorConfig>::value)e=c;else if constexpr(std::is_same<C,GradientReversalConfig>::value)r=c;else z=c;extra_kernel<<<(n+255)/256,256,0,s>>>(i,o,op,g,d,m,q,e,r,z);check(cudaGetLastError(),"isp_extra_kernel");}
#define EXTRA_CALL(name,config,op) void name(const std::uint8_t* i,std::uint8_t* o,const config& c,cudaStream_t s){extra_launch(i,o,c,op,s);}
EXTRA_CALL(gradient_plus_laplacian_noise_u8,GradientPlusLaplacianNoiseConfig,0)
EXTRA_CALL(deblocking_halos_u8,DeblockingHalosConfig,1)
EXTRA_CALL(demosaicing_edge_artifacts_u8,DemosaicingEdgeArtifactsConfig,2)
EXTRA_CALL(edge_dependent_quantization_u8,EdgeDependentQuantizationConfig,3)
EXTRA_CALL(edge_dependent_compression_error_u8,EdgeDependentCompressionErrorConfig,4)
EXTRA_CALL(gradient_reversal_u8,GradientReversalConfig,5)
EXTRA_CALL(clipped_edge_ringing_u8,ClippedEdgeRingingConfig,6)
#undef EXTRA_CALL
} // namespace augmatch
