#include "augmatch/geometry/mixing.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__host__ __device__ unsigned long long sm(unsigned long long x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__host__ __device__ float unit(unsigned long long x){return (float)((sm(x)>>11)*(1.0/9007199254740992.0));}
__device__ unsigned char cv(float x){return (unsigned char)floorf(fminf(255.f,fmaxf(0.f,x))+.5f);}
__device__ float clip(float x){return fminf(1.f,fmaxf(0.f,x));}
__global__ void mix_k(const unsigned char*a,const unsigned char*b,unsigned char*o,MixUpConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i<n){float w=c.sample_weight?unit(c.seed):c.weight;o[i]=cv((1.f-clip(w))*a[i]+clip(w)*b[i]);}}
__global__ void cut_k(const unsigned char*a,const unsigned char*b,unsigned char*o,CutMixConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int p=i/c.channels,x=p%c.width,y=p/c.width;BoxXYXY r=c.box;if(c.sample_box){int side=max(1,(int)roundf(sqrtf(c.box_fraction*c.width*c.height)));int cx=(int)(unit(c.seed)*c.width),cy=(int)(unit(c.seed+1)*c.height);r={float(cx-side/2),float(cy-side/2),float(cx-side/2+side),float(cy-side/2+side)};}bool take=x>=r.x1&&x<r.x2&&y>=r.y1&&y<r.y2;o[i]=take?b[i]:a[i];}
__global__ void mosaic_k(const ImageSourceU8*s,unsigned char*o,MosaicConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int p=i/c.channels,x=p%c.width,y=p/c.width;int cx=c.center_x<0?(int)(unit(c.seed)*c.width):c.center_x,cy=c.center_y<0?(int)(unit(c.seed+1)*c.height):c.center_y;cx=max(0,min(c.width,cx));cy=max(0,min(c.height,cy));int col=x>=cx,row=y>=cy,q=row*2+col,x0=col?cx:0,y0=row?cy:0,x1=col?c.width:cx,y1=row?c.height:cy;ImageSourceU8 in=s[q];int sx=min(in.width-1,(x-x0)*in.width/max(1,x1-x0)),sy=min(in.height-1,(y-y0)*in.height/max(1,y1-y0));o[i]=in.data[(sy*in.width+sx)*c.channels+i%c.channels];}
__global__ void template_k(const ImageSourceU8*ts,const float*weights,unsigned char*o,ImageSourceU8 in,TemplateTransformConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;float total=c.image_weight,v=c.image_weight*in.data[i];for(int k=0;k<(int)c.template_count;++k){float w=weights?weights[k]:1.f/(float)c.template_count;total+=w;v+=w*ts[k].data[i];}o[i]=cv(v/total);}
__global__ void overlay_k(const ImageSourceU8 base,const OverlayElementU8*es,unsigned char*o,OverlayElementsConfig c){int n=c.width*c.height*c.channels;for(int i=threadIdx.x;i<n;i+=blockDim.x)o[i]=base.data[i];__syncthreads();for(int e=0;e<(int)c.element_count;++e){OverlayElementU8 z=es[e];for(int p=threadIdx.x;p<z.image.width*z.image.height;p+=blockDim.x){int x=p%z.image.width,y=p/z.image.width,dx=z.x+x,dy=z.y+y;if(dx<0||dy<0||dx>=c.width||dy>=c.height)continue;float a=clip(z.alpha)*(z.mask?z.mask[p]/255.f:1.f);int d=(dy*c.width+dx)*c.channels;for(int ch=0;ch<c.channels;++ch)o[d+ch]=cv((1-a)*o[d+ch]+a*z.image.data[p*c.channels+ch]);}__syncthreads();}}
void check(cudaError_t e,const char*n){if(e!=cudaSuccess)throw std::runtime_error(std::string(n)+": "+cudaGetErrorString(e));}
void valid(const ImageSourceU8&s,int w,int h,int c){if(!s.data||s.width<=0||s.height<=0||s.channels!=c||w<=0||h<=0||c<=0)throw std::invalid_argument("invalid mixing source");}
void exact(const ImageSourceU8&s,int w,int h,int c){valid(s,w,h,c);if(s.width!=w||s.height!=h)throw std::invalid_argument("source dimensions do not match output");}
void out(const void*p,int w,int h,int c){if(!p||w<=0||h<=0||c<=0)throw std::invalid_argument("invalid mixing output");}
template<class K,class C>void launch(K k,int n,const C&c,cudaStream_t s,const char*nme){k<<<(n+255)/256,256,0,s>>>(c);check(cudaGetLastError(),nme);}
}
void mixup_u8(const ImageSourceU8&a,const ImageSourceU8&b,std::uint8_t*o,const MixUpConfig&c,cudaStream_t s){exact(a,c.width,c.height,c.channels);exact(b,c.width,c.height,c.channels);out(o,c.width,c.height,c.channels);int n=c.width*c.height*c.channels;mix_k<<<(n+255)/256,256,0,s>>>(a.data,b.data,o,c);check(cudaGetLastError(),"MixUp");}
void cutmix_u8(const ImageSourceU8&a,const ImageSourceU8&b,std::uint8_t*o,const CutMixConfig&c,cudaStream_t s){exact(a,c.width,c.height,c.channels);exact(b,c.width,c.height,c.channels);out(o,c.width,c.height,c.channels);int n=c.width*c.height*c.channels;cut_k<<<(n+255)/256,256,0,s>>>(a.data,b.data,o,c);check(cudaGetLastError(),"CutMix");}
void mosaic_u8(const ImageBatchU8&s,std::uint8_t*o,const MosaicConfig&c,cudaStream_t st){if(!s.sources||s.count<4)throw std::invalid_argument("Mosaic requires four device source records");out(o,c.width,c.height,c.channels);int n=c.width*c.height*c.channels;mosaic_k<<<(n+255)/256,256,0,st>>>(s.sources,o,c);check(cudaGetLastError(),"Mosaic");}
void template_transform_u8(const ImageSourceU8&i,const ImageBatchU8&t,std::uint8_t*o,const TemplateTransformConfig&c,cudaStream_t st){exact(i,c.width,c.height,c.channels);if(t.count!=c.template_count|| (t.count&&!t.sources))throw std::invalid_argument("invalid TemplateTransform records");out(o,c.width,c.height,c.channels);int n=c.width*c.height*c.channels;template_k<<<(n+255)/256,256,0,st>>>(t.sources,c.template_weights,o,i,c);check(cudaGetLastError(),"TemplateTransform");}
void overlay_elements_u8(const ImageSourceU8&b,std::uint8_t*o,const OverlayElementsConfig&c,cudaStream_t st){valid(b,c.width,c.height,c.channels);if(c.element_count&&!c.elements)throw std::invalid_argument("invalid OverlayElements records");out(o,c.width,c.height,c.channels);int n=c.width*c.height*c.channels;overlay_k<<<1,256,0,st>>>(b,c.elements,o,c);check(cudaGetLastError(),"OverlayElements");}
void mixup_targets(const ReadOnlyMixingTargets&a,const ReadOnlyMixingTargets&b,float w,MixingTargets&o){if(w<0||w>1||((a.count+b.count)&&!o.boxes))throw std::invalid_argument("invalid target contract");o.count=0;for(auto in:{a,b})for(std::size_t i=0;i<in.count;++i){if(o.count>=o.capacity||!in.boxes)throw std::invalid_argument("target capacity");o.boxes[o.count]=in.boxes[i];if(o.labels)o.labels[o.count]=in.labels?in.labels[i]:0;++o.count;}}
void cutmix_targets(const ReadOnlyMixingTargets&a,const ReadOnlyMixingTargets&b,const CutMixConfig&c,MixingTargets&o){if((a.count+b.count)&&!o.boxes)throw std::invalid_argument("invalid target contract");o.count=0;for(std::size_t i=0;i<a.count;++i){if(o.count>=o.capacity)throw std::invalid_argument("target capacity");o.boxes[o.count]=a.boxes[i];if(o.labels)o.labels[o.count]=a.labels?a.labels[i]:0;++o.count;}BoxXYXY r=c.box;for(std::size_t i=0;i<b.count;++i){BoxXYXY x=b.boxes[i];x.x1=fmaxf(x.x1,r.x1);x.y1=fmaxf(x.y1,r.y1);x.x2=fminf(x.x2,r.x2);x.y2=fminf(x.y2,r.y2);if(x.x2>x.x1&&x.y2>x.y1){if(o.count>=o.capacity)throw std::invalid_argument("target capacity");o.boxes[o.count]=x;if(o.labels)o.labels[o.count]=b.labels?b.labels[i]:0;++o.count;}}}
}
