#include "augmatch/sensor/noise.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ unsigned long long mix(unsigned long long x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__device__ float uni(unsigned long long x){return (float)((mix(x)>>11)*(1.0/9007199254740992.0));}
__device__ float norm(unsigned long long x){float a=fmaxf(uni(x),1.0e-7f);return sqrtf(-2.0f*logf(a))*cosf(6.28318530718f*uni(x^0xd1b54a32d192ed03ULL));}
__device__ unsigned long long key(unsigned long long s,int x,int y,int c,unsigned long long k){return s^(unsigned long long)x*0x632be59bd9b4e019ULL^(unsigned long long)y*0x8cb92baa2f2f6f7dULL^(unsigned long long)c*0x9e3779b97f4a7c15ULL^k;}
__device__ float lum(const float* p,int w,int h,int c,int x,int y){x=max(0,min(x,w-1));y=max(0,min(y,h-1));const float* q=p+(y*w+x)*c;if(c==1)return q[0];return .2126f*q[0]+.7152f*q[min(1,c-1)]+.0722f*q[min(2,c-1)];}
__device__ float shot_pois(float lambda,unsigned long long seed){
  if(lambda<=0.0f)return 0.0f;
  if(lambda<64.0f){
    const float u=uni(seed^0x53484f545f554e49ULL);
    float probability=expf(-lambda),cdf=probability;
    int count=0;
    while(u>cdf&&count<512){++count;probability*=lambda/(float)count;cdf+=probability;}
    return (float)count;
  }
  return floorf(fmaxf(0.0f,lambda+sqrtf(lambda)*norm(seed^0x53484f545f4e4f52ULL))+0.5f);
}
__global__ void prnu_kernel(const float* in,float* out,PixelResponseNonUniformityConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float gain=c.gain_map?c.gain_map[i]:1.0f+c.stddev*norm(key(c.seed,x,y,ch,0x50524e555f474149ULL));out[i]=in[i]*gain;}
__global__ void fpn_kernel(const float* in,float* out,FixedPatternOffsetNoiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float offset=c.offset_map?c.offset_map[i]:c.stddev*norm(key(c.seed,x,y,ch,0x46504e5f4f464653ULL));out[i]=in[i]+offset;}
__global__ void iso_noise_kernel(const unsigned char* in,unsigned char* out,ISONoiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);const float w0=.2126f,w1=.7152f,w2=.0722f;float zsum=0.0f;int limit=c.channels<3?c.channels:3;if(limit>0)zsum+=w0*norm(key(c.seed,x,y,0,0x49534f5f4348524fULL));if(limit>1)zsum+=w1*norm(key(c.seed,x,y,1,0x49534f5f4348524fULL));if(limit>2)zsum+=w2*norm(key(c.seed,x,y,2,0x49534f5f4348524fULL));float center=c.channels>=3?zsum:0.0f;float luma=norm(key(c.seed,x,y,0,0x49534f5f4c554d41ULL));float chroma=c.channels>=3?(norm(key(c.seed,x,y,ch,0x49534f5f4348524fULL))-center):0.0f;float gain=c.iso/c.base_iso*c.analog_gain;float value=((float)in[i]/255.0f)*c.digital_gain+c.gaussian_stddev*gain*luma+c.chroma_stddev*gain*chroma;out[i]=(unsigned char)floorf(fminf(1.0f,fmaxf(0.0f,value))*255.0f+0.5f);}
__global__ void shot_noise_kernel(const unsigned char* in,unsigned char* out,ShotNoiseConfig c){
  int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;
  int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);
  unsigned long long k=key(c.seed,x,y,ch,0x53484f545f4e4f49ULL);
  float lambda=((float)in[i]/255.0f)*c.gain*c.scale;
  float value=shot_pois(lambda,k)/c.scale;
  out[i]=(unsigned char)floorf(fminf(1.0f,fmaxf(0.0f,value))*255.0f+0.5f);
}
__global__ void sensor_kernel(const float* in,float* out,SensorNoiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);auto k=key(c.seed,x,y,ch,0x243f6a8885a308d3ULL);float src=fmaxf(0.0f,in[i]);float prnu=1+c.prnu_stddev*norm(k^0x082efa98ec4e6c89ULL);float lambda=fmaxf(0.0f,src*c.exposure*prnu*c.electrons_per_unit);float shot=lambda>0?lambda+sqrtf(lambda)*norm(k^0x452821e638d01377ULL):0;float dead=uni(k^0x13198a2e03707344ULL)<c.dead_pixel_probability;float hot=uni(k^0xa4093822299f31d0ULL)<c.hot_pixel_probability;float stuck=uni(k^0x7f4a7c159e3779b9ULL)<c.stuck_pixel_probability;float fpn=c.fpn_stddev*norm(key(c.seed,x,y,ch,0x6a09e667f3bcc909ULL));float e=stuck?c.stuck_pixel_value*c.electrons_per_unit:(dead?0:shot+c.read_noise_electrons*norm(k^0xc0ac29b7c97c50ddULL)+c.amplifier_noise_electrons*norm(k^0x3c6ef372fe94f82bULL)+c.reset_noise_electrons*norm(k^0xbb67ae8584caa73bULL)+c.row_noise_electrons*norm(key(c.seed,0,y,ch,0xbe5466cf34e90c6cULL))+c.column_noise_electrons*norm(key(c.seed,x,0,ch,0x9e3779b97f4a7c15ULL))+c.correlated_read_noise_electrons*(norm(key(c.seed,0,y,0,0x510e527fade682d1ULL))+norm(key(c.seed,x,0,1,0x1f83d9abfb41bd6bULL)))*0.5f+c.dark_current_electrons*expf(c.dark_current_temp_coefficient*(c.temperature_celsius-c.reference_temperature_celsius))+c.dark_frame_offset_electrons);if(hot)e+=c.hot_pixel_electrons;float v=fminf(c.white_level,fmaxf(c.black_level,c.black_level+e/c.electrons_per_unit));float q=(v-c.black_level)/(c.white_level-c.black_level);out[i]=rintf(q*(c.adc_levels-1))/(c.adc_levels-1);}
__global__ void edge_kernel(const float* in,float* out,EdgeDependentNoiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float gx=lum(in,c.width,c.height,c.channels,x+1,y-1)+2*lum(in,c.width,c.height,c.channels,x+1,y)+lum(in,c.width,c.height,c.channels,x+1,y+1)-lum(in,c.width,c.height,c.channels,x-1,y-1)-2*lum(in,c.width,c.height,c.channels,x-1,y)-lum(in,c.width,c.height,c.channels,x-1,y+1);float gy=lum(in,c.width,c.height,c.channels,x-1,y+1)+2*lum(in,c.width,c.height,c.channels,x,y+1)+lum(in,c.width,c.height,c.channels,x+1,y+1)-lum(in,c.width,c.height,c.channels,x-1,y-1)-2*lum(in,c.width,c.height,c.channels,x,y-1)-lum(in,c.width,c.height,c.channels,x+1,y-1);float l=fabsf(lum(in,c.width,c.height,c.channels,x-1,y)+lum(in,c.width,c.height,c.channels,x+1,y)+lum(in,c.width,c.height,c.channels,x,y-1)+lum(in,c.width,c.height,c.channels,x,y+1)-4*lum(in,c.width,c.height,c.channels,x,y));float s=c.base_stddev+c.gradient_scale*.125f*sqrtf(gx*gx+gy*gy)+c.laplacian_scale*l;out[i]=in[i]+s*norm(key(c.seed,x,y,ch,0xdeadbeefULL));}
__global__ void row_column_kernel(const float* in,float* out,RowColumnCorrelatedNoiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float row=c.row_map?c.row_map[y*c.channels+ch]:c.row_stddev*norm(key(c.seed,0,y,ch,0x524f575f4e4f4953ULL));float col=c.column_map?c.column_map[x*c.channels+ch]:c.column_stddev*norm(key(c.seed,x,0,ch,0x434f4c5f4e4f4953ULL));out[i]=fmaxf(c.clip_min,fminf(c.clip_max,in[i]+row+col));}
__global__ void clustered_kernel(const float* in,float* out,ClusteredDefectivePixelsConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float value=in[i];if(c.defects){for(unsigned long long d=0;d<c.defect_count;++d){const ClusteredDefect q=c.defects[d];int dx=x-q.center_x,dy=y-q.center_y;if(q.radius<0||(q.channel!=-1&&q.channel!=ch)||dx*dx+dy*dy>q.radius*q.radius)continue;if(q.kind==ClusteredDefectKind::Dead)value=0.0f;else if(q.kind==ClusteredDefectKind::Stuck)value=q.value;else if(q.kind==ClusteredDefectKind::Hot)value+=q.value;}}else for(int d=0;d<c.cluster_count;++d){unsigned long long k=key(c.seed,d,0,0,0x434c55535445525fULL);int cx=min(c.width-1,(int)(uni(k)*c.width)),cy=min(c.height-1,(int)(uni(k^0x9e3779b97f4a7c15ULL)*c.height));int dx=x-cx,dy=y-cy;if(dx*dx+dy*dy>c.cluster_radius*c.cluster_radius)continue;float kind=uni(k^0x243f6a8885a308d3ULL);if(kind<1.0f/3.0f)value+=c.hot_value;else if(kind<2.0f/3.0f)value=0.0f;else value=c.stuck_value;}out[i]=fminf(1.0f,fmaxf(0.0f,value));}
__device__ float adc_width(const float* lut,int channel,int code,int levels,float stddev,unsigned long long seed){const float value=lut?lut[channel*levels+code]:1.0f+stddev*norm(key(seed,code,0,channel,0x444e4c5f57494454ULL));return value;}
__global__ void adc_dnl_kernel(const float* in,float* out,AdcDifferentialNonLinearityConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels;float sample=fminf(1.0f,fmaxf(0.0f,in[i]));if(sample>=1.0f){out[i]=1.0f;return;}float total=0.0f;for(int code=0;code<c.levels;++code){float width=adc_width(c.lut,ch,code,c.levels,c.stddev,c.seed);total+=width*(code==0||code==c.levels-1?0.5f:1.0f);}float cumulative=0.0f;int code=0;for(;code<c.levels-1;++code){float width=adc_width(c.lut,ch,code,c.levels,c.stddev,c.seed);cumulative+=width*(code==0?0.5f:1.0f);if(sample*total<cumulative)break;}out[i]=(float)code/(float)(c.levels-1);}
__global__ void adc_inl_kernel(const float* in,float* out,AdcIntegralNonLinearityConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels;float sample=fminf(1.0f,fmaxf(0.0f,in[i]));int code=min(c.levels-1,max(0,(int)floorf(sample*(c.levels-1)+0.5f)));float offset=c.lut?c.lut[ch*c.levels+code]:c.stddev*norm(key(c.seed,code,0,ch,0x494e4c5f4f464653ULL));out[i]=fminf(1.0f,fmaxf(0.0f,((float)code+offset)/(float)(c.levels-1)));}
__global__ void well_capacity_kernel(const float* in,float* out,SensorWellCapacityVariationConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float capacity=c.capacity_map?c.capacity_map[i]:fmaxf(0.0f,1.0f+c.stddev*norm(key(c.seed,x,y,ch,0x57454c4c5f434150ULL)));out[i]=fminf(1.0f,fmaxf(0.0f,fminf(capacity,in[i])));}
__global__ void blooming_vertical_smear_kernel(const float* in,float* out,BloomingVerticalSmearConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float value=in[i];if(c.bright_pixels){for(unsigned long long p=0;p<c.bright_pixel_count;++p){const BrightPixel q=c.bright_pixels[p];if(q.x!=x||(q.channel!=-1&&q.channel!=ch)||q.y>y)continue;value+=fmaxf(0.0f,q.value-c.bright_threshold)*c.smear_strength*powf(c.smear_decay,(float)(y-q.y));}}else for(int sy=0;sy<=y;++sy){const float source=in[(sy*c.width+x)*c.channels+ch];if(source>c.bright_threshold)value+=(source-c.bright_threshold)*c.smear_strength*powf(c.smear_decay,(float)(y-sy));}if(c.column_smear_map)value+=c.column_smear_map[x*c.channels+ch]*c.smear_strength*powf(c.smear_decay,(float)y);out[i]=fminf(c.clip_max,fmaxf(c.clip_min,value));}
__global__ void sensor_dust_opaque_mask_kernel(const float* in,float* out,SensorDustOpaqueMaskConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);if(!c.mask){out[i]=in[i];return;}if(c.mask[y*c.width+x]==0){out[i]=in[i];return;}int x0=max(0,x-c.blur_radius),x1=min(c.width-1,x+c.blur_radius),y0=max(0,y-c.blur_radius),y1=min(c.height-1,y+c.blur_radius);float sum=0.0f;int count=0;for(int yy=y0;yy<=y1;++yy)for(int xx=x0;xx<=x1;++xx)if(c.mask[yy*c.width+xx]==0){sum+=in[(yy*c.width+xx)*c.channels+ch];++count;}float value=count?sum/(float)count:c.fill;out[i]=fminf(1.0f,fmaxf(0.0f,value));}
__device__ float optical_map(const float* p,int mc,int w,int x,int y,int ch){return !p?1.0f:(mc==1?p[y*w+x]:p[(y*w+x)*mc+ch]);}
__device__ float optical_radial(LensVignettingConfig c,int x,int y){float aw=fmaxf(1.0f,(float)(c.width-1)),ah=fmaxf(1.0f,(float)(c.height-1));float nx=((float)x/aw-c.center_x)/c.radius_x,ny=((float)y/ah-c.center_y)/c.radius_y,r2=nx*nx+ny*ny;return c.c0+c.c1*r2+c.c2*r2*r2+c.c3*r2*r2*r2;}
__global__ void lens_vignetting_kernel(const float* in,float* out,LensVignettingConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float v=in[i]*optical_radial(c,x,y)*optical_map(c.map,c.map_channels,c.width,x,y,ch);out[i]=fminf(c.clip_max,fmaxf(c.clip_min,v));}
__global__ void color_vignetting_kernel(const float* in,float* out,ColorDependentVignettingConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float g=optical_radial(c,x,y);if(c.coefficients){float aw=fmaxf(1.0f,(float)(c.width-1)),ah=fmaxf(1.0f,(float)(c.height-1)),nx=((float)x/aw-c.center_x)/c.radius_x,ny=((float)y/ah-c.center_y)/c.radius_y,r2=nx*nx+ny*ny;const float* p=c.coefficients+ch*4;g=p[0]+p[1]*r2+p[2]*r2*r2+p[3]*r2*r2*r2;}float v=in[i]*g*optical_map(c.map,c.map_channels,c.width,x,y,ch);out[i]=fminf(c.clip_max,fmaxf(c.clip_min,v));}
__global__ void shading_kernel(const float* in,float* out,LensShadingConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float v=in[i]*c.gain*optical_map(c.map,c.map_channels,c.width,x,y,ch);out[i]=fminf(c.clip_max,fmaxf(c.clip_min,v));}
__global__ void illumination_kernel(const float* in,float* out,UnevenIlluminationConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float v=in[i]*(c.base_gain*optical_map(c.map,c.map_channels,c.width,x,y,ch))+c.offset;out[i]=fminf(c.clip_max,fmaxf(c.clip_min,v));}
__global__ void dust_shadow_kernel(const float* in,float* out,SensorLensDustShadowsConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float op=c.shadow_map?fminf(1.0f,fmaxf(0.0f,c.shadow_map[y*c.width+x])):0.0f;float v=in[i]*(1.0f-c.strength*op);out[i]=fminf(c.clip_max,fmaxf(c.clip_min,v));}
__device__ float effect_map_cuda(const float* map,int mc,int w,int x,int y,int ch){return !map?1.0f:(mc==1?map[y*w+x]:map[(y*w+x)*mc+ch]);}
__device__ float effect_clip_cuda(float v,float lo,float hi){return fminf(hi,fmaxf(lo,v));}
__global__ void flare_kernel(const float* in,float* out,FlareConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float a=0.0f;for(unsigned long long j=0;j<c.source_count;++j){FlareSource s=c.sources[j];if(s.channel!=-1&&s.channel!=ch)continue;float dx=x-s.x,dy=y-s.y;if(dx*dx+dy*dy<=s.radius*s.radius)a+=c.opacity*s.intensity;}for(unsigned long long j=0;j<c.halo_count;++j){FlareHalo h=c.halos[j];float hx=h.x,hy=h.y;if(h.source_index>=0&&h.source_index<c.source_count){hx=c.sources[h.source_index].x;hy=c.sources[h.source_index].y;}if(h.radius>0.0f){float d=hypotf(x-hx,y-hy);if(d<h.radius)a+=c.opacity*h.intensity*(1.0f-d/h.radius);}}float b=fminf(1.0f,fmaxf(0.0f,a*effect_map_cuda(c.map,c.map_channels,c.width,x,y,ch)));out[i]=effect_clip_cuda((1.0f-b)*in[i]+b,c.clip_min,c.clip_max);}
__global__ void ghosting_kernel(const float* in,float* out,GhostingConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float value=in[i];for(unsigned long long j=0;j<c.ghost_count;++j){Ghost g=c.ghosts[j];int sx=max(0,min(c.width-1,(int)floorf(x-g.dx+0.5f))),sy=max(0,min(c.height-1,(int)floorf(y-g.dy+0.5f)));float b=fminf(1.0f,fmaxf(0.0f,c.opacity*g.alpha*effect_map_cuda(c.map,c.map_channels,c.width,x,y,ch)));value=(1.0f-b)*value+b*effect_clip_cuda(in[(sy*c.width+sx)*c.channels+ch]*g.scale,c.clip_min,c.clip_max);}out[i]=effect_clip_cuda(value,c.clip_min,c.clip_max);}
__global__ void glare_kernel(const float* in,float* out,VeilingGlareConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels),base=(y*c.width+x)*c.channels;float lum=0.0f;for(int k=0;k<c.channels;++k)lum=fmaxf(lum,in[base+k]);float v=in[i]+c.strength*lum*effect_map_cuda(c.map,c.map_channels,c.width,x,y,ch);out[i]=effect_clip_cuda(v,c.clip_min,c.clip_max);}
__global__ void bloom_kernel(const float* in,float* out,BloomConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float sum=0.0f;for(int yy=max(0,y-c.radius);yy<=min(c.height-1,y+c.radius);++yy)for(int xx=max(0,x-c.radius);xx<=min(c.width-1,x+c.radius);++xx)sum=fmaxf(0.0f,sum+fmaxf(0.0f,in[(yy*c.width+xx)*c.channels+ch]-c.threshold));float area=(float)((2*c.radius+1)*(2*c.radius+1));float v=in[i]+c.strength*sum/area*effect_map_cuda(c.map,c.map_channels,c.width,x,y,ch);out[i]=effect_clip_cuda(v,c.clip_min,c.clip_max);}
void check(cudaError_t e,const char* p){if(e!=cudaSuccess)throw std::runtime_error(std::string(p)+": "+cudaGetErrorString(e));}
void valid(int w,int h,int c){if(w<=0||h<=0||c<=0)throw std::invalid_argument("invalid noise dimensions");}
}
void pixel_response_non_uniformity_f32(const float* in,float* out,const PixelResponseNonUniformityConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.stddev)||c.stddev<0.0f)throw std::invalid_argument("invalid PRNU configuration");int n=c.width*c.height*c.channels;prnu_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"prnu_kernel");}
void fixed_pattern_offset_noise_f32(const float* in,float* out,const FixedPatternOffsetNoiseConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.stddev)||c.stddev<0.0f)throw std::invalid_argument("invalid FPN configuration");int n=c.width*c.height*c.channels;fpn_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"fpn_kernel");}
void iso_noise_u8(const std::uint8_t* in,std::uint8_t* out,const ISONoiseConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.iso)||!isfinite(c.base_iso)||!isfinite(c.analog_gain)||!isfinite(c.digital_gain)||!isfinite(c.gaussian_stddev)||!isfinite(c.chroma_stddev)||c.iso<=0||c.base_iso<=0||c.analog_gain<=0||c.digital_gain<0||c.gaussian_stddev<0||c.chroma_stddev<0)throw std::invalid_argument("invalid ISO noise configuration");int n=c.width*c.height*c.channels;iso_noise_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"iso_noise_kernel");}
void sensor_noise_f32(const float* in,float* out,const SensorNoiseConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||c.electrons_per_unit<=0||c.amplifier_noise_electrons<0||c.reset_noise_electrons<0||c.adc_levels<2||c.white_level<=c.black_level||c.stuck_pixel_probability<0||c.stuck_pixel_probability>1||c.fpn_stddev<0||!isfinite(c.temperature_celsius)||!isfinite(c.reference_temperature_celsius)||!isfinite(c.dark_current_temp_coefficient))throw std::invalid_argument("invalid sensor noise configuration");int n=c.width*c.height*c.channels;sensor_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"sensor_kernel");}
void shot_noise_u8(const std::uint8_t* in,std::uint8_t* out,const ShotNoiseConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.gain)||!isfinite(c.scale)||!isfinite(c.gain*c.scale)||c.gain<0.0f||c.scale<=0.0f)throw std::invalid_argument("invalid shot noise configuration");int n=c.width*c.height*c.channels;shot_noise_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"shot_noise_kernel");}
void edge_dependent_noise_f32(const float* in,float* out,const EdgeDependentNoiseConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||c.base_stddev<0||c.gradient_scale<0||c.laplacian_scale<0)throw std::invalid_argument("invalid edge noise configuration");int n=c.width*c.height*c.channels;edge_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"edge_kernel");}
void row_column_correlated_noise_f32(const float* in,float* out,const RowColumnCorrelatedNoiseConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.row_stddev)||!isfinite(c.column_stddev)||c.row_stddev<0||c.column_stddev<0||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min)throw std::invalid_argument("invalid row-column noise configuration");int n=c.width*c.height*c.channels;row_column_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"row_column_kernel");}
void clustered_defective_pixels_f32(const float* in,float* out,const ClusteredDefectivePixelsConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||(!c.defects&&c.defect_count)||c.cluster_count<0||c.cluster_radius<0||c.defect_count>100000||c.cluster_count>100000||!isfinite(c.hot_value)||!isfinite(c.stuck_value))throw std::invalid_argument("invalid clustered defect configuration");int n=c.width*c.height*c.channels;clustered_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"clustered_kernel");}
void adc_differential_non_linearity_f32(const float* in,float* out,const AdcDifferentialNonLinearityConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||c.levels<2||c.levels>65536||!isfinite(c.stddev)||c.stddev<0.0f)throw std::invalid_argument("invalid ADC DNL configuration");int n=c.width*c.height*c.channels;adc_dnl_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"adc_dnl_kernel");}
void adc_integral_non_linearity_f32(const float* in,float* out,const AdcIntegralNonLinearityConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||c.levels<2||c.levels>65536||!isfinite(c.stddev)||c.stddev<0.0f)throw std::invalid_argument("invalid ADC INL configuration");int n=c.width*c.height*c.channels;adc_inl_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"adc_inl_kernel");}
void sensor_well_capacity_variation_f32(const float* in,float* out,const SensorWellCapacityVariationConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.stddev)||c.stddev<0.0f)throw std::invalid_argument("invalid well-capacity configuration");int n=c.width*c.height*c.channels;well_capacity_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"well_capacity_kernel");}
void blooming_vertical_smear_f32(const float* in,float* out,const BloomingVerticalSmearConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.bright_threshold)||!isfinite(c.smear_strength)||!isfinite(c.smear_decay)||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.smear_strength<0.0f||c.smear_decay<0.0f||c.smear_decay>1.0f||c.clip_max<c.clip_min||c.bright_pixel_count>1000000||(!c.bright_pixels&&c.bright_pixel_count))throw std::invalid_argument("invalid blooming/vertical-smear configuration");int n=c.width*c.height*c.channels;blooming_vertical_smear_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"blooming_vertical_smear_kernel");}
void sensor_dust_opaque_mask_f32(const float* in,float* out,const SensorDustOpaqueMaskConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.fill)||c.blur_radius<0)throw std::invalid_argument("invalid sensor dust mask configuration");int n=c.width*c.height*c.channels;sensor_dust_opaque_mask_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"sensor_dust_opaque_mask_kernel");}
void lens_vignetting_f32(const float* in,float* out,const LensVignettingConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.center_x)||!isfinite(c.center_y)||!isfinite(c.radius_x)||!isfinite(c.radius_y)||!isfinite(c.c0)||!isfinite(c.c1)||!isfinite(c.c2)||!isfinite(c.c3)||c.radius_x<=0||c.radius_y<=0||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||c.map_channels!=1&&c.map_channels!=c.channels)throw std::invalid_argument("invalid lens vignetting configuration");int n=c.width*c.height*c.channels;lens_vignetting_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"lens_vignetting_kernel");}
void color_dependent_vignetting_f32(const float* in,float* out,const ColorDependentVignettingConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.center_x)||!isfinite(c.center_y)||!isfinite(c.radius_x)||!isfinite(c.radius_y)||!isfinite(c.c0)||!isfinite(c.c1)||!isfinite(c.c2)||!isfinite(c.c3)||c.radius_x<=0||c.radius_y<=0||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||c.map_channels!=1&&c.map_channels!=c.channels)throw std::invalid_argument("invalid color vignetting configuration");int n=c.width*c.height*c.channels;color_vignetting_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"color_vignetting_kernel");}
void optical_falloff_f32(const float* in,float* out,const OpticalFalloffConfig& c,cudaStream_t s){lens_vignetting_f32(in,out,c,s);}
void lens_shading_f32(const float* in,float* out,const LensShadingConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.gain)||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||c.map_channels!=1&&c.map_channels!=c.channels)throw std::invalid_argument("invalid lens shading configuration");int n=c.width*c.height*c.channels;shading_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"shading_kernel");}
void uneven_illumination_f32(const float* in,float* out,const UnevenIlluminationConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.base_gain)||!isfinite(c.offset)||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||c.map_channels!=1&&c.map_channels!=c.channels)throw std::invalid_argument("invalid uneven illumination configuration");int n=c.width*c.height*c.channels;illumination_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"illumination_kernel");}
void sensor_lens_dust_shadows_f32(const float* in,float* out,const SensorLensDustShadowsConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.strength)||c.strength<0||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min)throw std::invalid_argument("invalid dust shadow configuration");int n=c.width*c.height*c.channels;dust_shadow_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"dust_shadow_kernel");}
void flare_f32(const float* in,float* out,const FlareConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.opacity)||c.opacity<0||c.opacity>1||c.source_count>1000000||c.halo_count>1000000||(!c.sources&&c.source_count)||(!c.halos&&c.halo_count)||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||(c.map_channels!=1&&c.map_channels!=c.channels))throw std::invalid_argument("invalid flare configuration");int n=c.width*c.height*c.channels;flare_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"flare_kernel");}
void ghosting_f32(const float* in,float* out,const GhostingConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.opacity)||c.opacity<0||c.opacity>1||c.ghost_count>1000000||(!c.ghosts&&c.ghost_count)||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||(c.map_channels!=1&&c.map_channels!=c.channels))throw std::invalid_argument("invalid ghosting configuration");int n=c.width*c.height*c.channels;ghosting_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"ghosting_kernel");}
void veiling_glare_f32(const float* in,float* out,const VeilingGlareConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||!isfinite(c.strength)||c.strength<0||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||(c.map_channels!=1&&c.map_channels!=c.channels))throw std::invalid_argument("invalid veiling glare configuration");int n=c.width*c.height*c.channels;glare_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"glare_kernel");}
void bloom_f32(const float* in,float* out,const BloomConfig& c,cudaStream_t s){valid(c.width,c.height,c.channels);if(!in||!out||c.radius<0||!isfinite(c.threshold)||!isfinite(c.strength)||c.threshold<0||c.strength<0||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min||(c.map_channels!=1&&c.map_channels!=c.channels))throw std::invalid_argument("invalid bloom configuration");int n=c.width*c.height*c.channels;bloom_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"bloom_kernel");}
}
