#include "augmatch/noise.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ unsigned long long mix(unsigned long long x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__device__ float unit(unsigned long long x){return (float)(mix(x)>>40)/16777216.0f;}
__device__ unsigned long long key(unsigned long long s,int t,int y,int x,int ch,unsigned long long tag){return s^(unsigned long long)t*0x632be59bd9b4e019ULL^(unsigned long long)y*0x9e3779b97f4a7c15ULL^(unsigned long long)x*0x8cb92baa2f2f6f7dULL^(unsigned long long)ch*0xbf58476d1ce4e5b9ULL^tag;}
__device__ float clip(float x,float lo,float hi){return fmaxf(lo,fminf(hi,x));}
__device__ int clampi(int x,int n){return max(0,min(n-1,x));}
__device__ size_t pix(int w,int c,int y,int x,int ch){return ((size_t)y*w+x)*c+ch;}
__device__ WaterDroplet droplet(const WaterDropletsOnLensConfig& c,int i){if(c.droplets)return c.droplets[i];unsigned long long b=(unsigned long long)i*4;WaterDroplet d;d.x=unit(c.seed+b)*c.width;d.y=unit(c.seed+b+1)*c.height;d.radius=c.radius_min+(c.radius_max-c.radius_min)*unit(c.seed+b+2);d.opacity=1;return d;}
__global__ void rts_kernel(const float* in,float* out,RandomTelegraphSignalNoiseConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)c.height*c.width*c.channels;if(i>=n)return;int y=i/(c.width*c.channels),x=(i/c.channels)%c.width,ch=i%c.channels;bool state=c.state_map?c.state_map[i]!=0:((c.initial_state!=0)^(unit(key(c.seed,0,y,x,ch,0x5254535f53544154ULL))<c.transition_probability));out[i]=clip(in[i]+(state?c.high_offset:c.low_offset),c.clip_min,c.clip_max);}
__global__ void ifc_kernel(const float* in,float* out,InterFrameCompressionNoiseConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)c.frames*c.height*c.width*c.channels;if(i>=n)return;size_t plane=(size_t)c.height*c.width*c.channels,base=i/plane,p=i%plane;if(base==0){out[i]=in[i];return;}int ch=p%c.channels,x=(p/c.channels)%c.width,y=(p/c.channels/c.width)%c.height;float step=c.records?c.records[base].quantization_step:c.quantization_step,gain=c.records?c.records[base].strength:c.strength;step=fmaxf(0,step);float r=in[i]-in[i-plane],q=step>0?nearbyintf(r/step)*step:r;float noise=(unit(key(c.seed,(int)base,y,x,ch,0x4946525f4e4f4953ULL))-.5f)*step*.1f;out[i]=clip(in[i]+gain*(q-r+noise),c.clip_min,c.clip_max);}
__global__ void gop_kernel(const float* in,float* out,GopKeyframeArtifactsConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)c.frames*c.height*c.width*c.channels;if(i>=n)return;size_t plane=(size_t)c.height*c.width*c.channels,t=i/plane,p=i%plane;int ch=p%c.channels,x=(p/c.channels)%c.width,y=(p/c.channels/c.width)%c.height;bool k=c.records?c.records[t].keyframe!=0:c.keyframe_mask?c.keyframe_mask[t]!=0:(t%c.gop_size==0);float gain=c.records?fmaxf(0,c.records[t].strength):(k?c.keyframe_strength:c.interframe_strength),v=in[i];if(k){float q=nearbyintf(v/.05f)*.05f;v+=gain*(q-v);}else{float r=in[i]-in[i-plane],q=nearbyintf(r/.05f)*.05f;v+=gain*(q-r+(unit(key(c.seed,(int)t,y,x,ch,0x474f505f41525446ULL))-.5f)*.005f);}out[i]=clip(v,c.clip_min,c.clip_max);}
__global__ void motion_kernel(const float* in,float* out,BlockMotionEstimationArtifactsConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)c.frames*c.height*c.width*c.channels;if(i>=n)return;size_t plane=(size_t)c.height*c.width*c.channels,t=i/plane,p=i%plane;if(t==0){out[i]=in[i];return;}int ch=p%c.channels,x=(p/c.channels)%c.width,y=(p/c.channels/c.width)%c.height,bx=(c.width+c.block_width-1)/c.block_width,by=(c.height+c.block_height-1)/c.block_height,bi=y/c.block_height,bj=x/c.block_width;size_t ri=t*(size_t)bx*by+(size_t)bi*bx+bj;MotionVectorRecord v=c.vectors?c.vectors[ri]:MotionVectorRecord{};if(!c.vectors){v.dx=(int)floorf(unit(key(c.seed,(int)t,bi,bj,0,0x4d564543544f5253ULL))*5)-2;v.dy=(int)floorf(unit(key(c.seed,(int)t,bi,bj,1,0x4d564543544f5253ULL))*5)-2;v.strength=1;}int sx=clampi(x+v.dx,c.width),sy=clampi(y+v.dy,c.height);float a=clip(c.strength*v.strength,0,1);out[i]=clip((1-a)*in[i]+a*in[(t-1)*plane+pix(c.width,c.channels,sy,sx,ch)],c.clip_min,c.clip_max);}
__global__ void droplets_kernel(const float* in,float* out,WaterDropletsOnLensConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)c.height*c.width*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=(i/c.channels/c.width)%c.height;float value=in[i];for(int d=0;d<c.droplet_count;++d){WaterDroplet z=droplet(c,d);float dx=x+.5f-z.x,dy=y+.5f-z.y;if(dx*dx+dy*dy>z.radius*z.radius)continue;float sum=0;int count=0;for(int oy=-c.blur_radius;oy<=c.blur_radius;++oy)for(int ox=-c.blur_radius;ox<=c.blur_radius;++ox){int sx=clampi(x+ox,c.width),sy=clampi(y+oy,c.height);sum+=in[pix(c.width,c.channels,sy,sx,ch)];++count;}float a=clip(c.opacity*z.opacity,0,1);value=(1-a)*value+a*(sum/count);}out[i]=clip(value,c.clip_min,c.clip_max);}
void check(cudaError_t e,const char* n){if(e!=cudaSuccess)throw std::runtime_error(std::string(n)+": "+cudaGetErrorString(e));}
void vi(int w,int h,int c,const float* a,const float* b,float lo,float hi){if(w<=0||h<=0||c<=0||!a||!b||!std::isfinite(lo)||!std::isfinite(hi)||hi<lo)throw std::invalid_argument("invalid noise image configuration");}
void vv(const TemporalBatchConfig& c,const float* a,const float* b){vi(c.width,c.height,c.channels,a,b,c.clip_min,c.clip_max);if(c.frames<=0||!std::isfinite(c.temporal_correlation)||c.temporal_correlation<-1||c.temporal_correlation>1)throw std::invalid_argument("invalid video configuration");}
std::uint64_t host_mix(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
float host_unit(std::uint64_t x){return static_cast<float>(host_mix(x)>>40)/16777216.0f;}
}
#define LAUNCH(K,A,B,C,N,S,L) do{K<<<(unsigned int)(((N)+255)/256),256,0,S>>>(A,B,C);check(cudaGetLastError(),L);}while(0)
void random_telegraph_signal_noise_f32(const float* i,float* o,const RandomTelegraphSignalNoiseConfig& c,cudaStream_t s){vi(c.width,c.height,c.channels,i,o,c.clip_min,c.clip_max);if(!std::isfinite(c.low_offset)||!std::isfinite(c.high_offset)||!std::isfinite(c.transition_probability)||c.transition_probability<0||c.transition_probability>1||c.initial_state>1)throw std::invalid_argument("invalid random telegraph configuration");LAUNCH(rts_kernel,i,o,c,(size_t)c.height*c.width*c.channels,s,"random_telegraph_signal_noise");}
void inter_frame_compression_noise_f32(const float* i,float* o,const InterFrameCompressionNoiseConfig& c,cudaStream_t s){vv(c,i,o);if(!std::isfinite(c.quantization_step)||c.quantization_step<0||!std::isfinite(c.strength)||c.strength<0)throw std::invalid_argument("invalid inter-frame compression configuration");LAUNCH(ifc_kernel,i,o,c,(size_t)c.frames*c.height*c.width*c.channels,s,"inter_frame_compression_noise");}
void gop_keyframe_artifacts_f32(const float* i,float* o,const GopKeyframeArtifactsConfig& c,cudaStream_t s){vv(c,i,o);if(c.gop_size<=0||!std::isfinite(c.keyframe_strength)||c.keyframe_strength<0||!std::isfinite(c.interframe_strength)||c.interframe_strength<0)throw std::invalid_argument("invalid GOP configuration");LAUNCH(gop_kernel,i,o,c,(size_t)c.frames*c.height*c.width*c.channels,s,"gop_keyframe_artifacts");}
void block_motion_estimation_artifacts_f32(const float* i,float* o,const BlockMotionEstimationArtifactsConfig& c,cudaStream_t s){vv(c,i,o);if(c.block_width<=0||c.block_height<=0||!std::isfinite(c.strength)||c.strength<0)throw std::invalid_argument("invalid motion-estimation configuration");LAUNCH(motion_kernel,i,o,c,(size_t)c.frames*c.height*c.width*c.channels,s,"block_motion_estimation_artifacts");}
void make_water_droplets(WaterDroplet* output,const WaterDropletsOnLensConfig& c){if(!output&&c.droplet_count>0)throw std::invalid_argument("water droplet output is null");for(int i=0;i<c.droplet_count;++i) {unsigned long long b=(unsigned long long)i*4;output[i]={host_unit(c.seed+b)*c.width,host_unit(c.seed+b+1)*c.height,c.radius_min+(c.radius_max-c.radius_min)*host_unit(c.seed+b+2),1};}}
void water_droplets_on_lens_f32(const float* i,float* o,const WaterDropletsOnLensConfig& c,cudaStream_t s){vi(c.width,c.height,c.channels,i,o,c.clip_min,c.clip_max);if(c.droplet_count<0||c.blur_radius<0||c.blur_radius>32||!std::isfinite(c.opacity)||c.opacity<0||c.opacity>1||!std::isfinite(c.radius_min)||!std::isfinite(c.radius_max)||c.radius_min<=0||c.radius_min>c.radius_max)throw std::invalid_argument("invalid water droplet configuration");LAUNCH(droplets_kernel,i,o,c,(size_t)c.height*c.width*c.channels,s,"water_droplets_on_lens");}
#undef LAUNCH
}
