#include "augmatch/catalog/remaining_catalog.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <fstream>
#include <limits>
#include <random>
#include <stdexcept>
#include <vector>
namespace augmatch { namespace {
void check(int w,int h,int c){if(w<=0||h<=0||c<=0)throw std::invalid_argument("invalid remaining-catalog dimensions");}
void buffers(const std::uint8_t* i,std::uint8_t* o){if(!i||!o)throw std::invalid_argument("null remaining-catalog buffer");}
std::uint64_t sm(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
float unit(std::uint64_t s){return static_cast<float>(sm(s)>>40)/16777216.0f;}
std::uint8_t sat(float x){return static_cast<std::uint8_t>(std::max(0.0f,std::min(255.0f,std::floor(x+0.5f))));}
float gaussian(std::uint64_t s){const float u=std::max(1e-7f,unit(s)),v=unit(s+1);return std::sqrt(-2.0f*std::log(u))*std::cos(6.28318530718f*v);}
void validate(int w,int h,int c,const std::uint8_t* i,std::uint8_t* o){check(w,h,c);buffers(i,o);}
float channel_luma(const std::uint8_t* p){return 0.299f*p[0]+0.587f*p[1]+0.114f*p[2];}
void rgb_hsv(float r,float g,float b,float& h,float& s,float& v){r/=255.f;g/=255.f;b/=255.f;const float mx=std::max(r,std::max(g,b)),mn=std::min(r,std::min(g,b)),d=mx-mn;h=0;if(d>0){if(mx==r)h=60.f*std::fmod((g-b)/d+6.f,6.f);else if(mx==g)h=60.f*((b-r)/d+2.f);else h=60.f*((r-g)/d+4.f);}s=mx==0?0:d/mx;v=mx;}
void hsv_rgb(float h,float s,float v,float& r,float& g,float& b){h=std::fmod(h+360.f,360.f);const float x=v*s*(1.f-std::fabs(std::fmod(h/60.f,2.f)-1.f)),m=v-v*s;float a=0,z=0;if(h<60){a=x;z=0;}else if(h<120){a=x;z=0;}else if(h<180){a=0;z=x;}else if(h<240){a=0;z=x;}else if(h<300){a=x;z=0;}else{a=x;z=0;}if(h<60){r=v;g=a+m;b=m;}else if(h<120){r=a+m;g=v;b=m;}else if(h<180){r=m;g=v;b=z+m;}else if(h<240){r=m;g=z+m;b=v;}else if(h<300){r=z+m;g=m;b=v;}else{r=v;g=m;b=a+m;}}
std::uint8_t at(const std::uint8_t* in,int w,int h,int c,int x,int y,int ch){x=std::max(0,std::min(w-1,x));y=std::max(0,std::min(h-1,y));return in[(static_cast<std::size_t>(y)*w+x)*c+ch];}
}
void additive_laplace_noise_u8(const std::uint8_t* in,std::uint8_t* out,const AdditiveLaplaceNoiseConfig& c,cudaStream_t){validate(c.width,c.height,c.channels,in,out);if(!std::isfinite(c.scale)||c.scale<0)throw std::invalid_argument("Laplace scale must be finite and nonnegative");for(std::size_t i=0,n=static_cast<std::size_t>(c.width)*c.height*c.channels;i<n;++i){const float u=unit(c.seed+i*2+1)-.5f;const float noise=-c.scale*std::copysign(std::log(std::max(1e-7f,1.f-2.f*std::fabs(u))),u);out[i]=sat(static_cast<float>(in[i])+noise*255.f);}}
void additive_poisson_noise_u8(const std::uint8_t* in,std::uint8_t* out,const AdditivePoissonNoiseConfig& c,cudaStream_t){validate(c.width,c.height,c.channels,in,out);if(!std::isfinite(c.scale)||c.scale<=0)throw std::invalid_argument("Poisson scale must be finite and positive");for(std::size_t i=0,n=static_cast<std::size_t>(c.width)*c.height*c.channels;i<n;++i){std::poisson_distribution<int> d(std::max(0.f,in[i]*c.scale/255.f));std::mt19937_64 g(sm(c.seed+i));const float delta=(static_cast<float>(d(g))-in[i]*c.scale/255.f)*255.f/c.scale;out[i]=sat(in[i]+delta);}}
void cartoon_u8(const std::uint8_t* in,std::uint8_t* out,const CartoonConfig& c,cudaStream_t){validate(c.width,c.height,c.channels,in,out);if(c.channels<3||c.blur_radius<0||!std::isfinite(c.edge_threshold)||c.edge_threshold<0)throw std::invalid_argument("invalid Cartoon configuration");const int r=c.blur_radius;for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){float sum[3]={0,0,0};int count=0;for(int yy=y-r;yy<=y+r;++yy)for(int xx=x-r;xx<=x+r;++xx){for(int ch=0;ch<3;++ch)sum[ch]+=at(in,c.width,c.height,c.channels,xx,yy,ch);++count;}auto* q=out+(static_cast<std::size_t>(y)*c.width+x)*c.channels;const float e=std::fabs(channel_luma(in+(static_cast<std::size_t>(y)*c.width+std::min(c.width-1,x+1))*c.channels))-channel_luma(in+(static_cast<std::size_t>(y)*c.width+std::max(0,x-1))*c.channels);for(int ch=0;ch<3;++ch)q[ch]=e>=c.edge_threshold?c.edge_value:sat(sum[ch]/count);for(int ch=3;ch<c.channels;++ch)q[ch]=in[(static_cast<std::size_t>(y)*c.width+x)*c.channels+ch];}}
void rand_augment_u8(const std::uint8_t* in,std::uint8_t* out,const RandAugmentConfig& c,cudaStream_t s){validate(c.width,c.height,c.channels,in,out);if(c.count<0||c.count>32||!std::isfinite(c.magnitude)||c.magnitude<0)throw std::invalid_argument("invalid RandAugment configuration");std::vector<std::uint8_t> a(in,in+static_cast<std::size_t>(c.width)*c.height*c.channels),b(a.size());for(int k=0;k<c.count;++k){const int op=static_cast<int>(sm(c.seed+k)%4);if(op==0){for(std::size_t i=0;i<a.size();++i)b[i]=sat(a[i]+(unit(c.seed+k+99)-.5f)*2.f*c.magnitude*255.f);}else if(op==1){for(std::size_t i=0;i<a.size();++i)b[i]=sat((a[i]-128.f)*(1.f+c.magnitude)+128.f);}else if(op==2){CartoonConfig z{c.width,c.height,c.channels,1,c.magnitude*80.f,0};cartoon_u8(a.data(),b.data(),z,s);}else{AdditiveLaplaceNoiseConfig z{c.width,c.height,c.channels,c.magnitude*.05f,c.seed+k};additive_laplace_noise_u8(a.data(),b.data(),z,s);}a.swap(b);}std::copy(a.begin(),a.end(),out);}
void change_colorspace_u8(const std::uint8_t* in,std::uint8_t* out,const ChangeColorspaceConfig& c,cudaStream_t){validate(c.width,c.height,c.channels,in,out);if(c.channels<3)throw std::invalid_argument("ChangeColorspace requires RGB channels");if(c.source==c.destination){std::copy(in,in+static_cast<std::size_t>(c.width)*c.height*c.channels,out);return;}for(int i=0,n=c.width*c.height;i<n;++i){const auto* p=in+i*c.channels;auto* q=out+i*c.channels;if(c.source==CatalogColorSpace::RGB&&c.destination==CatalogColorSpace::HSV){float h,s,v;rgb_hsv(p[0],p[1],p[2],h,s,v);q[0]=sat(h/360.f*255.f);q[1]=sat(s*255.f);q[2]=sat(v*255.f);}else if(c.source==CatalogColorSpace::HSV&&c.destination==CatalogColorSpace::RGB){float r,g,b;hsv_rgb(p[0]/255.f*360.f,p[1]/255.f,p[2]/255.f,r,g,b);q[0]=sat(r*255);q[1]=sat(g*255);q[2]=sat(b*255);}else{for(int ch=0;ch<3;++ch)q[ch]=p[ch];}for(int ch=3;ch<c.channels;++ch)q[ch]=p[ch];}}
void kmeans_color_quantization_u8(const std::uint8_t* in,std::uint8_t* out,const KMeansColorQuantizationConfig& c,cudaStream_t){validate(c.width,c.height,c.channels,in,out);if(c.channels<3||c.clusters<1||c.clusters>256||c.iterations<1||c.iterations>100)throw std::invalid_argument("invalid KMeansColorQuantization configuration");const int n=c.width*c.height,k=c.clusters;std::vector<std::array<float,3>> centers(k);for(int j=0;j<k;++j){const int index=static_cast<int>(sm(c.seed+j)%n);for(int ch=0;ch<3;++ch)centers[j][ch]=in[index*c.channels+ch];}std::vector<int> labels(n);for(int it=0;it<c.iterations;++it){std::vector<std::array<float,3>> sums(k);std::vector<int> counts(k);for(int i=0;i<n;++i){float best=std::numeric_limits<float>::max();int label=0;for(int j=0;j<k;++j){float d=0;for(int ch=0;ch<3;++ch){const float x=in[i*c.channels+ch]-centers[j][ch];d+=x*x;}if(d<best){best=d;label=j;}}labels[i]=label;for(int ch=0;ch<3;++ch)sums[label][ch]+=in[i*c.channels+ch];++counts[label];}for(int j=0;j<k;++j)if(counts[j])for(int ch=0;ch<3;++ch)centers[j][ch]=sums[j][ch]/counts[j];}for(int i=0;i<n;++i){auto* q=out+i*c.channels;for(int ch=0;ch<3;++ch)q[ch]=sat(centers[labels[i]][ch]);for(int ch=3;ch<c.channels;++ch)q[ch]=in[i*c.channels+ch];}}
void convolve_u8(const std::uint8_t* in,std::uint8_t* out,const ConvolveConfig& c,cudaStream_t){validate(c.width,c.height,c.channels,in,out);if(c.kernel_width<=0||c.kernel_height<=0||!c.kernel||!std::isfinite(c.bias))throw std::invalid_argument("invalid Convolve configuration");float div=c.divisor;if(div==0)for(int i=0;i<c.kernel_width*c.kernel_height;++i)div+=c.kernel[i];if(!std::isfinite(div)||std::fabs(div)<1e-7f)div=1;const int rx=c.kernel_width/2,ry=c.kernel_height/2;for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){float sum=0;for(int ky=0;ky<c.kernel_height;++ky)for(int kx=0;kx<c.kernel_width;++kx)sum+=c.kernel[ky*c.kernel_width+kx]*at(in,c.width,c.height,c.channels,x+kx-rx,y+ky-ry,ch);out[(static_cast<std::size_t>(y)*c.width+x)*c.channels+ch]=sat(sum/div+c.bias);}}
void save_debug_image_every_n_batches_u8(const std::uint8_t* in,std::uint8_t* out,const SaveDebugImageEveryNBatchesConfig& c,cudaStream_t){validate(c.width,c.height,c.channels,in,out);if(c.every_n_batches<=0||c.batch_index<0)throw std::invalid_argument("invalid debug batch schedule");const std::size_t n=static_cast<std::size_t>(c.width)*c.height*c.channels;std::copy(in,in+n,out);if(!c.output_path||c.batch_index%c.every_n_batches!=0)return;std::ofstream f(c.output_path,std::ios::binary);if(!f)throw std::runtime_error("failed to open debug image path");const int channels=c.channels==1?1:3;f<< (channels==1?"P5\n":"P6\n")<<c.width<<' '<<c.height<<"\n255\n";for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){const auto* p=in+(static_cast<std::size_t>(y)*c.width+x)*c.channels;if(channels==1)f.put(static_cast<char>(p[0]));else{f.put(static_cast<char>(p[0]));f.put(static_cast<char>(p[1]));f.put(static_cast<char>(p[2]));}}}
void with_polar_warping_u8(const std::uint8_t* in,std::uint8_t* out,const WithPolarWarpingConfig& c,cudaStream_t){validate(c.width,c.height,c.channels,in,out);if(!std::isfinite(c.center_x)||!std::isfinite(c.center_y)||!std::isfinite(c.angle_scale)||!std::isfinite(c.radius_scale)||c.radius_scale<=0)throw std::invalid_argument("invalid WithPolarWarping configuration");const float maxr=std::sqrt(std::max(c.center_x*c.width,(1-c.center_x)*c.width)*std::max(c.center_y*c.height,(1-c.center_y)*c.height));for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){const float u=(x+.5f)/c.width-c.center_x,v=(y+.5f)/c.height-c.center_y,r=std::sqrt(u*u+v*v),a=std::atan2(v,u);const float sx=(c.center_x+std::cos(a*c.angle_scale)*r*c.radius_scale)*c.width-.5f,sy=(c.center_y+std::sin(a*c.angle_scale)*r*c.radius_scale)*c.height-.5f;auto* q=out+(static_cast<std::size_t>(y)*c.width+x)*c.channels;if(sx<0||sy<0||sx>=c.width||sy>=c.height)for(int ch=0;ch<c.channels;++ch)q[ch]=c.fill;else for(int ch=0;ch<c.channels;++ch)q[ch]=at(in,c.width,c.height,c.channels,static_cast<int>(std::lround(sx)),static_cast<int>(std::lround(sy)),ch);(void)maxr;}}
void jigsaw_u8(const std::uint8_t* in,std::uint8_t* out,const JigsawConfig& c,cudaStream_t){validate(c.width,c.height,c.channels,in,out);if(c.grid_rows<=0||c.grid_cols<=0)throw std::invalid_argument("invalid Jigsaw grid");const int cells=c.grid_rows*c.grid_cols;std::vector<std::uint32_t> p(cells);for(int i=0;i<cells;++i)p[i]=i;if(c.permutation)std::copy(c.permutation,c.permutation+cells,p.begin());else for(int i=cells-1;i>0;--i)std::swap(p[i],p[sm(c.seed+i)%(i+1)]);std::vector<bool> seen(cells);for(auto x:p)if(x>=static_cast<unsigned>(cells)||seen[x])throw std::invalid_argument("Jigsaw permutation is not a bijection");else seen[x]=true;for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x){const int dr=std::min(c.grid_rows-1,y*c.grid_rows/c.height),dc=std::min(c.grid_cols-1,x*c.grid_cols/c.width),d=dr*c.grid_cols+dc,s=p[d],sr=s/c.grid_cols,sc=s%c.grid_cols,sy=y*c.height/c.grid_rows-dr*c.height/c.grid_rows+sr*c.height/c.grid_rows,sx=x*c.width/c.grid_cols-dc*c.width/c.grid_cols+sc*c.width/c.grid_cols;for(int ch=0;ch<c.channels;++ch)out[(static_cast<std::size_t>(y)*c.width+x)*c.channels+ch]=in[(static_cast<std::size_t>(sy)*c.width+sx)*c.channels+ch];}}
void fda_u8(const std::uint8_t* in,std::uint8_t* out,const FDAConfig& c,cudaStream_t){validate(c.width,c.height,c.channels,in,out);if(!c.reference||c.reference_width<=0||c.reference_height<=0||!std::isfinite(c.low_frequency_radius)||c.low_frequency_radius<0||c.low_frequency_radius>1)throw std::invalid_argument("FDA requires a reference image and radius in [0,1]");const int n=c.width*c.height;float a[3]={0,0,0},b[3]={0,0,0};for(int i=0;i<n;++i)for(int ch=0;ch<3&&ch<c.channels;++ch)a[ch]+=in[i*c.channels+ch];for(int y=0;y<c.reference_height;++y)for(int x=0;x<c.reference_width;++x)for(int ch=0;ch<3&&ch<c.channels;++ch)b[ch]+=c.reference[(static_cast<std::size_t>(y)*c.reference_width+x)*c.channels+ch];for(int ch=0;ch<3;++ch){a[ch]/=n;b[ch]/=static_cast<float>(c.reference_width*c.reference_height);}for(int i=0;i<n;++i){for(int ch=0;ch<c.channels;++ch){if(ch<3)out[i*c.channels+ch]=sat((in[i*c.channels+ch]-a[ch])*(1.f-c.low_frequency_radius)+b[ch]*c.low_frequency_radius);else out[i*c.channels+ch]=in[i*c.channels+ch];}}}
void fourier_domain_adaptation_u8(const std::uint8_t* in,std::uint8_t* out,const FourierDomainAdaptationConfig& c,cudaStream_t s){fda_u8(in,out,c,s);}
}
