#include "augmatch/core/signal.hpp"
#include <cuda_runtime.h>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {__device__ unsigned char sat(float x){return (unsigned char)fminf(255.f,fmaxf(0.f,rintf(x)));}__global__ void gain_kernel(const unsigned char* in,unsigned char* out,SignalGainConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i<n)out[i]=sat(in[i]*c.gain);}__global__ void level_kernel(const unsigned char* in,unsigned char* out,SignalLevelConfig c,int mode){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int v=in[i];if(mode==0)v=min(v,c.level);else if(mode==1)v=max(0,min(255,v+c.level));else if(mode==2)v=(int)rintf(rintf(v*(c.level-1)/255.f)*(255.f/(c.level-1)));else v=v&(255<<(8-c.level));out[i]=(unsigned char)v;}void check(cudaError_t e,const char* p){if(e!=cudaSuccess)throw std::runtime_error(std::string(p)+": "+cudaGetErrorString(e));}void valid(const SignalGainConfig& c){if(c.width<=0||c.height<=0||c.channels<=0||c.gain<0||!isfinite(c.gain))throw std::invalid_argument("invalid signal gain configuration");}void apply(const std::uint8_t* in,std::uint8_t* out,const SignalGainConfig& c,cudaStream_t s,const char* name){valid(c);if(!in||!out)throw std::invalid_argument("null signal buffer");int n=c.width*c.height*c.channels;gain_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),name);}}
void exposure_scale_u8(const std::uint8_t* i,std::uint8_t* o,const SignalGainConfig& c,cudaStream_t s){apply(i,o,c,s,"exposure_kernel");}
void analog_gain_u8(const std::uint8_t* i,std::uint8_t* o,const SignalGainConfig& c,cudaStream_t s){apply(i,o,c,s,"analog_gain_kernel");}
void digital_gain_u8(const std::uint8_t* i,std::uint8_t* o,const SignalGainConfig& c,cudaStream_t s){apply(i,o,c,s,"digital_gain_kernel");}
void level_apply(const std::uint8_t* i,std::uint8_t* o,const SignalLevelConfig& c,int mode,cudaStream_t s){if(c.width<=0||c.height<=0||c.channels<=0||!i||!o)throw std::invalid_argument("invalid signal level configuration");int n=c.width*c.height*c.channels;level_kernel<<<(n+255)/256,256,0,s>>>(i,o,c,mode);check(cudaGetLastError(),"level_kernel");}
void pixel_saturation_u8(const std::uint8_t* i,std::uint8_t* o,const SignalLevelConfig& c,cudaStream_t s){if(c.level<0||c.level>255)throw std::invalid_argument("invalid saturation level");level_apply(i,o,c,0,s);}
void black_level_u8(const std::uint8_t* i,std::uint8_t* o,const SignalLevelConfig& c,cudaStream_t s){level_apply(i,o,c,1,s);}
void adc_quantize_u8(const std::uint8_t* i,std::uint8_t* o,const SignalLevelConfig& c,cudaStream_t s){if(c.level<2||c.level>256)throw std::invalid_argument("ADC levels must be in [2,256]");level_apply(i,o,c,2,s);}
void bit_reduce_u8(const std::uint8_t* i,std::uint8_t* o,const SignalLevelConfig& c,cudaStream_t s){if(c.level<1||c.level>8)throw std::invalid_argument("bit depth must be in [1,8]");level_apply(i,o,c,3,s);}
__global__ void cross_kernel(const unsigned char* in,unsigned char* out,SpatialArtifactConfig c,int mode){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);int xl=max(0,x-1),xr=min(c.width-1,x+1),yu=max(0,y-1),yd=min(c.height-1,y+1);float v=in[i],neighbor;if(mode==0)neighbor=.25f*(in[(y*c.width+xl)*c.channels+ch]+in[(y*c.width+xr)*c.channels+ch]+in[(yu*c.width+x)*c.channels+ch]+in[(yd*c.width+x)*c.channels+ch]);else neighbor=in[(y*c.width+xl)*c.channels+ch];out[i]=sat((1-c.coefficient)*v+c.coefficient*neighbor);}
void spatial_apply(const std::uint8_t* i,std::uint8_t* o,const SpatialArtifactConfig& c,int mode,cudaStream_t s){if(!i||!o||c.width<=0||c.height<=0||c.channels<=0||c.coefficient<0||c.coefficient>1)throw std::invalid_argument("invalid spatial artifact configuration");int n=c.width*c.height*c.channels;cross_kernel<<<(n+255)/256,256,0,s>>>(i,o,c,mode);check(cudaGetLastError(),"spatial_kernel");}
void pixel_cross_talk_u8(const std::uint8_t* i,std::uint8_t* o,const SpatialArtifactConfig& c,cudaStream_t s){spatial_apply(i,o,c,0,s);}
void charge_leakage_u8(const std::uint8_t* i,std::uint8_t* o,const SpatialArtifactConfig& c,cudaStream_t s){spatial_apply(i,o,c,1,s);}
__global__ void channel_gain_kernel(const unsigned char* in,unsigned char* out,ChannelGainConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.width*c.height*c.channels;if(i<n){int ch=i%c.channels;float g=ch==0?c.gain0:ch==1?c.gain1:c.gain2;out[i]=sat(in[i]*g);}}
void channel_gain_u8(const std::uint8_t* i,std::uint8_t* o,const ChannelGainConfig& c,cudaStream_t s){if(!i||!o||c.width<=0||c.height<=0||c.channels<=0||c.gain0<0||c.gain1<0||c.gain2<0)throw std::invalid_argument("invalid channel gain configuration");int n=c.width*c.height*c.channels;channel_gain_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"channel_gain_kernel");}
}
