#include "augmatch/core/signal.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace augmatch { namespace {void check(const SignalGainConfig& c){if(c.width<=0||c.height<=0||c.channels<=0||c.gain<0||!std::isfinite(c.gain))throw std::invalid_argument("invalid signal gain configuration");} void apply(const std::uint8_t* in,std::uint8_t* out,const SignalGainConfig& c){check(c);if(!in||!out)throw std::invalid_argument("null signal buffer");for(int i=0,n=c.width*c.height*c.channels;i<n;++i)out[i]=static_cast<std::uint8_t>(std::lround(std::max(0.f,std::min(255.f,in[i]*c.gain))));}}
void exposure_scale_u8(const std::uint8_t* in,std::uint8_t* out,const SignalGainConfig& c,cudaStream_t){apply(in,out,c);}
void analog_gain_u8(const std::uint8_t* in,std::uint8_t* out,const SignalGainConfig& c,cudaStream_t){apply(in,out,c);}
void digital_gain_u8(const std::uint8_t* in,std::uint8_t* out,const SignalGainConfig& c,cudaStream_t){apply(in,out,c);}
namespace {void level_check(const SignalLevelConfig& c){if(c.width<=0||c.height<=0||c.channels<=0)throw std::invalid_argument("invalid signal level dimensions");} template<class F> void level_apply(const std::uint8_t* in,std::uint8_t* out,const SignalLevelConfig& c,F f){level_check(c);if(!in||!out)throw std::invalid_argument("null signal level buffer");for(int i=0,n=c.width*c.height*c.channels;i<n;++i)out[i]=f(in[i],c.level);}}
void pixel_saturation_u8(const std::uint8_t* i,std::uint8_t* o,const SignalLevelConfig& c,cudaStream_t){if(c.level<0||c.level>255)throw std::invalid_argument("invalid saturation level");level_apply(i,o,c,[](int v,int l){return static_cast<std::uint8_t>(std::min(v,l));});}
void black_level_u8(const std::uint8_t* i,std::uint8_t* o,const SignalLevelConfig& c,cudaStream_t){level_apply(i,o,c,[](int v,int l){return static_cast<std::uint8_t>(std::max(0,std::min(255,v+l)));});}
void adc_quantize_u8(const std::uint8_t* i,std::uint8_t* o,const SignalLevelConfig& c,cudaStream_t){if(c.level<2||c.level>256)throw std::invalid_argument("ADC levels must be in [2,256]");level_apply(i,o,c,[](int v,int l){return static_cast<std::uint8_t>(std::lround(std::lround(v* (l-1)/255.0)*(255.0/(l-1))));});}
void bit_reduce_u8(const std::uint8_t* i,std::uint8_t* o,const SignalLevelConfig& c,cudaStream_t){if(c.level<1||c.level>8)throw std::invalid_argument("bit depth must be in [1,8]");level_apply(i,o,c,[](int v,int l){return static_cast<std::uint8_t>(v & (255 << (8-l)));});}
void pixel_cross_talk_u8(const std::uint8_t* in,std::uint8_t* out,const SpatialArtifactConfig& c,cudaStream_t){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.coefficient<0||c.coefficient>1)throw std::invalid_argument("invalid cross-talk configuration");auto at=[&](int x,int y,int ch){x=std::max(0,std::min(c.width-1,x));y=std::max(0,std::min(c.height-1,y));return static_cast<float>(in[(y*c.width+x)*c.channels+ch]);};for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){float n=(at(x-1,y,ch)+at(x+1,y,ch)+at(x,y-1,ch)+at(x,y+1,ch))*.25f;out[(y*c.width+x)*c.channels+ch]=static_cast<std::uint8_t>(std::lround((1-c.coefficient)*at(x,y,ch)+c.coefficient*n));}}
void charge_leakage_u8(const std::uint8_t* in,std::uint8_t* out,const SpatialArtifactConfig& c,cudaStream_t){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.coefficient<0||c.coefficient>1)throw std::invalid_argument("invalid leakage configuration");for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){int sx=std::max(0,x-1);float a=in[(y*c.width+sx)*c.channels+ch],v=in[(y*c.width+x)*c.channels+ch];out[(y*c.width+x)*c.channels+ch]=static_cast<std::uint8_t>(std::lround((1-c.coefficient)*v+c.coefficient*a));}}
void channel_gain_u8(const std::uint8_t* in,std::uint8_t* out,const ChannelGainConfig& c,cudaStream_t){if(!in||!out||c.width<=0||c.height<=0||c.channels<=0||c.gain0<0||c.gain1<0||c.gain2<0)throw std::invalid_argument("invalid channel gain configuration");for(int i=0,n=c.width*c.height*c.channels;i<n;++i){int ch=i%c.channels;float g=ch==0?c.gain0:ch==1?c.gain1:c.gain2;out[i]=static_cast<std::uint8_t>(std::lround(std::max(0.f,std::min(255.f,in[i]*g))));}}
}
