#include "augmatch/geometry/size.hpp"
#include <cuda_runtime.h>
#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>
namespace augmatch { namespace {
__device__ int refl(int i,int n){if(n==1)return 0;while(i<0||i>=n)i=i<0?-i:2*n-i-2;return i;}
__global__ void crop_kernel(const unsigned char* in,unsigned char* out,CenterCropConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.output_width*c.output_height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.output_width,y=i/(c.output_width*c.channels),ox=(c.input_width-c.output_width)/2,oy=(c.input_height-c.output_height)/2;out[i]=in[((y+oy)*c.input_width+x+ox)*c.channels+ch];}
__global__ void random_crop_kernel(const unsigned char* in,unsigned char* out,RandomCropConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.output_width*c.output_height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.output_width,y=i/(c.output_width*c.channels);out[i]=in[((y+c.top)*c.input_width+x+c.left)*c.channels+ch];}
__global__ void crop_non_empty_mask_kernel(const unsigned char* image,const unsigned char* mask,unsigned char* output_image,unsigned char* output_mask,CropNonEmptyMaskIfExistsConfig c,int x0,int y0){int i=blockIdx.x*blockDim.x+threadIdx.x;const int image_n=c.crop_width*c.crop_height*c.channels;if(i<image_n){int ch=i%c.channels,x=(i/c.channels)%c.crop_width,y=i/(c.crop_width*c.channels);output_image[i]=image[((y+y0)*c.input_width+x+x0)*c.channels+ch];}if(mask&&output_mask){const int mask_n=c.crop_width*c.crop_height*c.mask_channels;if(i<mask_n){int ch=i%c.mask_channels,x=(i/c.mask_channels)%c.crop_width,y=i/(c.crop_width*c.mask_channels);output_mask[i]=mask[((y+y0)*c.input_width+x+x0)*c.mask_channels+ch];}}}
__global__ void random_crop_from_borders_kernel(const unsigned char* in,unsigned char* out,RandomCropFromBordersConfig c,int left,int top,int ow,int oh){int i=blockIdx.x*blockDim.x+threadIdx.x,n=ow*oh*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%ow,y=i/(ow*c.channels);out[i]=in[((y+top)*c.input_width+x+left)*c.channels+ch];}
__global__ void pad_kernel(const unsigned char* in,unsigned char* out,PadConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.output_width*c.output_height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.output_width,y=i/(c.output_width*c.channels),ox=(c.output_width-c.input_width)/2,oy=(c.output_height-c.input_height)/2,sx=x-ox,sy=y-oy;bool inside=sx>=0&&sx<c.input_width&&sy>=0&&sy<c.input_height;if(!inside&&c.border==PadBorder::Constant){out[i]=c.value;return;}if(c.border==PadBorder::Replicate){sx=max(0,min(c.input_width-1,sx));sy=max(0,min(c.input_height-1,sy));}else if(c.border==PadBorder::Reflect101){sx=refl(sx,c.input_width);sy=refl(sy,c.input_height);}out[i]=in[(sy*c.input_width+sx)*c.channels+ch];}
__global__ void crop_pad_kernel(const unsigned char* in,unsigned char* out,CropPadConfig c,int ow,int oh){int i=blockIdx.x*blockDim.x+threadIdx.x,n=ow*oh*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%ow,y=i/(ow*c.channels),pl=max(0,c.left),pt=max(0,c.top),cl=max(0,-c.left),ct=max(0,-c.top),sx=x-pl+cl,sy=y-pt+ct;out[i]=(sx>=0&&sx<c.input_width&&sy>=0&&sy<c.input_height)?in[(sy*c.input_width+sx)*c.channels+ch]:c.value;}
__global__ void size_transform_kernel(const unsigned char* in,unsigned char* out,int iw,int ih,int ow,int oh,int channels,unsigned char value,PadBorder border,SizeAnchor anchor,bool pad){int i=blockIdx.x*blockDim.x+threadIdx.x,n=ow*oh*channels;if(i>=n)return;int ch=i%channels,x=(i/channels)%ow,y=i/(ow*channels),dx=anchor==SizeAnchor::Center?abs(ow-iw)/2:0,dy=anchor==SizeAnchor::Center?abs(oh-ih)/2:0,sx=pad?x-dx:x+dx,sy=pad?y-dy:y+dy;bool inside=sx>=0&&sx<iw&&sy>=0&&sy<ih;if(!inside&&border==PadBorder::Constant){out[i]=value;return;}if(border==PadBorder::Replicate){sx=max(0,min(iw-1,sx));sy=max(0,min(ih-1,sy));}else if(border==PadBorder::Reflect101){sx=refl(sx,iw);sy=refl(sy,ih);}out[i]=in[(sy*iw+sx)*channels+ch];}
void check(cudaError_t e,const char* p){if(e!=cudaSuccess)throw std::runtime_error(std::string(p)+": "+cudaGetErrorString(e));}
void valid(int w,int h,int c){if(w<=0||h<=0||c<=0)throw std::invalid_argument("invalid size dimensions");}
std::uint64_t splitmix64(std::uint64_t value){value+=0x9e3779b97f4a7c15ULL;value=(value^(value>>30))*0xbf58476d1ce4e5b9ULL;value=(value^(value>>27))*0x94d049bb133111ebULL;return value^(value>>31);}
int crop_limit(float fraction,int size){if(!std::isfinite(fraction)||fraction<0.0f||fraction>1.0f)throw std::invalid_argument("crop fractions must be finite values in [0,1]");return static_cast<int>(std::floor(fraction*static_cast<float>(size)));}
int choose_offset(int explicit_offset,int maximum,std::uint64_t seed,int side){if(explicit_offset>=0)return explicit_offset;return static_cast<int>(splitmix64(seed+static_cast<std::uint64_t>(side))%(static_cast<std::uint64_t>(maximum)+1ULL));}
RandomResizedCropRectangle rectangle(const RandomResizedCropConfig& c){
  valid(c.input_width,c.input_height,c.channels);
  if(c.output_width<=0||c.output_height<=0||static_cast<int>(c.interpolation)<0||static_cast<int>(c.interpolation)>2) throw std::invalid_argument("invalid random resized crop output configuration");
  if(c.crop_width<0||c.crop_height<0||(c.crop_width==0)!=(c.crop_height==0)) throw std::invalid_argument("crop dimensions must both be explicit or both be zero");
  const int width=c.crop_width==0?1+static_cast<int>(splitmix64(c.seed)%(static_cast<std::uint64_t>(c.input_width))):c.crop_width;
  const int height=c.crop_height==0?1+static_cast<int>(splitmix64(c.seed+1)%(static_cast<std::uint64_t>(c.input_height))):c.crop_height;
  if(width<=0||height<=0||width>c.input_width||height>c.input_height) throw std::invalid_argument("random resized crop rectangle exceeds input");
  const int x=c.crop_x<0?static_cast<int>(splitmix64(c.seed+2)%(static_cast<std::uint64_t>(c.input_width-width+1))):c.crop_x;
  const int y=c.crop_y<0?static_cast<int>(splitmix64(c.seed+3)%(static_cast<std::uint64_t>(c.input_height-height+1))):c.crop_y;
  if(c.crop_x<-1||c.crop_y<-1||x<0||y<0||x+width>c.input_width||y+height>c.input_height) throw std::invalid_argument("random resized crop rectangle is outside input");
  return {x,y,width,height};
}
CropNonEmptyMaskIfExistsRectangle choose_crop_host(const ImageMaskView& source,const CropNonEmptyMaskIfExistsConfig& c){
  if(!source.image.valid()||source.image.type!=DataType::UInt8||source.image.layout!=Layout::HWC) throw std::invalid_argument("CropNonEmptyMaskIfExists requires an HWC uint8 image view");
  if(c.crop_width<=0||c.crop_height<=0||c.crop_width>source.image.width||c.crop_height>source.image.height) throw std::invalid_argument("CropNonEmptyMaskIfExists crop exceeds image");
  if((c.fallback_x< -1)||(c.fallback_y< -1)||(c.fallback_x>=0)!=(c.fallback_y>=0)||c.fallback_x+c.crop_width>source.image.width||c.fallback_y+c.crop_height>source.image.height) throw std::invalid_argument("invalid CropNonEmptyMaskIfExists fallback crop");
  std::vector<std::pair<int,int>> targets;
  if(source.mask.valid()){
    if(source.mask.type!=DataType::UInt8||source.mask.layout!=Layout::HWC||source.mask.width!=source.image.width||source.mask.height!=source.image.height) throw std::invalid_argument("CropNonEmptyMaskIfExists mask view must match image");
    const auto* mask=static_cast<const std::uint8_t*>(source.mask.data);
    for(int y=0;y<source.image.height;++y) for(int x=0;x<source.image.width;++x){bool found=false;for(int ch=0;ch<source.mask.channels;++ch) if(mask[(static_cast<std::size_t>(y)*source.mask.width+x)*source.mask.channels+ch]>c.mask_threshold){found=true;break;}if(found)targets.emplace_back(x,y);}
  }
  if(targets.empty()) return {c.fallback_x>=0?c.fallback_x:static_cast<int>(splitmix64(c.seed)%(source.image.width-c.crop_width+1)),c.fallback_y>=0?c.fallback_y:static_cast<int>(splitmix64(c.seed+1)%(source.image.height-c.crop_height+1)),c.crop_width,c.crop_height,false};
  const auto target=targets[static_cast<std::size_t>(splitmix64(c.seed)%targets.size())]; const int min_x=max(0,target.first-c.crop_width+1),max_x=min(target.first,source.image.width-c.crop_width),min_y=max(0,target.second-c.crop_height+1),max_y=min(target.second,source.image.height-c.crop_height);
  return {min_x+static_cast<int>(splitmix64(c.seed+1)%(max_x-min_x+1)),min_y+static_cast<int>(splitmix64(c.seed+2)%(max_y-min_y+1)),c.crop_width,c.crop_height,true};
}
}
RandomResizedCropRectangle make_random_resized_crop_rectangle(const RandomResizedCropConfig& c){return rectangle(c);}
void random_crop_u8(const std::uint8_t* in,std::uint8_t* out,const RandomCropConfig& c,cudaStream_t s){valid(c.input_width,c.input_height,c.channels);if(!in||!out||c.output_width<=0||c.output_height<=0||c.output_width>c.input_width||c.output_height>c.input_height||c.left<0||c.top<0||c.left+c.output_width>c.input_width||c.top+c.output_height>c.input_height)throw std::invalid_argument("invalid random crop configuration");int n=c.output_width*c.output_height*c.channels;random_crop_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"random_crop_kernel");}
void center_crop_u8(const std::uint8_t* in,std::uint8_t* out,const CenterCropConfig& c,cudaStream_t s){valid(c.input_width,c.input_height,c.channels);if(!in||!out||c.output_width<=0||c.output_height<=0||c.output_width>c.input_width||c.output_height>c.input_height)throw std::invalid_argument("invalid center crop configuration");int n=c.output_width*c.output_height*c.channels;crop_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"crop_kernel");}
void random_resized_crop_u8(const std::uint8_t* in,std::uint8_t* out,const RandomResizedCropConfig& c,cudaStream_t s){
  if(!in||!out) throw std::invalid_argument("null random resized crop buffer");
  const RandomResizedCropRectangle r=make_random_resized_crop_rectangle(c);
  const std::size_t bytes=static_cast<std::size_t>(r.width)*r.height*c.channels;
  std::uint8_t* cropped=nullptr; check(cudaMalloc(&cropped,bytes),"cudaMalloc random resized crop");
  try {
    const RandomCropConfig crop{c.input_width,c.input_height,r.width,r.height,c.channels,r.x,r.y};
    random_crop_u8(in,cropped,crop,s);
    resize_u8(cropped,out,{r.width,r.height,c.output_width,c.output_height,c.channels,c.interpolation},s);
    check(cudaFree(cropped),"cudaFree random resized crop");
  } catch(...) { cudaFree(cropped); throw; }
}
void random_sized_crop_u8(const std::uint8_t* in,std::uint8_t* out,const RandomSizedCropConfig& c,cudaStream_t s){random_resized_crop_u8(in,out,c,s);}
RandomCropFromBordersOffsets make_random_crop_from_borders_offsets(const RandomCropFromBordersConfig& c){
  valid(c.input_width,c.input_height,c.channels);
  const int max_left=crop_limit(c.crop_left,c.input_width),max_right=crop_limit(c.crop_right,c.input_width),max_top=crop_limit(c.crop_top,c.input_height),max_bottom=crop_limit(c.crop_bottom,c.input_height);
  const int left_bound=c.left_offset>=0?c.left_offset:max_left,right_bound=c.right_offset>=0?c.right_offset:max_right,top_bound=c.top_offset>=0?c.top_offset:max_top,bottom_bound=c.bottom_offset>=0?c.bottom_offset:max_bottom;
  if(static_cast<long long>(left_bound)+right_bound>=c.input_width||static_cast<long long>(top_bound)+bottom_bound>=c.input_height)throw std::invalid_argument("border crop fractions and offsets can remove the entire dimension");
  if(c.left_offset < -1 || c.right_offset < -1 || c.top_offset < -1 || c.bottom_offset < -1 || (c.left_offset >= 0 && c.left_offset > max_left) || (c.right_offset >= 0 && c.right_offset > max_right) || (c.top_offset >= 0 && c.top_offset > max_top) || (c.bottom_offset >= 0 && c.bottom_offset > max_bottom)) throw std::invalid_argument("border crop offset exceeds its fraction limit");
  RandomCropFromBordersOffsets result{choose_offset(c.left_offset,max_left,c.seed,0),choose_offset(c.right_offset,max_right,c.seed,1),choose_offset(c.top_offset,max_top,c.seed,2),choose_offset(c.bottom_offset,max_bottom,c.seed,3)};
  if(static_cast<long long>(result.left)+result.right>=c.input_width||static_cast<long long>(result.top)+result.bottom>=c.input_height)throw std::invalid_argument("border crop offsets can remove the entire dimension");
  return result;
}
void random_crop_from_borders_u8(const std::uint8_t* in,std::uint8_t* out,const RandomCropFromBordersConfig& c,cudaStream_t s){
  valid(c.input_width,c.input_height,c.channels);if(!in||!out)throw std::invalid_argument("null border crop buffer");const RandomCropFromBordersOffsets offsets=make_random_crop_from_borders_offsets(c);const int ow=c.input_width-offsets.left-offsets.right,oh=c.input_height-offsets.top-offsets.bottom;const int n=ow*oh*c.channels;random_crop_from_borders_kernel<<<(n+255)/256,256,0,s>>>(in,out,c,offsets.left,offsets.top,ow,oh);check(cudaGetLastError(),"random_crop_from_borders_kernel");
}
RandomCropNearBBoxOffsets make_random_crop_near_bbox_offsets(const RandomCropNearBBoxConfig& c){
  valid(c.input_width,c.input_height,c.channels);
  const BoxXYXY b=c.bbox;
  if(!std::isfinite(b.x1)||!std::isfinite(b.y1)||!std::isfinite(b.x2)||!std::isfinite(b.y2)||b.x1<0.0f||b.y1<0.0f||b.x2>c.input_width||b.y2>c.input_height||b.x2<=b.x1||b.y2<=b.y1)
    throw std::invalid_argument("RandomCropNearBBox requires a non-empty in-image box");
  if(!std::isfinite(c.max_part_shift_x)||!std::isfinite(c.max_part_shift_y)||c.max_part_shift_x<0.0f||c.max_part_shift_y<0.0f)
    throw std::invalid_argument("RandomCropNearBBox max_part_shift values must be finite and nonnegative");
  const auto maximum=[](float fraction,float extent){const double value=std::floor(static_cast<double>(fraction)*static_cast<double>(extent));if(value>static_cast<double>(std::numeric_limits<int>::max()))throw std::invalid_argument("RandomCropNearBBox margin is too large");return static_cast<int>(value);};
  const int max_x=maximum(c.max_part_shift_x,b.x2-b.x1),max_y=maximum(c.max_part_shift_y,b.y2-b.y1);
  if(c.left_offset < -1 || c.right_offset < -1 || c.top_offset < -1 || c.bottom_offset < -1 ||
     (c.left_offset>=0&&c.left_offset>max_x)||(c.right_offset>=0&&c.right_offset>max_x)||
     (c.top_offset>=0&&c.top_offset>max_y)||(c.bottom_offset>=0&&c.bottom_offset>max_y))
    throw std::invalid_argument("RandomCropNearBBox offset exceeds its margin limit");
  RandomCropNearBBoxOffsets result;
  result.left=choose_offset(c.left_offset,max_x,c.seed,0);result.right=choose_offset(c.right_offset,max_x,c.seed,1);
  result.top=choose_offset(c.top_offset,max_y,c.seed,2);result.bottom=choose_offset(c.bottom_offset,max_y,c.seed,3);
  return result;
}
RandomCropNearBBoxRectangle make_random_crop_near_bbox_rectangle(const RandomCropNearBBoxConfig& c){
  const RandomCropNearBBoxOffsets o=make_random_crop_near_bbox_offsets(c);
  const int x0=max(0,static_cast<int>(std::floor(c.bbox.x1))-o.left);
  const int y0=max(0,static_cast<int>(std::floor(c.bbox.y1))-o.top);
  const int x1=min(c.input_width,static_cast<int>(std::ceil(c.bbox.x2))+o.right);
  const int y1=min(c.input_height,static_cast<int>(std::ceil(c.bbox.y2))+o.bottom);
  return {x0,y0,x1-x0,y1-y0};
}
void random_crop_near_bbox_u8(const std::uint8_t* in,std::uint8_t* out,const RandomCropNearBBoxConfig& c,cudaStream_t s){
  if(!in||!out)throw std::invalid_argument("null RandomCropNearBBox buffer");
  const RandomCropNearBBoxRectangle r=make_random_crop_near_bbox_rectangle(c);
  random_crop_u8(in,out,{c.input_width,c.input_height,r.width,r.height,c.channels,r.x,r.y},s);
}
struct BBoxEnvelope { int x1=0,y1=0,x2=0,y2=0; };
void validate_target_config(int width,int height,int channels,const BoxXYXY* boxes,std::size_t count,float erosion){
  valid(width,height,channels); if(count!=0&&!boxes) throw std::invalid_argument("target-aware crop box array is null"); if(!std::isfinite(erosion)||erosion<0.0f||erosion>1.0f) throw std::invalid_argument("target-aware crop erosion must be finite in [0,1]");
  for(std::size_t i=0;i<count;++i){const BoxXYXY b=boxes[i];if(!std::isfinite(b.x1)||!std::isfinite(b.y1)||!std::isfinite(b.x2)||!std::isfinite(b.y2)||b.x1<0||b.y1<0||b.x2>width||b.y2>height||b.x2<=b.x1||b.y2<=b.y1) throw std::invalid_argument("target-aware crop boxes must be non-empty and inside the image");}
}
BBoxEnvelope target_envelope(const BoxXYXY* boxes,std::size_t count,float erosion){float x1=boxes[0].x1,y1=boxes[0].y1,x2=boxes[0].x2,y2=boxes[0].y2;for(std::size_t i=1;i<count;++i){x1=min(x1,boxes[i].x1);y1=min(y1,boxes[i].y1);x2=max(x2,boxes[i].x2);y2=max(y2,boxes[i].y2);}const float ex=(x2-x1)*erosion*0.5f,ey=(y2-y1)*erosion*0.5f;int ix1=static_cast<int>(floor(x1+ex)),iy1=static_cast<int>(floor(y1+ey)),ix2=static_cast<int>(ceil(x2-ex)),iy2=static_cast<int>(ceil(y2-ey));if(ix2<=ix1)ix2=ix1+1;if(iy2<=iy1)iy2=iy1+1;return {ix1,iy1,ix2,iy2};}
int random_between(int low,int high,std::uint64_t seed){if(low>high)throw std::invalid_argument("target-aware crop has no valid origin");return low+static_cast<int>(splitmix64(seed)%(static_cast<std::uint64_t>(high-low)+1ULL));}
BBoxSafeRandomCropRectangle choose_bbox_safe(const BBoxSafeRandomCropConfig& c){validate_target_config(c.input_width,c.input_height,c.channels,c.boxes,c.box_count,c.erosion_rate);const int max_w=c.max_crop_width==0?c.input_width:c.max_crop_width,max_h=c.max_crop_height==0?c.input_height:c.max_crop_height;if(c.min_crop_width<=0||c.min_crop_height<=0||max_w<c.min_crop_width||max_h<c.min_crop_height||max_w>c.input_width||max_h>c.input_height)throw std::invalid_argument("invalid BBoxSafeRandomCrop dimensions");if(c.box_count==0){const int w=random_between(c.min_crop_width,max_w,c.seed),h=random_between(c.min_crop_height,max_h,c.seed+1);return {random_between(0,c.input_width-w,c.seed+2),random_between(0,c.input_height-h,c.seed+3),w,h,true};}const BBoxEnvelope e=target_envelope(c.boxes,c.box_count,c.erosion_rate);const int low_w=max(c.min_crop_width,e.x2-e.x1),low_h=max(c.min_crop_height,e.y2-e.y1);if(low_w>max_w||low_h>max_h)throw std::invalid_argument("BBoxSafeRandomCrop max crop cannot contain boxes");const int w=random_between(low_w,max_w,c.seed),h=random_between(low_h,max_h,c.seed+1);return {random_between(max(0,e.x2-w),min(e.x1,c.input_width-w),c.seed+2),random_between(max(0,e.y2-h),min(e.y1,c.input_height-h),c.seed+3),w,h,false};}
BBoxSafeRandomCropRectangle make_bbox_safe_random_crop_rectangle(const BBoxSafeRandomCropConfig& c){return choose_bbox_safe(c);}
void bbox_safe_random_crop_u8(const std::uint8_t* in,std::uint8_t* out,const BBoxSafeRandomCropConfig& c,cudaStream_t s){if(!in||!out)throw std::invalid_argument("null BBoxSafeRandomCrop buffer");const auto r=choose_bbox_safe(c);random_crop_u8(in,out,{c.input_width,c.input_height,r.width,r.height,c.channels,r.x,r.y},s);}
RandomSizedBBoxSafeCropRectangle make_random_sized_bbox_safe_crop_rectangle(const RandomSizedBBoxSafeCropConfig& c){if(c.output_width<=0||c.output_height<=0||static_cast<int>(c.interpolation)<0||static_cast<int>(c.interpolation)>2)throw std::invalid_argument("invalid RandomSizedBBoxSafeCrop output configuration");BBoxSafeRandomCropConfig source{c.input_width,c.input_height,c.channels,c.boxes,c.box_count,1,1,0,0,c.erosion_rate,c.seed};const auto r=choose_bbox_safe(source);return {r.x,r.y,r.width,r.height,c.output_width,c.output_height,static_cast<float>(c.output_width)/r.width,static_cast<float>(c.output_height)/r.height,r.used_fallback};}
void random_sized_bbox_safe_crop_u8(const std::uint8_t* in,std::uint8_t* out,const RandomSizedBBoxSafeCropConfig& c,cudaStream_t s){if(!in||!out)throw std::invalid_argument("null RandomSizedBBoxSafeCrop buffer");const auto r=make_random_sized_bbox_safe_crop_rectangle(c);std::uint8_t* cropped=nullptr;const std::size_t bytes=static_cast<std::size_t>(r.width)*r.height*c.channels;check(cudaMalloc(&cropped,bytes),"cudaMalloc RandomSizedBBoxSafeCrop");try{random_crop_u8(in,cropped,{c.input_width,c.input_height,r.width,r.height,c.channels,r.x,r.y},s);resize_u8(cropped,out,{r.width,r.height,r.output_width,r.output_height,c.channels,c.interpolation},s);check(cudaFree(cropped),"cudaFree RandomSizedBBoxSafeCrop");}catch(...){cudaFree(cropped);throw;}}
AtLeastOneBBoxRandomCropRectangle make_at_least_one_bbox_random_crop_rectangle(const AtLeastOneBBoxRandomCropConfig& c){validate_target_config(c.input_width,c.input_height,c.channels,c.boxes,c.box_count,c.erosion_factor);if(c.crop_width<=0||c.crop_height<=0||c.crop_width>c.input_width||c.crop_height>c.input_height)throw std::invalid_argument("invalid AtLeastOneBBoxRandomCrop dimensions");if((c.fallback_x<0)!=(c.fallback_y<0)||c.fallback_x<-1||c.fallback_y<-1||c.fallback_x+c.crop_width>c.input_width||c.fallback_y+c.crop_height>c.input_height)throw std::invalid_argument("invalid AtLeastOneBBoxRandomCrop fallback");if(c.box_count==0){const int x=c.fallback_x>=0?c.fallback_x:random_between(0,c.input_width-c.crop_width,c.seed+1),y=c.fallback_y>=0?c.fallback_y:random_between(0,c.input_height-c.crop_height,c.seed+2);return {x,y,c.crop_width,c.crop_height,static_cast<std::size_t>(-1),true};}const std::size_t selected=static_cast<std::size_t>(splitmix64(c.seed)%c.box_count);const BoxXYXY b=c.boxes[selected];const float ex=(b.x2-b.x1)*c.erosion_factor*0.5f,ey=(b.y2-b.y1)*c.erosion_factor*0.5f;const int x1=static_cast<int>(floor(b.x1+ex)),y1=static_cast<int>(floor(b.y1+ey)),x2=static_cast<int>(ceil(b.x2-ex)),y2=static_cast<int>(ceil(b.y2-ey));return {random_between(max(0,x1-c.crop_width+1),min(x2-1,c.input_width-c.crop_width),c.seed+1),random_between(max(0,y1-c.crop_height+1),min(y2-1,c.input_height-c.crop_height),c.seed+2),c.crop_width,c.crop_height,selected,false};}
void at_least_one_bbox_random_crop_u8(const std::uint8_t* in,std::uint8_t* out,const AtLeastOneBBoxRandomCropConfig& c,cudaStream_t s){if(!in||!out)throw std::invalid_argument("null AtLeastOneBBoxRandomCrop buffer");const auto r=make_at_least_one_bbox_random_crop_rectangle(c);random_crop_u8(in,out,{c.input_width,c.input_height,r.width,r.height,c.channels,r.x,r.y},s);}
CropNonEmptyMaskIfExistsRectangle make_crop_non_empty_mask_if_exists_rectangle(const ImageMaskView& source,const CropNonEmptyMaskIfExistsConfig& c){
  if(source.image.memory==MemorySpace::Device||(source.mask.valid()&&source.mask.memory==MemorySpace::Device)) throw std::invalid_argument("CUDA mask selection requires crop_non_empty_mask_if_exists");
  return choose_crop_host(source,c);
}
void crop_non_empty_mask_if_exists(const ImageMaskView& source,const MutableImageMaskView& destination,const CropNonEmptyMaskIfExistsConfig& c,cudaStream_t stream){
  if(!source.image.valid()||!destination.image.valid()||source.image.type!=DataType::UInt8||destination.image.type!=DataType::UInt8||source.image.layout!=Layout::HWC||destination.image.layout!=Layout::HWC||!source.image.contiguous()||!destination.image.contiguous()||source.image.memory!=MemorySpace::Device||destination.image.memory!=MemorySpace::Device) throw std::invalid_argument("CropNonEmptyMaskIfExists CUDA image views must be contiguous device HWC uint8");
  if(c.input_width>0&&c.input_width!=source.image.width||c.input_height>0&&c.input_height!=source.image.height||c.channels>0&&c.channels!=source.image.channels||destination.image.width!=c.crop_width||destination.image.height!=c.crop_height) throw std::invalid_argument("CropNonEmptyMaskIfExists image dimensions mismatch");
  if(source.mask.valid()&&(!destination.mask.valid()||source.mask.type!=DataType::UInt8||destination.mask.type!=DataType::UInt8||source.mask.layout!=Layout::HWC||destination.mask.layout!=Layout::HWC||!source.mask.contiguous()||!destination.mask.contiguous()||source.mask.memory!=MemorySpace::Device||destination.mask.memory!=MemorySpace::Device||source.mask.width!=source.image.width||source.mask.height!=source.image.height||destination.mask.width!=c.crop_width||destination.mask.height!=c.crop_height||destination.mask.channels!=source.mask.channels)) throw std::invalid_argument("CropNonEmptyMaskIfExists CUDA mask views mismatch");
  std::vector<std::uint8_t> host_mask; ImageMaskView selection_source=source;
  if(source.mask.valid()){
    host_mask.resize(static_cast<std::size_t>(source.mask.width)*source.mask.height*source.mask.channels);
    check(cudaMemcpyAsync(host_mask.data(),source.mask.data,host_mask.size(),cudaMemcpyDeviceToHost,stream),"cudaMemcpy CropNonEmptyMaskIfExists mask"); check(cudaStreamSynchronize(stream),"cudaStreamSynchronize CropNonEmptyMaskIfExists selection");
    selection_source.mask=make_hwc_u8_view(static_cast<const std::uint8_t*>(host_mask.data()),source.mask.width,source.mask.height,source.mask.channels,MemorySpace::Host);
  }
  const auto r=choose_crop_host(selection_source,c); const int n=std::max(c.crop_width*c.crop_height*c.channels,c.crop_width*c.crop_height*(source.mask.valid()?source.mask.channels:0));
  crop_non_empty_mask_kernel<<<(n+255)/256,256,0,stream>>>(static_cast<const std::uint8_t*>(source.image.data),source.mask.valid()?static_cast<const std::uint8_t*>(source.mask.data):nullptr,static_cast<std::uint8_t*>(destination.image.data),source.mask.valid()?static_cast<std::uint8_t*>(destination.mask.data):nullptr,c,r.x,r.y); check(cudaGetLastError(),"crop_non_empty_mask_if_exists_kernel");
}
void crop_non_empty_mask_if_exists_u8(const std::uint8_t* image,const std::uint8_t* mask,std::uint8_t* output_image,std::uint8_t* output_mask,const CropNonEmptyMaskIfExistsConfig& c,cudaStream_t stream){
  if(!image||!output_image||(mask&&!output_mask)) throw std::invalid_argument("null CropNonEmptyMaskIfExists buffer");
  if(c.input_width<=0||c.input_height<=0||c.channels<=0||c.mask_channels<=0) throw std::invalid_argument("invalid CropNonEmptyMaskIfExists dimensions");
  const auto image_in=make_hwc_u8_view(image,c.input_width,c.input_height,c.channels,MemorySpace::Device); const auto image_out=make_hwc_u8_view(output_image,c.crop_width,c.crop_height,c.channels,MemorySpace::Device);
  ImageMaskView source{image_in,mask?make_hwc_u8_view(mask,c.input_width,c.input_height,c.mask_channels,MemorySpace::Device):ImageView{}}; MutableImageMaskView destination{image_out,mask?make_hwc_u8_view(output_mask,c.crop_width,c.crop_height,c.mask_channels,MemorySpace::Device):MutableImageView{}};
  crop_non_empty_mask_if_exists(source,destination,c,stream);
}
void square_symmetric_pad_u8(const std::uint8_t* in,std::uint8_t* out,const PadConfig& c,cudaStream_t s){if(c.output_width!=c.output_height||c.output_width<max(c.input_width,c.input_height))throw std::invalid_argument("invalid square symmetric pad configuration");pad_to_size_u8(in,out,c,s);}
void pad_to_size_u8(const std::uint8_t* in,std::uint8_t* out,const PadConfig& c,cudaStream_t s){valid(c.input_width,c.input_height,c.channels);if(!in||!out||c.output_width<c.input_width||c.output_height<c.input_height||static_cast<int>(c.border)<0||static_cast<int>(c.border)>2)throw std::invalid_argument("invalid pad configuration");int n=c.output_width*c.output_height*c.channels;pad_kernel<<<(n+255)/256,256,0,s>>>(in,out,c);check(cudaGetLastError(),"pad_kernel");}
void crop_and_pad_u8(const std::uint8_t* in,std::uint8_t* out,const CropPadConfig& c,cudaStream_t s){valid(c.input_width,c.input_height,c.channels);int ow=c.input_width+c.left+c.right,oh=c.input_height+c.top+c.bottom;if(!in||!out||ow<=0||oh<=0)throw std::invalid_argument("invalid crop and pad configuration");int n=ow*oh*c.channels;crop_pad_kernel<<<(n+255)/256,256,0,s>>>(in,out,c,ow,oh);check(cudaGetLastError(),"crop_pad_kernel");}
void pad_to_fixed_size_u8(const std::uint8_t* i,std::uint8_t* o,const PadConfig& c,cudaStream_t s){pad_to_size_u8(i,o,c,s);} void center_pad_to_fixed_size_u8(const std::uint8_t* i,std::uint8_t* o,const PadConfig& c,cudaStream_t s){pad_to_size_u8(i,o,c,s);} void pad_to_square_u8(const std::uint8_t* i,std::uint8_t* o,const PadConfig& c,cudaStream_t s){square_symmetric_pad_u8(i,o,c,s);} void center_pad_to_square_u8(const std::uint8_t* i,std::uint8_t* o,const PadConfig& c,cudaStream_t s){square_symmetric_pad_u8(i,o,c,s);} void crop_to_fixed_size_u8(const std::uint8_t* i,std::uint8_t* o,const RandomCropConfig& c,cudaStream_t s){random_crop_u8(i,o,c,s);} void center_crop_to_fixed_size_u8(const std::uint8_t* i,std::uint8_t* o,const CenterCropConfig& c,cudaStream_t s){center_crop_u8(i,o,c,s);} void crop_to_square_u8(const std::uint8_t* i,std::uint8_t* o,const CenterCropConfig& c,cudaStream_t s){if(c.output_width!=c.output_height)throw std::invalid_argument("square crop requires equal output dimensions");center_crop_u8(i,o,c,s);} void center_crop_to_square_u8(const std::uint8_t* i,std::uint8_t* o,const CenterCropConfig& c,cudaStream_t s){crop_to_square_u8(i,o,c,s);}
namespace {
void validate_anchor_cuda(SizeAnchor a){if(a!=SizeAnchor::TopLeft&&a!=SizeAnchor::Center)throw std::invalid_argument("invalid size anchor");}
void validate_rounding_cuda(SizeRounding r){if(r!=SizeRounding::Floor&&r!=SizeRounding::Ceil&&r!=SizeRounding::Nearest)throw std::invalid_argument("invalid size rounding");}
int rounded_cuda(double x,SizeRounding r){if(!std::isfinite(x)||x<1||x>std::numeric_limits<int>::max())throw std::invalid_argument("size target is outside integer range");if(r==SizeRounding::Floor)return static_cast<int>(floor(x));if(r==SizeRounding::Ceil)return static_cast<int>(ceil(x));if(r==SizeRounding::Nearest)return static_cast<int>(floor(x+.5));throw std::invalid_argument("invalid size rounding");}
int multiple_cuda(int n,int m,bool pad){if(n<=0||m<=0)throw std::invalid_argument("size dimensions and multiples must be positive");long long q=pad?(static_cast<long long>(n)+m-1)/m:n/m;if(q<1||q*m>std::numeric_limits<int>::max())throw std::invalid_argument("multiple target overflows");return static_cast<int>(q*m);}
int power_cuda(int n,int b,bool pad){if(n<=0||b<2)throw std::invalid_argument("size dimensions and power base are invalid");long long p=1;while(p<n){if(p>std::numeric_limits<int>::max()/b)throw std::invalid_argument("power target overflows");p*=b;}if(!pad&&p>n)p/=b;return static_cast<int>(p);}
SizeTransformDimensions aspect_cuda(const AspectRatioConfig& c,bool pad){valid(c.input_width,c.input_height,c.channels);if(!std::isfinite(c.aspect_ratio)||c.aspect_ratio<=0)throw std::invalid_argument("aspect ratio must be finite and positive");validate_anchor_cuda(c.anchor);validate_rounding_cuda(c.rounding);const double current=static_cast<double>(c.input_width)/c.input_height;int w=c.input_width,h=c.input_height;if((pad&&current<c.aspect_ratio)||(!pad&&current>c.aspect_ratio))w=rounded_cuda(static_cast<double>(c.input_height)*c.aspect_ratio,c.rounding);else if((pad&&current>c.aspect_ratio)||(!pad&&current<c.aspect_ratio))h=rounded_cuda(static_cast<double>(c.input_width)/c.aspect_ratio,c.rounding);if(pad){w=max(w,c.input_width);h=max(h,c.input_height);}else{w=min(w,c.input_width);h=min(h,c.input_height);}return {w,h};}
void launch_size(const std::uint8_t* i,std::uint8_t* o,int iw,int ih,int c,int ow,int oh,std::uint8_t value,PadBorder border,SizeAnchor anchor,bool pad,cudaStream_t s){valid(iw,ih,c);if(!i||!o||ow<=0||oh<=0||static_cast<int>(border)<0||static_cast<int>(border)>2||((pad&&(ow<iw||oh<ih))||(!pad&&(ow>iw||oh>ih))))throw std::invalid_argument("invalid size transform configuration");const int n=ow*oh*c;size_transform_kernel<<<(n+255)/256,256,0,s>>>(i,o,iw,ih,ow,oh,c,value,border,anchor,pad);check(cudaGetLastError(),"size_transform_kernel");}
}
SizeTransformDimensions make_pad_to_multiples_of_dimensions(const MultiplesOfConfig& c){valid(c.input_width,c.input_height,c.channels);validate_anchor_cuda(c.anchor);return {multiple_cuda(c.input_width,c.multiple_width,true),multiple_cuda(c.input_height,c.multiple_height,true)};}
SizeTransformDimensions make_crop_to_multiples_of_dimensions(const MultiplesOfConfig& c){valid(c.input_width,c.input_height,c.channels);validate_anchor_cuda(c.anchor);return {multiple_cuda(c.input_width,c.multiple_width,false),multiple_cuda(c.input_height,c.multiple_height,false)};}
SizeTransformDimensions make_pad_to_powers_of_dimensions(const PowersOfConfig& c){valid(c.input_width,c.input_height,c.channels);validate_anchor_cuda(c.anchor);return {power_cuda(c.input_width,c.base,true),power_cuda(c.input_height,c.base,true)};}
SizeTransformDimensions make_crop_to_powers_of_dimensions(const PowersOfConfig& c){valid(c.input_width,c.input_height,c.channels);validate_anchor_cuda(c.anchor);return {power_cuda(c.input_width,c.base,false),power_cuda(c.input_height,c.base,false)};}
SizeTransformDimensions make_pad_to_aspect_ratio_dimensions(const AspectRatioConfig& c){return aspect_cuda(c,true);}
SizeTransformDimensions make_crop_to_aspect_ratio_dimensions(const AspectRatioConfig& c){return aspect_cuda(c,false);}
void pad_to_multiples_of_u8(const std::uint8_t* i,std::uint8_t* o,const MultiplesOfConfig& c,cudaStream_t s){auto d=make_pad_to_multiples_of_dimensions(c);launch_size(i,o,c.input_width,c.input_height,c.channels,d.width,d.height,c.value,c.border,c.anchor,true,s);}
void crop_to_multiples_of_u8(const std::uint8_t* i,std::uint8_t* o,const MultiplesOfConfig& c,cudaStream_t s){auto d=make_crop_to_multiples_of_dimensions(c);launch_size(i,o,c.input_width,c.input_height,c.channels,d.width,d.height,0,PadBorder::Constant,c.anchor,false,s);}
void pad_to_powers_of_u8(const std::uint8_t* i,std::uint8_t* o,const PowersOfConfig& c,cudaStream_t s){auto d=make_pad_to_powers_of_dimensions(c);launch_size(i,o,c.input_width,c.input_height,c.channels,d.width,d.height,c.value,c.border,c.anchor,true,s);}
void crop_to_powers_of_u8(const std::uint8_t* i,std::uint8_t* o,const PowersOfConfig& c,cudaStream_t s){auto d=make_crop_to_powers_of_dimensions(c);launch_size(i,o,c.input_width,c.input_height,c.channels,d.width,d.height,0,PadBorder::Constant,c.anchor,false,s);}
void pad_to_aspect_ratio_u8(const std::uint8_t* i,std::uint8_t* o,const AspectRatioConfig& c,cudaStream_t s){auto d=make_pad_to_aspect_ratio_dimensions(c);launch_size(i,o,c.input_width,c.input_height,c.channels,d.width,d.height,c.value,c.border,c.anchor,true,s);}
void crop_to_aspect_ratio_u8(const std::uint8_t* i,std::uint8_t* o,const AspectRatioConfig& c,cudaStream_t s){auto d=make_crop_to_aspect_ratio_dimensions(c);launch_size(i,o,c.input_width,c.input_height,c.channels,d.width,d.height,0,PadBorder::Constant,c.anchor,false,s);}
void center_pad_to_multiples_of_u8(const std::uint8_t* i,std::uint8_t* o,MultiplesOfConfig c,cudaStream_t s){c.anchor=SizeAnchor::Center;pad_to_multiples_of_u8(i,o,c,s);} void center_crop_to_multiples_of_u8(const std::uint8_t* i,std::uint8_t* o,MultiplesOfConfig c,cudaStream_t s){c.anchor=SizeAnchor::Center;crop_to_multiples_of_u8(i,o,c,s);} void center_pad_to_powers_of_u8(const std::uint8_t* i,std::uint8_t* o,PowersOfConfig c,cudaStream_t s){c.anchor=SizeAnchor::Center;pad_to_powers_of_u8(i,o,c,s);} void center_crop_to_powers_of_u8(const std::uint8_t* i,std::uint8_t* o,PowersOfConfig c,cudaStream_t s){c.anchor=SizeAnchor::Center;crop_to_powers_of_u8(i,o,c,s);} void center_pad_to_aspect_ratio_u8(const std::uint8_t* i,std::uint8_t* o,AspectRatioConfig c,cudaStream_t s){c.anchor=SizeAnchor::Center;pad_to_aspect_ratio_u8(i,o,c,s);} void center_crop_to_aspect_ratio_u8(const std::uint8_t* i,std::uint8_t* o,AspectRatioConfig c,cudaStream_t s){c.anchor=SizeAnchor::Center;crop_to_aspect_ratio_u8(i,o,c,s);}
void keep_size_by_resize_u8(const std::uint8_t* i,std::uint8_t* o,const KeepSizeByResizeConfig& c,cudaStream_t s){valid(c.input_width,c.input_height,c.channels);if(!i||!o||c.intermediate_width<=0||c.intermediate_height<=0||static_cast<int>(c.interpolation)<0||static_cast<int>(c.interpolation)>2)throw std::invalid_argument("invalid KeepSizeByResize configuration");if(c.intermediate_width==c.input_width&&c.intermediate_height==c.input_height){check(cudaMemcpyAsync(o,i,static_cast<std::size_t>(c.input_width)*c.input_height*c.channels,cudaMemcpyDeviceToDevice,s),"cudaMemcpy KeepSizeByResize");return;}const std::size_t bytes=static_cast<std::size_t>(c.intermediate_width)*c.intermediate_height*c.channels;std::uint8_t* tmp=nullptr;check(cudaMalloc(&tmp,bytes),"cudaMalloc KeepSizeByResize");try{resize_u8(i,tmp,{c.input_width,c.input_height,c.intermediate_width,c.intermediate_height,c.channels,c.interpolation},s);resize_u8(tmp,o,{c.intermediate_width,c.intermediate_height,c.input_width,c.input_height,c.channels,c.interpolation},s);check(cudaFree(tmp),"cudaFree KeepSizeByResize");}catch(...){cudaFree(tmp);throw;}}
void keep_size_by_resize_u8(const std::uint8_t* i,std::uint8_t* o,const ResizeConfig& c,cudaStream_t s){keep_size_by_resize_u8(i,o,KeepSizeByResizeConfig{c.input_width,c.input_height,c.channels,c.output_width,c.output_height,c.interpolation},s);}
}
