#include "augmatch/noise.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ unsigned long long mix(unsigned long long x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__device__ float uni(unsigned long long x){return (float)((mix(x)>>11)*(1.0/9007199254740992.0));}
__device__ float normal(unsigned long long x){float a=fmaxf(uni(x),1.0e-7f);return sqrtf(-2.0f*logf(a))*cosf(6.28318530718f*uni(x^0xd1b54a32d192ed03ULL));}
__device__ unsigned long long key(unsigned long long s,int t,int x,int y,int ch,unsigned long long tag){return s^(unsigned long long)t*0x632be59bd9b4e019ULL^(unsigned long long)x*0x8cb92baa2f2f6f7dULL^(unsigned long long)y*0x9e3779b97f4a7c15ULL^(unsigned long long)ch*0xbf58476d1ce4e5b9ULL^tag;}
__device__ float state(TemporalBatchConfig c,int t,int x,int y,int ch,unsigned long long tag){float s=0.0f,a=sqrtf(fmaxf(0.0f,1.0f-c.temporal_correlation*c.temporal_correlation));for(int q=0;q<=t;++q)s=(q?c.temporal_correlation*s:0.0f)+a*normal(key(c.seed,q,x,y,ch,tag));return s;}
__device__ float clip(float v,float lo,float hi){return fmaxf(lo,fminf(hi,v));}
__global__ void gaussian_kernel(const float* in,float* out,TemporalGaussianNoiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.frames*c.height*c.width*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=(i/c.channels/c.width)%c.height,t=i/(c.channels*c.width*c.height);out[i]=clip(in[i]+c.stddev*state(c,t,x,y,ch,0x5447415553534941ULL),c.clip_min,c.clip_max);}
__global__ void shot_kernel(const float* in,float* out,TemporallyCorrelatedShotNoiseConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.frames*c.height*c.width*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=(i/c.channels/c.width)%c.height,t=i/(c.channels*c.width*c.height);float signal=fmaxf(0.0f,in[i]),lambda=signal*c.photons_per_unit,noise=lambda>0.0f?sqrtf(lambda)*state(c,t,x,y,ch,0x5453484f545f4e4fULL)/c.photons_per_unit:0.0f;out[i]=clip(signal+noise,c.clip_min,c.clip_max);}
__global__ void read_kernel(const float* in,float* out,TemporalReadNoiseCorrelationConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.frames*c.height*c.width*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=(i/c.channels/c.width)%c.height,t=i/(c.channels*c.width*c.height);out[i]=clip(in[i]+c.stddev*state(c,t,x,y,ch,0x54524541445f4e4fULL),c.clip_min,c.clip_max);}
__global__ void flicker_kernel(const float* in,float* out,FlickerConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.frames*c.height*c.width*c.channels;if(i>=n)return;int t=i/(c.channels*c.width*c.height);out[i]=clip(in[i]*(1.0f+c.stddev*state(c,t,0,0,0,0x464c49434b4552ULL)),c.clip_min,c.clip_max);}
__global__ void wb_kernel(const float* in,float* out,WhiteBalanceFlickerConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.frames*c.height*c.width*c.channels;if(i>=n)return;int ch=i%c.channels,t=i/(c.channels*c.width*c.height);float sd=ch==0?c.red_stddev:(ch==1?c.green_stddev:c.blue_stddev);out[i]=clip(in[i]*(1.0f+sd*state(c,t,0,0,0,0x5742464c49434b52ULL)),c.clip_min,c.clip_max);}
__global__ void row_phase_kernel(const float* in,float* out,RowNoisePhaseChangesConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.frames*c.height*c.width*c.channels;if(i>=n)return;int y=(i/c.channels/c.width)%c.height,t=i/(c.channels*c.width*c.height);float u=uni(key(c.seed,t,0,y,0,0x525057484153455fULL));float phase=u<c.phase_change_probability?-1.0f:1.0f;float off=phase*c.row_stddev*state(c,t,0,y,0,0x52574e4f495345ULL);out[i]=clip(in[i]+off,c.clip_min,c.clip_max);}
__global__ void drift_kernel(const float* in,float* out,FixedPatternNoiseDriftConfig c){int i=blockIdx.x*blockDim.x+threadIdx.x,n=c.frames*c.height*c.width*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=(i/c.channels/c.width)%c.height,t=i/(c.channels*c.width*c.height),p=(y*c.width+x)*c.channels+ch;float base=c.base_map?c.base_map[p]:c.base_stddev*normal(key(c.seed,0,x,y,ch,0x46504e424153455fULL));out[i]=clip(in[i]+base+c.drift_stddev*state(c,t,x,y,ch,0x46504e4452494654ULL),c.clip_min,c.clip_max);}
void check(cudaError_t e,const char* p){if(e!=cudaSuccess)throw std::runtime_error(std::string(p)+": "+cudaGetErrorString(e));}
void valid(const TemporalBatchConfig& c,const float* in,const float* out){if(c.frames<=0||c.height<=0||c.width<=0||c.channels<=0||!in||!out||!isfinite(c.temporal_correlation)||c.temporal_correlation<-1||c.temporal_correlation>1||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min)throw std::invalid_argument("invalid temporal batch configuration");}
void stddev(float v,const char* m){if(!isfinite(v)||v<0)throw std::invalid_argument(m);}
}
void temporal_gaussian_noise_f32(const float* i,float* o,const TemporalGaussianNoiseConfig& c,cudaStream_t s){valid(c,i,o);stddev(c.stddev,"invalid temporal Gaussian configuration");int n=c.frames*c.height*c.width*c.channels;gaussian_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"temporal_gaussian_noise");}
void temporally_correlated_shot_noise_f32(const float* i,float* o,const TemporallyCorrelatedShotNoiseConfig& c,cudaStream_t s){valid(c,i,o);stddev(c.photons_per_unit,"invalid temporal shot-noise configuration");if(c.photons_per_unit<=0)throw std::invalid_argument("photons_per_unit must be positive");int n=c.frames*c.height*c.width*c.channels;shot_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"temporal_shot_noise");}
void temporal_read_noise_correlation_f32(const float* i,float* o,const TemporalReadNoiseCorrelationConfig& c,cudaStream_t s){valid(c,i,o);stddev(c.stddev,"invalid temporal read-noise configuration");int n=c.frames*c.height*c.width*c.channels;read_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"temporal_read_noise");}
void flicker_f32(const float* i,float* o,const FlickerConfig& c,cudaStream_t s){valid(c,i,o);stddev(c.stddev,"invalid flicker configuration");int n=c.frames*c.height*c.width*c.channels;flicker_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"flicker");}
void exposure_flicker_f32(const float* i,float* o,const ExposureFlickerConfig& c,cudaStream_t s){FlickerConfig z;static_cast<TemporalBatchConfig&>(z)=static_cast<const TemporalBatchConfig&>(c);z.stddev=c.stddev;flicker_f32(i,o,z,s);}
void white_balance_flicker_f32(const float* i,float* o,const WhiteBalanceFlickerConfig& c,cudaStream_t s){valid(c,i,o);stddev(c.red_stddev,"invalid white-balance flicker configuration");stddev(c.green_stddev,"invalid white-balance flicker configuration");stddev(c.blue_stddev,"invalid white-balance flicker configuration");int n=c.frames*c.height*c.width*c.channels;wb_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"white_balance_flicker");}
void gain_flicker_f32(const float* i,float* o,const GainFlickerConfig& c,cudaStream_t s){FlickerConfig z;static_cast<TemporalBatchConfig&>(z)=static_cast<const TemporalBatchConfig&>(c);z.stddev=c.stddev;flicker_f32(i,o,z,s);}
void fixed_pattern_noise_drift_f32(const float* i,float* o,const FixedPatternNoiseDriftConfig& c,cudaStream_t s){valid(c,i,o);stddev(c.base_stddev,"invalid FPN drift configuration");stddev(c.drift_stddev,"invalid FPN drift configuration");int n=c.frames*c.height*c.width*c.channels;drift_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"fixed_pattern_noise_drift");}
void row_noise_phase_changes_f32(const float* i,float* o,const RowNoisePhaseChangesConfig& c,cudaStream_t s){valid(c,i,o);stddev(c.row_stddev,"invalid row-noise configuration");if(!isfinite(c.phase_change_probability)||c.phase_change_probability<0||c.phase_change_probability>1)throw std::invalid_argument("phase_change_probability must be in [0,1]");int n=c.frames*c.height*c.width*c.channels;row_phase_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"row_noise_phase_changes");}
}
