#include "augmatch/noise.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
#include <limits>
namespace augmatch { namespace {
void valid(const TemporalBatchConfig& c,const float* in,const float* out) {
  if(c.frames<=0||c.height<=0||c.width<=0||c.channels<=0||!in||!out||!std::isfinite(c.temporal_correlation)||c.temporal_correlation<-1.0f||c.temporal_correlation>1.0f||!std::isfinite(c.clip_min)||!std::isfinite(c.clip_max)||c.clip_max<c.clip_min) throw std::invalid_argument("invalid temporal batch configuration");
}
std::uint64_t mix(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
float uni(std::uint64_t x){return static_cast<float>((mix(x)>>11)*(1.0/9007199254740992.0));}
float normal(std::uint64_t x){const float a=std::max(uni(x),std::numeric_limits<float>::min());return std::sqrt(-2.0f*std::log(a))*std::cos(6.28318530718f*uni(x^0xd1b54a32d192ed03ULL));}
std::uint64_t key(std::uint64_t s,int t,int x,int y,int ch,std::uint64_t tag){return s^static_cast<std::uint64_t>(t)*0x632be59bd9b4e019ULL^static_cast<std::uint64_t>(x)*0x8cb92baa2f2f6f7dULL^static_cast<std::uint64_t>(y)*0x9e3779b97f4a7c15ULL^static_cast<std::uint64_t>(ch)*0xbf58476d1ce4e5b9ULL^tag;}
float state(const TemporalBatchConfig& c,int t,int x,int y,int ch,std::uint64_t tag){float s=0.0f;const float a=std::sqrt(std::max(0.0f,1.0f-c.temporal_correlation*c.temporal_correlation));for(int q=0;q<=t;++q)s=(q?c.temporal_correlation*s:0.0f)+a*normal(key(c.seed,q,x,y,ch,tag));return s;}
float clip(float v,float lo,float hi){return std::max(lo,std::min(hi,v));}
void validate_std(float v,const char* what){if(!std::isfinite(v)||v<0.0f)throw std::invalid_argument(what);}
}
void temporal_gaussian_noise_f32(const float* in,float* out,const TemporalGaussianNoiseConfig& c,cudaStream_t){valid(c,in,out);validate_std(c.stddev,"invalid temporal Gaussian configuration");for(int t=0;t<c.frames;++t)for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const std::size_t i=(((std::size_t)t*c.height+y)*c.width+x)*c.channels+ch;out[i]=clip(in[i]+c.stddev*state(c,t,x,y,ch,0x5447415553534941ULL),c.clip_min,c.clip_max);}}
void temporally_correlated_shot_noise_f32(const float* in,float* out,const TemporallyCorrelatedShotNoiseConfig& c,cudaStream_t){valid(c,in,out);validate_std(c.photons_per_unit,"invalid temporal shot-noise configuration");if(c.photons_per_unit<=0)throw std::invalid_argument("photons_per_unit must be positive");for(int t=0;t<c.frames;++t)for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const std::size_t i=(((std::size_t)t*c.height+y)*c.width+x)*c.channels+ch;const float signal=std::max(0.0f,in[i]),lambda=signal*c.photons_per_unit;const float noise=lambda>0.0f?std::sqrt(lambda)*state(c,t,x,y,ch,0x5453484f545f4e4fULL)/c.photons_per_unit:0.0f;out[i]=clip(signal+noise,c.clip_min,c.clip_max);}}
void temporal_read_noise_correlation_f32(const float* in,float* out,const TemporalReadNoiseCorrelationConfig& c,cudaStream_t){valid(c,in,out);validate_std(c.stddev,"invalid temporal read-noise configuration");for(int t=0;t<c.frames;++t)for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const std::size_t i=(((std::size_t)t*c.height+y)*c.width+x)*c.channels+ch;out[i]=clip(in[i]+c.stddev*state(c,t,x,y,ch,0x54524541445f4e4fULL),c.clip_min,c.clip_max);}}
void flicker_f32(const float* in,float* out,const FlickerConfig& c,cudaStream_t){valid(c,in,out);validate_std(c.stddev,"invalid flicker configuration");for(int t=0;t<c.frames;++t){const float f=1.0f+c.stddev*state(c,t,0,0,0,0x464c49434b4552ULL);for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const std::size_t i=(((std::size_t)t*c.height+y)*c.width+x)*c.channels+ch;out[i]=clip(in[i]*f,c.clip_min,c.clip_max);}}}
void exposure_flicker_f32(const float* in,float* out,const ExposureFlickerConfig& c,cudaStream_t){FlickerConfig z;static_cast<TemporalBatchConfig&>(z)=static_cast<const TemporalBatchConfig&>(c);z.stddev=c.stddev;flicker_f32(in,out,z,nullptr);}
void white_balance_flicker_f32(const float* in,float* out,const WhiteBalanceFlickerConfig& c,cudaStream_t){valid(c,in,out);validate_std(c.red_stddev,"invalid white-balance flicker configuration");validate_std(c.green_stddev,"invalid white-balance flicker configuration");validate_std(c.blue_stddev,"invalid white-balance flicker configuration");const float sd[3]={c.red_stddev,c.green_stddev,c.blue_stddev};for(int t=0;t<c.frames;++t)for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const std::size_t i=(((std::size_t)t*c.height+y)*c.width+x)*c.channels+ch;const float s=sd[std::min(ch,2)];out[i]=clip(in[i]*(1.0f+s*state(c,t,0,0,ch,0x5742464c49434b52ULL)),c.clip_min,c.clip_max);}}
void gain_flicker_f32(const float* in,float* out,const GainFlickerConfig& c,cudaStream_t){FlickerConfig z;static_cast<TemporalBatchConfig&>(z)=static_cast<const TemporalBatchConfig&>(c);z.stddev=c.stddev;flicker_f32(in,out,z,nullptr);}
void fixed_pattern_noise_drift_f32(const float* in,float* out,const FixedPatternNoiseDriftConfig& c,cudaStream_t){valid(c,in,out);validate_std(c.base_stddev,"invalid FPN drift configuration");validate_std(c.drift_stddev,"invalid FPN drift configuration");const std::size_t plane=(std::size_t)c.height*c.width*c.channels;for(int y=0;y<c.height;++y)for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const std::size_t p=((std::size_t)y*c.width+x)*c.channels+ch;const float base=c.base_map?c.base_map[p]:c.base_stddev*normal(key(c.seed,0,x,y,ch,0x46504e424153455fULL));for(int t=0;t<c.frames;++t){const std::size_t i=(std::size_t)t*plane+p;out[i]=clip(in[i]+base+c.drift_stddev*state(c,t,x,y,ch,0x46504e4452494654ULL),c.clip_min,c.clip_max);}}}
void row_noise_phase_changes_f32(const float* in,float* out,const RowNoisePhaseChangesConfig& c,cudaStream_t){valid(c,in,out);validate_std(c.row_stddev,"invalid row-noise configuration");if(!std::isfinite(c.phase_change_probability)||c.phase_change_probability<0||c.phase_change_probability>1)throw std::invalid_argument("phase_change_probability must be in [0,1]");const std::size_t plane=(std::size_t)c.height*c.width*c.channels;for(int t=0;t<c.frames;++t)for(int y=0;y<c.height;++y){const float phase=uni(key(c.seed,t,0,y,0,0x525057484153455fULL))<c.phase_change_probability?-1.0f:1.0f;const float offset=phase*c.row_stddev*state(c,t,0,y,0,0x52574e4f495345ULL);for(int x=0;x<c.width;++x)for(int ch=0;ch<c.channels;++ch){const std::size_t i=(std::size_t)t*plane+((std::size_t)y*c.width+x)*c.channels+ch;out[i]=clip(in[i]+offset,c.clip_min,c.clip_max);}}}
}
