#include "augmatch/transport.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ unsigned long long mix(unsigned long long x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__device__ float unit(unsigned long long x){return (float)((mix(x)>>11)*(1.0/9007199254740992.0));}
__device__ int clampi(int v,int n){return max(0,min(n-1,v));}
__device__ unsigned long long key(unsigned long long seed,size_t i){return seed^((unsigned long long)i*0x632be59bd9b4e019ULL);}
__global__ void trunc_kernel(const unsigned char* in,unsigned char* out,TransportByteConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;if(i<c.bytes)out[i]=i<c.preserve_bytes?in[i]:c.fill;}
__global__ void flip_kernel(const unsigned char* in,unsigned char* out,TransportByteConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;if(i>=c.bytes)return;unsigned char v=in[i];if(unit(key(c.seed,i))<c.probability){unsigned int m=c.bit_mask?c.bit_mask:(1u<<(mix(key(c.seed,i)^0xa5a5a5a5ULL)%8));v=(unsigned char)(v^(unsigned char)m);}out[i]=v;}
__device__ size_t fi(const TransportFrameConfig& c,int x,int y,int ch){return ((size_t)y*c.width+x)*c.channels+ch;}
__global__ void quant_kernel(const unsigned char* in,unsigned char* out,TransportFrameConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)c.width*c.height*c.channels;if(i>=n)return;int q=((int)in[i]+c.quant_step/2)/c.quant_step*c.quant_step;out[i]=(unsigned char)min(255,q);}
__global__ void deblock_kernel(const unsigned char* in,unsigned char* out,TransportFrameConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)c.width*c.height*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=i/(c.width*c.channels);float v=in[i];if(x%c.block_size==0&&x>0)v=(1-c.strength)*v+c.strength*.5f*(in[fi(c,x-1,y,ch)]+in[i]);if(y%c.block_size==0&&y>0)v=(1-c.strength)*v+c.strength*.5f*(in[fi(c,x,y-1,ch)]+in[i]);out[i]=(unsigned char)floorf(fminf(255.0f,fmaxf(0.0f,v))+.5f);}
__global__ void loss_kernel(const unsigned char* in,unsigned char* out,TransportFrameConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)c.width*c.height*c.channels;if(i>=n)return;int x=(i/c.channels)%c.width,y=i/(c.width*c.channels),bx=(c.width+c.block_size-1)/c.block_size;int b=(y/c.block_size)*bx+x/c.block_size;bool lost=c.block_mask?c.block_mask[b]!=0:unit(key(c.seed,(size_t)b))<c.probability;out[i]=lost?c.fill:in[i];}
__global__ void plane_kernel(const unsigned char* in,unsigned char* out,TransportPlaneConfig c){int x=blockIdx.x*blockDim.x+threadIdx.x,y=blockIdx.y*blockDim.y+threadIdx.y;if(x>=c.stride||y>=c.height)return;if(x>=c.width){out[(size_t)y*c.stride+x]=in[(size_t)y*c.stride+x];return;}int sx=clampi(x-c.dx,c.width),sy=clampi(y-c.dy,c.height);out[(size_t)y*c.stride+x]=in[(size_t)sy*c.stride+sx];}
__global__ void raw16_kernel(const unsigned short* in,unsigned short* out,RawBayerTransportCorruptionConfig c){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,n=(size_t)c.stride*c.height;if(i>=n)return;int x=i%c.stride,y=i/c.stride;if(x>=c.width){out[i]=in[i];return;}bool bad=(c.mask&&c.mask[(size_t)y*c.width+x])||unit(key(c.seed,i))<c.probability;unsigned int maxv=c.bit_depth==16?65535u:((1u<<c.bit_depth)-1u);out[i]=bad?(c.xor_mask?(unsigned short)(in[i]^c.xor_mask):c.fill):(unsigned short)min((unsigned int)in[i],maxv);}
void check(cudaError_t e,const char* where){if(e!=cudaSuccess)throw std::runtime_error(std::string(where)+": "+cudaGetErrorString(e));}
void valid_bytes(const void* i,const void* o,size_t n){if(!i||!o||!n)throw std::invalid_argument("invalid transport byte buffers");}
void valid_frame(const void* i,const void* o,const TransportFrameConfig& c){if(!i||!o||c.width<=0||c.height<=0||c.channels<=0||c.block_size<=0||c.quant_step<=0||!isfinite(c.strength)||c.strength<0||c.strength>1||!isfinite(c.probability)||c.probability<0||c.probability>1)throw std::invalid_argument("invalid transport frame configuration");}
}
void truncated_frame_u8(const std::uint8_t* i,std::uint8_t* o,const TransportByteConfig& c,cudaStream_t s){valid_bytes(i,o,c.bytes);if(c.preserve_bytes>c.bytes)throw std::invalid_argument("preserve_bytes exceeds frame size");trunc_kernel<<<(c.bytes+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"truncated_frame_kernel");}
void bit_flips_u8(const std::uint8_t* i,std::uint8_t* o,const TransportByteConfig& c,cudaStream_t s){valid_bytes(i,o,c.bytes);if(!isfinite(c.probability)||c.probability<0||c.probability>1)throw std::invalid_argument("bit-flip probability must be in [0,1]");flip_kernel<<<(c.bytes+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"bit_flip_kernel");}
void block_quantization_u8(const std::uint8_t* i,std::uint8_t* o,const TransportFrameConfig& c,cudaStream_t s){valid_frame(i,o,c);size_t n=(size_t)c.width*c.height*c.channels;quant_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"block_quantization_kernel");}
void deblocking_filter_mismatch_u8(const std::uint8_t* i,std::uint8_t* o,const TransportFrameConfig& c,cudaStream_t s){valid_frame(i,o,c);size_t n=(size_t)c.width*c.height*c.channels;deblock_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"deblocking_kernel");}
void packet_loss_macroblocks_u8(const std::uint8_t* i,std::uint8_t* o,const TransportFrameConfig& c,cudaStream_t s){valid_frame(i,o,c);size_t n=(size_t)c.width*c.height*c.channels;loss_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"packet_loss_kernel");}
void chroma_plane_misalignment_u8(const std::uint8_t* i,std::uint8_t* o,const TransportPlaneConfig& c,cudaStream_t s){if(!i||!o||c.width<=0||c.height<=0||c.stride<c.width)throw std::invalid_argument("invalid transport plane configuration");dim3 b(16,16),g((c.stride+15)/16,(c.height+15)/16);plane_kernel<<<g,b,0,s>>>(i,o,c);check(cudaGetLastError(),"chroma_plane_kernel");}
void raw_bayer_transport_corruption_u16(const std::uint16_t* i,std::uint16_t* o,const RawBayerTransportCorruptionConfig& c,cudaStream_t s){if(!i||!o||c.width<=0||c.height<=0||c.stride<c.width||c.bit_depth<=0||c.bit_depth>16||!isfinite(c.probability)||c.probability<0||c.probability>1)throw std::invalid_argument("invalid raw Bayer transport configuration");size_t n=(size_t)c.stride*c.height;raw16_kernel<<<(n+255)/256,256,0,s>>>(i,o,c);check(cudaGetLastError(),"raw_bayer_transport_kernel");}
void raw_bayer_transport_corruption_u8(const std::uint8_t* i,std::uint8_t* o,const TransportByteConfig& c,cudaStream_t s){bit_flips_u8(i,o,c,s);}
}
