#pragma once
#include "augmatch/video_codec.hpp"
#include <algorithm>
#include <stdexcept>
#include <string>
extern "C" {
#include <libavcodec/avcodec.h>
#include <libavutil/imgutils.h>
#include <libavutil/opt.h>
#include <libswscale/swscale.h>
}
namespace augmatch { namespace video_detail {
inline AVCodecID id(VideoCodec c){ switch(c){case VideoCodec::H264:return AV_CODEC_ID_H264;case VideoCodec::HEVC:return AV_CODEC_ID_HEVC;case VideoCodec::AV1:return AV_CODEC_ID_AV1;} throw std::invalid_argument("unknown video codec"); }
inline void check(int r,const char* what){if(r<0) throw std::runtime_error(std::string(what)+" (FFmpeg error "+std::to_string(r)+")");}
inline std::size_t bytes(int w,int h,int c){if(w<=0||h<=0||(w&1)||(h&1)||(c!=1&&c!=3))throw std::invalid_argument("codec requires positive even dimensions and one or three channels");auto n=std::uint64_t(w)*std::uint64_t(h)*std::uint64_t(c);if(n>SIZE_MAX)throw std::invalid_argument("codec image too large");return std::size_t(n);}
inline std::vector<std::uint8_t> encode(const std::uint8_t* in,const VideoCodecConfig& c){bytes(c.width,c.height,c.channels);if(c.quality<1||c.quality>100)throw std::invalid_argument("codec quality must be in [1,100]");if(!in)throw std::invalid_argument("null codec input"); const char* name=c.codec==VideoCodec::H264?"libx264":c.codec==VideoCodec::HEVC?"libx265":"libaom-av1"; const AVCodec* codec=avcodec_find_encoder_by_name(name); if(!codec)codec=avcodec_find_encoder(id(c.codec)); if(!codec)throw std::runtime_error("requested FFmpeg video encoder unavailable"); AVCodecContext* ctx=avcodec_alloc_context3(codec); AVFrame* f=av_frame_alloc(); AVPacket* p=av_packet_alloc(); SwsContext* sw=nullptr; try {if(!ctx||!f||!p)throw std::bad_alloc();ctx->width=c.width;ctx->height=c.height;ctx->time_base={1,25};ctx->framerate={25,1};ctx->pix_fmt=AV_PIX_FMT_YUV420P;ctx->gop_size=1;ctx->max_b_frames=0;ctx->thread_count=1;ctx->bit_rate=std::max<std::int64_t>(10000,std::int64_t(c.width)*c.height*std::max(1,c.quality)*2);if(c.codec==VideoCodec::H264)av_opt_set(ctx->priv_data,"preset","ultrafast",0);if(c.codec==VideoCodec::AV1)av_opt_set(ctx->priv_data,"cpu-used","8",0);check(avcodec_open2(ctx,codec,nullptr),"open encoder");f->format=ctx->pix_fmt;f->width=c.width;f->height=c.height;check(av_frame_get_buffer(f,32),"allocate frame");check(av_frame_make_writable(f),"writable frame");sw=sws_getContext(c.width,c.height,c.channels==1?AV_PIX_FMT_GRAY8:AV_PIX_FMT_RGB24,c.width,c.height,ctx->pix_fmt,SWS_BILINEAR,nullptr,nullptr,nullptr);if(!sw)throw std::runtime_error("create pixel conversion");const std::uint8_t* src[4]={in,nullptr,nullptr,nullptr};int stride[4]={c.width*c.channels,0,0,0};sws_scale(sw,src,stride,0,c.height,f->data,f->linesize);f->pict_type=AV_PICTURE_TYPE_I;check(avcodec_send_frame(ctx,f),"encode frame");check(avcodec_send_frame(ctx,nullptr),"flush encoder");std::vector<std::uint8_t> out;while(avcodec_receive_packet(ctx,p)==0){out.insert(out.end(),p->data,p->data+p->size);av_packet_unref(p);}if(out.empty())throw std::runtime_error("encoder produced no packet");sws_freeContext(sw);av_packet_free(&p);av_frame_free(&f);avcodec_free_context(&ctx);return out;}catch(...){if(sw)sws_freeContext(sw);av_packet_free(&p);av_frame_free(&f);avcodec_free_context(&ctx);throw;}}
inline void decode(const std::uint8_t* data,std::size_t size,std::uint8_t* out,const VideoDecodeConfig& c){auto count=bytes(c.width,c.height,c.channels);if(!data||!size||!out)throw std::invalid_argument("null or empty codec buffer");const AVCodec* codec=avcodec_find_decoder(id(c.codec));if(!codec)throw std::runtime_error("requested FFmpeg decoder unavailable");AVCodecContext* ctx=avcodec_alloc_context3(codec);AVFrame* f=av_frame_alloc();AVPacket* p=av_packet_alloc();if(!ctx||!f||!p){avcodec_free_context(&ctx);av_frame_free(&f);av_packet_free(&p);throw std::bad_alloc();}SwsContext* sw=nullptr;try{check(avcodec_open2(ctx,codec,nullptr),"open decoder");check(av_new_packet(p,int(size)),"allocate packet");std::copy(data,data+size,p->data);check(avcodec_send_packet(ctx,p),"decode packet");check(avcodec_send_packet(ctx,nullptr),"flush decoder");int r=avcodec_receive_frame(ctx,f);check(r,"receive decoded frame");sw=sws_getContext(f->width,f->height,AVPixelFormat(f->format),c.width,c.height,c.channels==1?AV_PIX_FMT_GRAY8:AV_PIX_FMT_RGB24,SWS_BILINEAR,nullptr,nullptr,nullptr);if(!sw)throw std::runtime_error("create decoded pixel conversion");std::uint8_t* dst[4]={out,nullptr,nullptr,nullptr};int stride[4]={c.width*c.channels,0,0,0};sws_scale(sw,f->data,f->linesize,0,f->height,dst,stride);sws_freeContext(sw);av_packet_free(&p);av_frame_free(&f);avcodec_free_context(&ctx);}catch(...){if(sw)sws_freeContext(sw);av_packet_free(&p);av_frame_free(&f);avcodec_free_context(&ctx);throw;}}
}}
