#include "augmatch/sensor/noise.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <stdexcept>
#include <string>
namespace augmatch { namespace {
__device__ unsigned long long vmix(unsigned long long x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
__device__ float vunit(unsigned long long x){return (float)((vmix(x)>>11)*(1.0/9007199254740992.0));}
__device__ unsigned long long vkey(unsigned long long seed,int t,int y,int x,int ch,unsigned long long tag){return seed^(unsigned long long)t*0x632be59bd9b4e019ULL^(unsigned long long)y*0x9e3779b97f4a7c15ULL^(unsigned long long)x*0x8cb92baa2f2f6f7dULL^(unsigned long long)ch*0xbf58476d1ce4e5b9ULL^tag;}
__device__ int vc(int p,int n){return max(0,min(n-1,p));}
__device__ int vt(int p,int n){return max(0,min(n-1,p));}
__device__ float vclip(float x,float lo,float hi){return fmaxf(lo,fminf(hi,x));}
__global__ void dead_kernel(const float* in,float* out,DeadPixelPersistenceConfig c){unsigned long long i=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,n=(unsigned long long)c.frames*c.height*c.width*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=(i/c.channels/c.width)%c.height;unsigned long long p=(unsigned long long)y*c.width*c.channels+(unsigned long long)x*c.channels+ch;bool hit=c.mask?c.mask[p]!=0:vunit(vkey(c.seed,0,y,x,ch,0x444541445f504552ULL))<c.probability;out[i]=vclip(hit?c.dead_value:in[i],c.clip_min,c.clip_max);}
__global__ void hot_kernel(const float* in,float* out,HotPixelPersistenceConfig c){unsigned long long i=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,n=(unsigned long long)c.frames*c.height*c.width*c.channels;if(i>=n)return;int ch=i%c.channels,x=(i/c.channels)%c.width,y=(i/c.channels/c.width)%c.height;unsigned long long p=(unsigned long long)y*c.width*c.channels+(unsigned long long)x*c.channels+ch;bool hit=c.mask?c.mask[p]!=0:vunit(vkey(c.seed,0,y,x,ch,0x484f545f50455253ULL))<c.probability;out[i]=vclip(hit?c.hot_value:in[i],c.clip_min,c.clip_max);}
__global__ void drop_kernel(const float* in,float* out,FrameDropConfig c){unsigned long long i=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,n=(unsigned long long)c.frames*c.height*c.width*c.channels;if(i>=n)return;unsigned long long plane=(unsigned long long)c.height*c.width*c.channels;int t=i/plane;bool drop=c.drop_mask?c.drop_mask[t]!=0:false;if(!c.drop_mask&&!c.drop_indices)drop=vunit(vkey(c.seed,t,0,0,0,0x44524f505f465241ULL))<c.probability;for(unsigned long long k=0;k<c.drop_count&&!drop;++k)if(c.drop_indices[k]==t)drop=true;int src=drop?t-1:t;if(src<0)out[i]=vclip(c.fill_value,c.clip_min,c.clip_max);else out[i]=in[(unsigned long long)src*plane+i%plane];}
__global__ void duplicate_kernel(const float* in,float* out,DuplicateFrameConfig c){unsigned long long i=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,n=(unsigned long long)c.frames*c.height*c.width*c.channels;if(i>=n)return;unsigned long long plane=(unsigned long long)c.height*c.width*c.channels;int t=i/plane,src;if(c.source_indices)src=c.source_indices[t];else src=vunit(vkey(c.seed,t,0,0,0,0x4455504c49434154ULL))<c.probability?t-1:t;src=vt(src<0?t:src,c.frames);out[i]=in[(unsigned long long)src*plane+i%plane];}
__global__ void blend_kernel(const float* in,float* out,FrameBlendingConfig c){unsigned long long i=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,n=(unsigned long long)c.frames*c.height*c.width*c.channels;if(i>=n)return;unsigned long long plane=(unsigned long long)c.height*c.width*c.channels;int t=i/plane,src=c.source_indices?c.source_indices[t]:t-1;if(src<0)src=t;src=vt(src,c.frames);float w=vclip(c.weights?c.weights[t]:c.weight,0,1);out[i]=vclip((1-w)*in[(unsigned long long)t*plane+i%plane]+w*in[(unsigned long long)src*plane+i%plane],c.clip_min,c.clip_max);}
__global__ void ghost_kernel(const float* in,float* out,TemporalGhostingConfig c){unsigned long long i=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,n=(unsigned long long)c.frames*c.height*c.width*c.channels;if(i>=n)return;unsigned long long plane=(unsigned long long)c.height*c.width*c.channels;int ch=i%c.channels,x=(i/c.channels)%c.width,y=(i/c.channels/c.width)%c.height,t=i/plane;TemporalGhostTransform z=c.transforms?c.transforms[t]:TemporalGhostTransform{c.source_frame_offset,c.dx,c.dy,c.alpha};int st=vt(t+z.source_frame_offset,c.frames),sx=vc(x+z.dx,c.width),sy=vc(y+z.dy,c.height);unsigned long long q=(unsigned long long)st*plane+((unsigned long long)sy*c.width+sx)*c.channels+ch;float a=vclip(z.alpha,0,1);out[i]=vclip((1-a)*in[i]+a*in[q],c.clip_min,c.clip_max);}
__global__ void motion_kernel(const float* in,float* out,MotionCompensationErrorConfig c){unsigned long long i=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,n=(unsigned long long)c.frames*c.height*c.width*c.channels;if(i>=n)return;unsigned long long plane=(unsigned long long)c.height*c.width*c.channels;int ch=i%c.channels,x=(i/c.channels)%c.width,y=(i/c.channels/c.width)%c.height,t=i/plane;MotionCompensationTransform z=c.transforms?c.transforms[t]:MotionCompensationTransform{c.source_frame_offset,c.dx,c.dy,c.weight};int st=vt(t+z.source_frame_offset,c.frames),sx=vc(x+z.dx,c.width),sy=vc(y+z.dy,c.height);unsigned long long q=(unsigned long long)st*plane+((unsigned long long)sy*c.width+sx)*c.channels+ch;float w=vclip(z.weight,0,1);out[i]=vclip((1-w)*in[i]+w*in[q],c.clip_min,c.clip_max);}
__global__ void rolling_kernel(const float* in,float* out,VideoRollingShutterConfig c){unsigned long long i=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,n=(unsigned long long)c.frames*c.height*c.width*c.channels;if(i>=n)return;unsigned long long plane=(unsigned long long)c.height*c.width*c.channels;int ch=i%c.channels,x=(i/c.channels)%c.width,y=(i/c.channels/c.width)%c.height,t=i/plane;RollingShutterTransform z;if(c.transforms)z=c.transforms[(unsigned long long)t*c.height+y];else{float phase=c.height==1?0.0f:((float)y/(c.height-1)-.5f)*c.readout_fraction;z.dx=(int)nearbyintf(c.motion_dx*phase);z.dy=(int)nearbyintf(c.motion_dy*phase);z.source_frame_offset=0;}int st=vt(t+z.source_frame_offset,c.frames),sx=vc(x+z.dx,c.width),sy=vc(y+z.dy,c.height);out[i]=vclip(in[(unsigned long long)st*plane+((unsigned long long)sy*c.width+sx)*c.channels+ch],c.clip_min,c.clip_max);}
void vcuda(cudaError_t e,const char* p){if(e!=cudaSuccess)throw std::runtime_error(std::string(p)+": "+cudaGetErrorString(e));}
void vvalid(const TemporalBatchConfig& c,const float* i,const float* o){if(c.frames<=0||c.height<=0||c.width<=0||c.channels<=0||!i||!o||!isfinite(c.clip_min)||!isfinite(c.clip_max)||c.clip_max<c.clip_min)throw std::invalid_argument("invalid video temporal configuration");}
void prob(float v,const char* m){if(!isfinite(v)||v<0||v>1)throw std::invalid_argument(m);}
void launch(unsigned long long n,const char* name){vcuda(cudaGetLastError(),name);(void)n;}
}
#define VLAUNCH(K,I,O,C,N,STREAM,NAME) do { unsigned long long _n=(unsigned long long)(N); K<<<(unsigned int)((_n+255)/256),256,0,STREAM>>>(I,O,C); launch(_n,NAME); } while(0)
void dead_pixel_persistence_f32(const float* i,float* o,const DeadPixelPersistenceConfig& c,cudaStream_t s){vvalid(c,i,o);prob(c.probability,"invalid dead-pixel probability");VLAUNCH(dead_kernel,i,o,c,(unsigned long long)c.frames*c.height*c.width*c.channels,s,"dead_pixel_persistence");}
void hot_pixel_persistence_f32(const float* i,float* o,const HotPixelPersistenceConfig& c,cudaStream_t s){vvalid(c,i,o);prob(c.probability,"invalid hot-pixel probability");VLAUNCH(hot_kernel,i,o,c,(unsigned long long)c.frames*c.height*c.width*c.channels,s,"hot_pixel_persistence");}
void frame_drops_f32(const float* i,float* o,const FrameDropConfig& c,cudaStream_t s){vvalid(c,i,o);prob(c.probability,"invalid frame-drop probability");VLAUNCH(drop_kernel,i,o,c,(unsigned long long)c.frames*c.height*c.width*c.channels,s,"frame_drops");}
void duplicate_frames_f32(const float* i,float* o,const DuplicateFrameConfig& c,cudaStream_t s){vvalid(c,i,o);prob(c.probability,"invalid duplicate probability");VLAUNCH(duplicate_kernel,i,o,c,(unsigned long long)c.frames*c.height*c.width*c.channels,s,"duplicate_frames");}
void frame_blending_f32(const float* i,float* o,const FrameBlendingConfig& c,cudaStream_t s){vvalid(c,i,o);if(!isfinite(c.weight)||c.weight<0||c.weight>1)throw std::invalid_argument("invalid frame-blending weight");VLAUNCH(blend_kernel,i,o,c,(unsigned long long)c.frames*c.height*c.width*c.channels,s,"frame_blending");}
void temporal_ghosting_f32(const float* i,float* o,const TemporalGhostingConfig& c,cudaStream_t s){vvalid(c,i,o);prob(c.alpha,"invalid ghost alpha");VLAUNCH(ghost_kernel,i,o,c,(unsigned long long)c.frames*c.height*c.width*c.channels,s,"temporal_ghosting");}
void motion_compensation_errors_f32(const float* i,float* o,const MotionCompensationErrorConfig& c,cudaStream_t s){vvalid(c,i,o);VLAUNCH(motion_kernel,i,o,c,(unsigned long long)c.frames*c.height*c.width*c.channels,s,"motion_compensation_errors");}
void video_sensor_rolling_shutter_f32(const float* i,float* o,const VideoRollingShutterConfig& c,cudaStream_t s){vvalid(c,i,o);if(!isfinite(c.motion_dx)||!isfinite(c.motion_dy)||!isfinite(c.readout_fraction))throw std::invalid_argument("invalid rolling-shutter motion");VLAUNCH(rolling_kernel,i,o,c,(unsigned long long)c.frames*c.height*c.width*c.channels,s,"video_sensor_rolling_shutter");}
#undef VLAUNCH
} // namespace augmatch
